### ISSUE TITLE
🐛 Disc ejects after a minute with log errors

### ISSUE THREAD

**Issue by roidy** [automatic-ripping-machine/automatic-ripping-machine#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After inserting a disc after a minute it ejects with errors in the log

### To Reproduce

1. put in a disc
2. error

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

20e3ac86b7a84870d7f23a60921c91468edca063

### Expected behavior?

Well I'd like it to work!

### Relevant log output

```shell
[12-24-2023 19:58:04] INFO ARM: ARM version: 2.6.67
[12-24-2023 19:58:04] INFO ARM: Python version: 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]
[12-24-2023 19:58:04] INFO ARM: User is: arm
[12-24-2023 19:58:04] INFO ARM: Alembic head is: 469d88477c13
[12-24-2023 19:58:04] INFO ARM: Database version is: 469d88477c13
[12-24-2023 19:58:05] INFO ARM: ************* Starting ARM processing at 2023-12-24 19:58:05.009322 *************
[12-24-2023 19:58:06] INFO ARM: Looking for log files older than 1 days old.
[12-24-2023 19:58:06] INFO ARM: Checking path /home/arm/logs/ for old log files...
[12-24-2023 19:58:06] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[12-24-2023 19:58:06] INFO ARM: Job: THEPERKSOFBEINGAWALLFLOWER
[12-24-2023 19:58:06] INFO ARM: Job #2 with PID 128 is currently running.
[12-24-2023 19:58:06] INFO ARM: Starting Disc identification
[12-24-2023 19:58:06] INFO ARM: Mounting disc to: /mnt/dev/sr0
[12-24-2023 19:58:06] ERROR ARM: Mounting failed! Rip might have problems
[12-24-2023 19:58:06] INFO ARM: Disc identified as video
[12-24-2023 19:58:06] ERROR ARM: Disc is a bluray, but bdmt_eng.xml could not be found. Disc cannot be identified.  Error number is: 2
[12-24-2023 19:58:06] INFO ARM: Disc title Post ident -  title:Theperksofbeingawallflower year: video_type:unknown disctype: bluray
[12-24-2023 19:58:06] INFO ARM: We have no previous rips/jobs matching this label
[12-24-2023 19:58:06] INFO ARM: Waiting 60 seconds for manual override.
[12-24-2023 19:58:36] INFO ARM: Manual override found.  Overriding auto identification values.
[12-24-2023 19:58:36] INFO ARM: ******************* Logging ARM variables *******************
[12-24-2023 19:58:36] INFO ARM: devpath: /dev/sr0
[12-24-2023 19:58:36] INFO ARM: mountpoint: /mnt/dev/sr0
[12-24-2023 19:58:36] INFO ARM: title: The Perks of Being a Wallflower
[12-24-2023 19:58:36] INFO ARM: year: 2012
[12-24-2023 19:58:36] INFO ARM: video_type: movie
[12-24-2023 19:58:36] INFO ARM: hasnicetitle: True
[12-24-2023 19:58:36] INFO ARM: label: THEPERKSOFBEINGAWALLFLOWER
[12-24-2023 19:58:36] INFO ARM: disctype: bluray
[12-24-2023 19:58:36] INFO ARM: ******************* End of ARM variables *******************
[12-24-2023 19:58:36] INFO ARM: ******************* Logging config parameters *******************
[12-24-2023 19:58:36] INFO ARM: skip_transcode: True
[12-24-2023 19:58:36] INFO ARM: mainfeature: False
[12-24-2023 19:58:36] INFO ARM: minlength: 600
[12-24-2023 19:58:36] INFO ARM: maxlength: 99999
[12-24-2023 19:58:36] INFO ARM: videotype: auto
[12-24-2023 19:58:36] INFO ARM: manual_wait: True
[12-24-2023 19:58:36] INFO ARM: manual_wait_time: 60
[12-24-2023 19:58:36] INFO ARM: ripmethod: mkv
[12-24-2023 19:58:36] INFO ARM: mkv_args: 
[12-24-2023 19:58:36] INFO ARM: delrawfiles: True
[12-24-2023 19:58:36] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[12-24-2023 19:58:36] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[12-24-2023 19:58:36] INFO ARM: hb_args_dvd: --subtitle scan -F
[12-24-2023 19:58:36] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[12-24-2023 19:58:36] INFO ARM: raw_path: /home/arm/media/raw/
[12-24-2023 19:58:36] INFO ARM: transcode_path: /home/arm/media/transcode/
[12-24-2023 19:58:36] INFO ARM: completed_path: /home/arm/media/completed/
[12-24-2023 19:58:36] INFO ARM: extras_sub: extras
[12-24-2023 19:58:36] INFO ARM: emby_refresh: False
[12-24-2023 19:58:36] INFO ARM: emby_server: 
[12-24-2023 19:58:36] INFO ARM: emby_port: 8096
[12-24-2023 19:58:36] INFO ARM: notify_rip: True
[12-24-2023 19:58:36] INFO ARM: notify_transcode: True
[12-24-2023 19:58:36] INFO ARM: max_concurrent_transcodes: 0
[12-24-2023 19:58:36] INFO ARM: ******************* End of config parameters *******************
[12-24-2023 19:58:36] INFO ARM: Checking for fstab entry.
[12-24-2023 19:58:36] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[12-24-2023 19:58:36] INFO ARM: Final Output directory "/home/arm/media/transcode/movies/The Perks of Being a Wallflower (2012)"
[12-24-2023 19:58:36] INFO ARM: Final Output directory "/home/arm/media/completed/movies/The Perks of Being a Wallflower (2012)"
[12-24-2023 19:58:36] INFO ARM: Processing files to: /home/arm/media/transcode/movies/The Perks of Being a Wallflower (2012)
[12-24-2023 19:58:36] INFO ARM: ************* Ripping disc with MakeMKV *************
[12-24-2023 19:58:36] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-dG00FDKJOJvB3LTHvPqfEK76znNpkkSoOyI3ZNmEEsVG1livUJHxfvSMI3tsfZfoVS
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[12-24-2023 19:58:37] INFO ARM: Starting MakeMKV rip. Method is mkv
[12-24-2023 19:58:38] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[12-24-2023 19:58:38] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[12-24-2023 19:58:38] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 46, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 53, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 203, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[12-24-2023 19:58:38] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

makemkvcon says it can't find my optical drive.

makemkvcon -r info disc:9999
MSG:1005,0,1,"MakeMKV v1.17.5 linux(x64-release) started","%1 started","MakeMKV v1.17.5 linux(x64-release)"
MSG:5042,0,0,"The program can't find any usable optical drives.","The program can't find any usable optical drives."
DRV:0,256,999,0,"","",""
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
TCOUNT:0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Please post a copy of your `start-arm-container.sh`, as well as the output of `lsscsi -g` run on the host
