### ISSUE TITLE
🐛 database gets created, but initialization failing with "database is locked"

### ISSUE THREAD

**Issue by VincentKueszter** [automatic-ripping-machine/automatic-ripping-machine#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Running `sudo ./start_arm_container.sh`  will start the container, but the UI is not accessible, due to the database not being initialized correctly.

### To Reproduce

Environment:
- Ubuntu 20.04 VM as a host for the ARM Docker
- ARM installed by following https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker
- The folders of the Ubuntu host that get mounted for the docker are CIFS mounts (mounted to /media/arm_data), if that makes a difference. uid/gid set to arm:arm when mounting in fstab.

1.  make sure directories on the host are owned by arm:arm, which has id 1000:1000 (see output below)
2. `docker system prune -a --volumes` to make sure we are in a clean environment
3. make sure the directory /media/arm_data/db is empty
4. `sudo ./start_arm_container.sh` (file content listed below) successfully pulls latest container, starts it accordingly
5. `docker logs automatic-ripping-machine` to see current output, attached below. Main error: `database is locked` The second error (`no such table: alembic_version`) will repeat indefinitely, since the UI keeps trying to start.
6. observe that a 0kB file arm.db now exists in /media/arm_data/db, owned by arm:arm
7. any further starts with this file in place will only show the second error, since the DB is there, but empty.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.72
43ed1e4ce3d2d797405556768e97adb67230b5f9

### Expected behavior?

start_arm_container.sh successfully initializes the database, so that the UI can run.

### Relevant log output

```shell
*** Running /etc/my_init.d/10_syslog-ng.init...
Apr  1 10:09:20 97d1aa6bacb5 syslog-ng[13]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm group id 1000 to default (1000)...
usermod: no changes
Updating arm group id 1000 to default (1000)...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1000:1000
Removing any link between music and Music
Checking ownership of /etc/arm/config
[OK]: ARM UID and GID set correctly, ARM has access to '/etc/arm/config' using 1000:1000
Checking location of abcde configuration files
/etc/abcde.conf link doesnt exist
*** Running /etc/my_init.d/start_udev.sh...
/etc/my_init.d/start_udev.sh: 0: can't access tty; job control turned off
Trying to start udev
udev Started successfully
# # # # # #
*** Booting runit daemon...
*** Runit started as PID 96
Starting web ui
Apr  1 10:09:27 97d1aa6bacb5 cron[99]: (CRON) INFO (pidfile fd = 3)
Apr  1 10:09:27 97d1aa6bacb5 cron[99]: (CRON) INFO (Running @reboot jobs)
[2024-04-01 10:09:28,283] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-04-01 10:09:28,387] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-04-01 10:09:28,389] DEBUG ARM: utils.arm_db_check Database file is not present: /home/arm/db/arm.db
[2024-04-01 10:09:28,389] DEBUG ARM: utils.arm_db_cfg No armui cfg setup
[2024-04-01 10:09:28,389] INFO ARM: utils.check_db_version No database found.  Initializing arm.db...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import db  # needs to be imported before models
  File "/opt/arm/arm/../arm/ui/__init__.py", line 66, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 28, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 206, in arm_db_cfg
    check_db_version(cfg.arm_config['INSTALLPATH'], cfg.arm_config['DBFILE'])
  File "/opt/arm/arm/../arm/ui/utils.py", line 88, in check_db_version
    flask_migrate.upgrade(mig_dir)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 399, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "/opt/arm/arm/migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "/opt/arm/arm/migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/environment.py", line 937, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 607, in run_migrations
    self._ensure_version_table()
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 545, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 1291, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 955, in visit_table
    CreateTable(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Starting web ui
[2024-04-01 10:09:34,350] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-04-01 10:09:34,431] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: alembic_version

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import db  # needs to be imported before models
  File "/opt/arm/arm/../arm/ui/__init__.py", line 66, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 28, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 203, in arm_db_cfg
    db_update = arm_db_check()
  File "/opt/arm/arm/../arm/ui/utils.py", line 171, in arm_db_check
    db_revision = arm_db_get()
  File "/opt/arm/arm/../arm/ui/utils.py", line 150, in arm_db_get
    db_revision = alembic_db.query.first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: alembic_version
[SQL: SELECT alembic_version.version_num AS alembic_version_version_num
FROM alembic_version
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

arm@arm:~$ ls -al /media/arm_data/
total 4
drwxr-xr-x 2 arm  arm     0 Mar 31 20:01 .
drwxr-xr-x 3 root root 4096 Mar 31 19:41 ..
drwxr-xr-x 2 arm  arm     0 Mar 31 20:01 config
drwxr-xr-x 2 arm  arm     0 Apr  1 10:53 db
drwxr-xr-x 2 arm  arm     0 Mar 31 20:01 logs
drwxr-xr-x 2 arm  arm     0 Mar 31 20:10 .MakeMKV
drwxr-xr-x 2 arm  arm     0 Mar 31 20:01 media
drwxr-xr-x 2 arm  arm     0 Mar 31 19:54 music

arm@arm:~$ ls -al /media/arm_data/db
total 1
drwxr-xr-x 2 arm arm 0 Apr  1 11:29 .
drwxr-xr-x 2 arm arm 0 Mar 31 20:01 ..
-rwxr-xr-x 1 arm arm 0 Apr  1 10:53 arm.db

arm@arm:~$ nano start_arm_container.sh
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -v "/media/arm_data/:/home/arm" \
    -v "/media/arm_data/music/:/home/arm/music" \
    -v "/media/arm_data/logs/:/home/arm/logs" \
    -v "/media/arm_data/media/:/home/arm/media" \
    -v "/media/arm_data/config/:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --privileged \
    --name "automatic-ripping-machine" \
    --cpuset-cpus='0,1' \
    automaticrippingmachine/automatic-ripping-machine:latest
```

### Anything else?

Thank you in advance!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Odd, what happens if you delete the arm.db file?

**Comment by VincentKueszter** [comment]
Same situation, it tries to create it and then fails with the same error (database is locked).
I wonder if an initialized, but empty database file would be a workaround - or if this is a general problem.

**Comment by SylvainMT** [comment]
Are you running AppArmor or SELinux by any chance?

**Comment by VincentKueszter** [comment]
> Are you running AppArmor or SELinux by any chance?

AppArmor, but only the defaults.
I tried deactivating it with `sudo aa-teardown` and confirmed with `sudo aa-status` that it stopped running, but no success - still `database is locked`.

**Comment by VincentKueszter** [comment]
This works without issue.
```
Starting web ui
Apr  1 20:17:29 9014a39d4700 cron[98]: (CRON) INFO (pidfile fd = 3)
Apr  1 20:17:29 9014a39d4700 cron[98]: (CRON) INFO (Running @reboot jobs)
[2024-04-01 20:17:30,577] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-04-01 20:17:30,682] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-04-01 20:17:30,682] DEBUG ARM: utils.arm_db_check Database file is not present: /home/arm/db/arm.db
[2024-04-01 20:17:30,682] DEBUG ARM: utils.arm_db_cfg No armui cfg setup
[2024-04-01 20:17:30,683] INFO ARM: utils.check_db_version No database found.  Initializing arm.db...
[2024-04-01 20:17:31,354] DEBUG ARM: utils.check_db_version Alembic Head is: 469d88477c13
[2024-04-01 20:17:31,356] DEBUG ARM: utils.check_db_version Database version is: 469d88477c13
[2024-04-01 20:17:31,357] INFO ARM: utils.check_db_version Database is up to date
[2024-04-01 20:17:31,394] DEBUG ARM: utils.setup_database Number of admins: 0
[2024-04-01 20:17:31,394] DEBUG ARM: utils.setup_database Found User table but didnt find any admins...
[2024-04-01 20:17:31,648] DEBUG ARM: utils.setup_database DB Init - Admin user loaded
[2024-04-01 20:17:31,652] DEBUG ARM: utils.setup_database DB Init - Server info loaded
[2024-04-01 20:17:31,701] DEBUG ARM: DriveUtils.drives_search regex output: /dev/sr0
[2024-04-01 20:17:31,704] INFO ARM: DriveUtils.drives_search System disk scan, found 1 drives for ARM
[2024-04-01 20:17:31,704] DEBUG ARM: DriveUtils.drives_search disk: /dev/sr0
[2024-04-01 20:17:31,729] DEBUG ARM: DriveUtils.drives_update ****** Drive Information ******
[2024-04-01 20:17:31,729] DEBUG ARM: DriveUtils.drives_update Name: Drive 1
[2024-04-01 20:17:31,730] DEBUG ARM: DriveUtils.drives_update Type: CD/BluRay/DVD
[2024-04-01 20:17:31,730] DEBUG ARM: DriveUtils.drives_update Mount: /dev/sr0
[2024-04-01 20:17:31,730] DEBUG ARM: DriveUtils.drives_update ****** End Drive Information ******
[2024-04-01 20:17:31,767] INFO ARM: DriveUtils.drives_update Added 1 drives for ARM.
[2024-04-01 20:17:31,767] DEBUG ARM: utils.setup_database DB Init - Drive info loaded
[2024-04-01 20:17:31,778] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f1c9a350ee0>) (use_icons=True) (bootstrap_skin=spacelab) (index_refresh=2000) (notify_refresh=6500) (language=en) (id=1) (save_remote_images=True) (database_limit=200)
[2024-04-01 20:17:31,789] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-04-01 20:17:31,794] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
[2024-04-01 20:17:31,794] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13
[2024-04-01 20:17:31,794] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f1c9a350ee0>) (use_icons=True) (bootstrap_skin=spacelab) (index_refresh=2000) (notify_refresh=6500) (language=en) (id=1) (save_remote_images=True) (database_limit=200)
[2024-04-01 20:17:31,850] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-04-01 20:17:31,852] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
[2024-04-01 20:17:31,852] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13
[2024-04-01 20:17:31,852] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f1c9a350ee0>) (use_icons=True) (bootstrap_skin=spacelab) (index_refresh=2000) (notify_refresh=6500) (language=en) (id=1) (save_remote_images=True) (database_limit=200)
[2024-04-01 20:17:31,854] INFO ARM: runui.<module> Starting ARM-UI on interface address - 172.17.0.2:8080
[2024-04-01 20:17:31,874] INFO ARM: wasyncore.log_info Serving on http://172.17.0.2:8080
```
Unfortunately, I kind of need it to run on a network share.
Do you think this is a general issue the ARM docker has with network shares or might this be fixable by trying to edit the properties (e.g. permissions) of the share itself?

**Comment by microtechno9000** [comment]
The database is only a single file, all the rips and transcodes are put into another series of folders and a separate volume.

It may be an issue with the network share, permissions or SQlite over the network.

At the moment there isn't anything we can do with ARM to help. Upgrading to a mysql docker container is on the development path at the moment

**Comment by VincentKueszter** [comment]
Ok, thank you.
I will try exploring this more - for now I can report that processing a music CD worked.
If I find out how to make the DB on a network share work, I will post it here!

Thank you for your help.

**Comment by VincentKueszter** [comment]
I found a solution for mounting a network share:
CIFS mounts have to be mounted with the `nobrl` flag.
See this issue for details: https://github.com/docker/for-win/issues/11
Example for my case: 
```
sudo unmount /media/arm-data
sudo nano /etc/fstab // add nobrl to the list of flags for the cifs mount
sudo mount -a
```

**Comment by VincentKueszter** [comment]
> Welcome to add to the troubleshoot wiki for others

Already on it! :)

**Comment by Gonkers** [comment]
Thanks for reporting this issue. I was just getting started with ARM and ran into this exact issue. Mounting the share with `nobrl` did the trick for me. Thank you.
