### ISSUE TITLE
🐋 Call to MakeMKV failed with code: 1 (b'')

### ISSUE THREAD

**Issue by Cody-W-Tucker** [automatic-ripping-machine/automatic-ripping-machine#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

MakeMKV fails and the error output isn't clear. (at least to me.)

The wiki lists steps but I don't see anything that matches my error.

### To Reproduce

1. In nixos using docker
2. With this config
```bash
Docker run command:
docker run -d \
   -p "8080:8080" \
   -e ARM_UID="1002" \
   -e ARM_GID="983" \
   -v "/home/arm:/home/arm" \
   -v "/home/arm/Music:/home/arm/Music" \
   -v "/home/arm/logs:/home/arm/logs" \
   -v "/home/arm/media:/home/arm/media" \
   -v "/home/arm/config:/etc/arm/config" \
   --device=/dev/sr0:/dev/sr0 \
   --privileged \
   --restart "always" \
   --name "arm-rippers" \
   1337server/automatic-ripping-machine:latest
```
3. Insert a disk
4. Disk fails to rip
5. See error in logs

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

I'd expect the errors to give some idea of the problem. Currently, I can't tell if the issue is my system's issue or with the docker container. I assume it's on my end, but I don't know what needs to change. I followed the wiki steps and installed the official image.

### Relevant log output

```shell
ARM: [ARM] Entering docker wrapper
ARM: [ARM] Starting ARM for DVD on sr0
DEBUG ARM: json_api.process_logfile active
DEBUG ARM: json_api.process_logfile using handbrake
DEBUG ARM: json_api.process_handbrake_logfile Cant find index
DEBUG ARM: json_api.get_x_jobs couldn't get config
DEBUG ARM: json_api.get_x_jobs jobs  - we have 1 jobs
DEBUG ARM: json_api.process_logfile active
DEBUG ARM: json_api.process_logfile using handbrake
DEBUG ARM: utils.database_updater Setting seen: 1
DEBUG ARM: utils.database_updater Setting dismiss_time: 2024-06-27 15:29:23.024599
DEBUG ARM: utils.database_updater successfully written to the database
DEBUG ARM: json_api.process_logfile ripping
DEBUG ARM: json_api.process_logfile using mkv - /home/arm/logs/THE_MAGNIFICENT_SEVEN_2016_171950215159.log
tail: cannot open '/home/arm/logs/progress/2.log' for reading: No such file or directory
DEBUG ARM: json_api.read_log_line Error while reading logfile for ETA
DEBUG ARM: json_api.get_x_jobs jobs  - we have 1 jobs
ARM: eject: device name is `/dev/sr0'
ARM: eject: expanded name is `/dev/sr0'
ARM: eject: `/dev/sr0' is not mounted
ARM: eject: `/dev/sr0' is not a mount point
ARM: eject: `/dev/sr0' is not a multipartition device
ARM: eject: trying to eject `/dev/sr0' using SCSI commands
ARM: eject: SCSI eject succeeded
ARM: [ARM] Entering docker wrapper
ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0

INFO ARM: ARM version: 2.6.67
INFO ARM: Python version: 3.8.10 (default, Nov 22 2023, 10:22:35) 
INFO ARM: User is: arm
INFO ARM: Alembic head is: 469d88477c13
INFO ARM: Database version is: 469d88477c13
INFO ARM: ************* Starting ARM processing at 2024-06-27 15:25:29.780333 *************
INFO ARM: Looking for log files older than 1 days old.
INFO ARM: Checking path /home/arm/logs/ for old log files...
INFO ARM: Checking path /home/arm/logs/progress for old log files...
INFO ARM: Job: THE_MAGNIFICENT_SEVEN_2016
INFO ARM: Job #1 with PID 280 is currently running.
INFO ARM: Starting Disc identification
INFO ARM: Mounting disc to: /mnt/dev/sr0
INFO ARM: Mounting disc was successful
INFO ARM: Disc identified as video
INFO ARM: DVD CRC64 hash is: a42e0ff7ce30e73f
INFO ARM: Disc title Post ident -  title:The-Magnificent-Seven year:2016 video_type:movie disctype: dvd
INFO ARM: We have no previous rips/jobs matching this label
INFO ARM: Waiting 60 seconds for manual override.
INFO ARM: ******************* Logging ARM variables *******************
INFO ARM: devpath: /dev/sr0
INFO ARM: mountpoint: /mnt/dev/sr0
INFO ARM: title: The-Magnificent-Seven
INFO ARM: year: 2016
INFO ARM: video_type: movie
INFO ARM: hasnicetitle: True
INFO ARM: label: THE_MAGNIFICENT_SEVEN_2016
INFO ARM: disctype: dvd
INFO ARM: ******************* End of ARM variables *******************
INFO ARM: ******************* Logging config parameters *******************
INFO ARM: skip_transcode: False
INFO ARM: mainfeature: False
INFO ARM: minlength: 600
INFO ARM: maxlength: 99999
INFO ARM: videotype: auto
INFO ARM: manual_wait: True
INFO ARM: manual_wait_time: 60
INFO ARM: ripmethod: mkv
INFO ARM: mkv_args: 
INFO ARM: delrawfiles: True
INFO ARM: hb_preset_dvd: HQ 720p30 Surround
INFO ARM: hb_preset_bd: HQ 1080p30 Surround
INFO ARM: hb_args_dvd: --subtitle scan -F
INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
INFO ARM: raw_path: /home/arm/media/raw/
INFO ARM: transcode_path: /home/arm/media/transcode/
INFO ARM: completed_path: /home/arm/media/completed/
INFO ARM: extras_sub: extras
INFO ARM: emby_refresh: False
INFO ARM: emby_server: 
INFO ARM: emby_port: 8096
INFO ARM: notify_rip: True
INFO ARM: notify_transcode: True
INFO ARM: max_concurrent_transcodes: 0
INFO ARM: ******************* End of config parameters *******************
INFO ARM: Checking for fstab entry.
INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
INFO ARM: Final Output directory "/home/arm/media/transcode/movies/The-Magnificent-Seven (2016)"
INFO ARM: Final Output directory "/home/arm/media/completed/movies/The-Magnificent-Seven (2016)"
INFO ARM: Processing files to: /home/arm/media/transcode/movies/The-Magnificent-Seven (2016)
INFO ARM: ************* Ripping disc with MakeMKV *************
INFO ARM: Updating MakeMKV key...
INFO ARM: Starting MakeMKV rip. Method is mkv
ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException


ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 46, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 53, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 203, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

I'm using NixOs with oci-containers.

```Nix
{
  virtualisation = {
    docker.enable = true;
    oci-containers.backend = "docker";
  };

  virtualisation.oci-containers.containers."arm-rippers" = {
    autoStart = false; # Assuming you want the container to start automatically on boot
    image = "1337server/automatic-ripping-machine:latest";
    ports = [ "8080:8080" ];
    environment = {
      ARM_UID = "1002";
      ARM_GID = "983";
    };
    volumes = [
      "/home/arm:/home/arm"
      "/home/arm/Music:/home/arm/Music"
      "/home/arm/logs:/home/arm/logs"
      "/home/arm/media:/home/arm/media"
      "/home/arm/config:/etc/arm/config"
    ];
    extraOptions = [
      "--device=/dev/sr0:/dev/sr0"
      "--privileged"
    ];
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.arm = {
    isNormalUser = true;
    description = "arm";
    group = "arm";
    extraGroups = [ "arm" "cdrom" "video" "docker" ];
    hashedPassword = "$y$j9T$2gGzaHfv1JMUMtHdaXBGF/$RoEaBINI46v1yFpR1bSgPc9ovAyzqjgSSTxuNhRiOn4";
  };

  users.groups.arm = { };

  # Enable udev
  services.udev.enable = true;

}
```
This creates an fstab entry for the disk drive.

```Nix
  fileSystems."/mnt/dev/sr0" =
    {
      device = "/dev/sr0";
      fsType = "udf,iso9660";
      options = [ "users" "noauto" "exec" "utf8" ];
    };
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fairct** [comment]
I am using a very similar setup (also using NixOS with oci containers) and I get the same vague error on blu-rays

**Comment by shitwolfymakes** [comment]
I think y'all might be the first NixOS users we have, but this shouldn't be an issue related to the OS. Not sure what error code 1 is for MakeMKV

**Comment by shitwolfymakes** [comment]
This is an error in the call to makemkv, arm is just returning the error code. Not sure what's causing this bc MakeMKV's docs are awful :/

**Comment by dbeta** [comment]
Another NixOS user here. I'm using podman as my container, but had the exact same problem. After some troubleshooting and searching and hair pulling, I figured it out. MakeMKV needs both sr0 and sg0. You might be saying to yourself, "I've `ls /dev` a million times and I have no sg0". A quick `sudo modprob sb` will add sg0, then you can pass that into docker/podman just like sr0. 

I just figured it out and haven't figured out how to incorporate the modprobe command into the NixOS config, but it seems to be working with the manual action.

**Comment by Cody-W-Tucker** [comment]
This might be interesting, [this nixos forum post](https://discourse.nixos.org/t/makemkv-cant-find-my-usb-blu-ray-drive/23714/4)  suggested adding `boot.kernelModules = [ “sg” ];` to persist the setting across reboots.

I'll try it soon and see if this fixes it for me too! Thanks for posting

**Comment by Cody-W-Tucker** [comment]
Adding `boot.kernelModules = [ “sg” ];` allows me to rip dvd's but I couldn't figure out how to get intelQSV to work. Also, all DVDs rip at 404p instead of the preset 720p.

**Comment by dbeta** [comment]
I don't know about IntelQSV, but for NVIDIA hardware encoding I had to pass the GPU into docker/podman with `"--device=nvidia.com/gpu=all"` as an extra option. I'm guessing Intel needs something similar. As for the 404p, I can't say, mine are ripping at 1080p as the arm.config file suggests. If you want 720p, I'd suggest making sure the BD preset is set to `HQ 720p30 Surround` until you get your IntelQSV working.

**Comment by Cody-W-Tucker** [comment]
Interesting. Are you ripping DVDs or blu-rays? Apparently DVDs are 480p.

**Comment by dbeta** [comment]
Oh, sorry, I misread your message. I'm mostly doing bluray. Some of the DVDs I did try ended up at 480p, but they were ancient ones, of even ancienter movies, so I assumed that had something to do with it.

**Comment by Cody-W-Tucker** [comment]
Thanks again @dbeta adding `boot.kernelModules = [ “sg” ];` solves this and allows ripping.

To get QSV working, I followed the instructions on the [IntelQSV wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/intel-qsv). It took me a little while to realize the docker container was running Ubuntu, so I used `docker exec -t -i arm-rippers /bin/bash` to enter the container's bash environment, enabled sudo with `apt-get install sudo` because sudo isn't enabled by default, and then ran the script provided.

Here's the working config for NixOS

```nix
{
  # Enable docker, it probably works with Podman too.
  virtualisation = {
      docker.enable = true;
      oci-containers.backend = "docker";
    };

  # Load the 'sg' kernel module to allow the container to see disk drives
  boot.kernelModules = [ "sg" ];

  # Enable udev to allow the container to see disk drives and other devices
  services.udev.enable = true;

  # Open port 9090 for the web UI of the container
  networking.firewall.allowedTCPPorts = [ 8080 ];

  # Create a user 'arm' for the container; set the password with `passwd`
  users.users.arm = {
    isNormalUser = true;
    description = "arm";
    group = "arm";
    extraGroups = [ "arm" "cdrom" "video" "render" "docker" ];
  };

  # Create a group 'arm' for the container
  users.groups.arm = { };

  # Configure the ARM container
  virtualisation.oci-containers.containers."arm-rippers" = {
    autoStart = true; # Automatically start the container on boot
    image = "automaticrippingmachine/automatic-ripping-machine:latest"; # Docker image for ARM
    ports = [ "8080:8080" ];
    # TODO: Use id arm to get the UID and GID for the arm user after creation
    environment = {
      ARM_UID = "<ARM_UID>"; # UID of the 'arm' user on the host system
      ARM_GID = "<ARM_UID>"; # GID of the 'arm' group on the host system
    };
    # Mount 'host directory' to 'container directory'
    volumes = [
      "/home/arm:/home/arm"
      "/home/arm/Music:/home/arm/Music"
      "/home/arm/logs:/home/arm/logs"
      "/home/arm/media:/home/arm/media"
      "/home/arm/config:/etc/arm/config"
    ];
    extraOptions = [
      "--device=/dev/sr0:/dev/sr0" # Pass through the CD/DVD drive
      "--device=/dev/dri:/dev/dri" # For IntelQSV support, add the GPU device to the container and follow [the IntelQSV instructions in the ARM wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/intel-qsv).
      "--privileged" # Run the container in privileged mode
    ];
  };
}
```
