### ISSUE TITLE
MakeMKV error not properly propagated.

### ISSUE THREAD

**Issue by johnhelt** [automatic-ripping-machine/automatic-ripping-machine#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Trying to rip a BR, and ARM fails (MakeMKV). The error is not properly propagated and python raises a lot of errors, obscuring the cause of the issue. 

### To Reproduce

1. I'm running the docker image (latest)
2. Insert BR
3. wait for rip to fail (not sure if this is particularly an error related to this BR).

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.8.0 
Current git version: 1e0f496 

### Expected behavior?

I would expect the error from makeMKV to be properly propagated so I can begin debugging.

### Relevant log output

```shell
[09-05-2024 09:48:22] DEBUG ARM: makemkv.run_makemkv Ripping with the following command: makemkvcon mkv --profile=/etc/arm/config/profile.xml  -r --progress=/home/arm/logs/progress/12.log --messages=-stdout dev:/dev/sr0 all /home/arm/media/raw/The-Lego-Movie-2--The-Second-Part_172552962130 --minlength=600
MSG:1005,0,1,"MakeMKV v1.17.7 linux(x64-release) started","%1 started","MakeMKV v1.17.7 linux(x64-release)"
MSG:5042,0,0,"The program can't find any usable optical drives.","The program can't find any usable optical drives."
DRV:0,256,999,0,"","",""
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:2024,16777216,1,"Unknown device - '/dev/sr0'","Unknown device - '%1'","/dev/sr0"
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
[09-05-2024 09:48:23] ERROR ARM: makemkv.__init__ Call to MakeMKV failed with code: 11 (b'')
[09-05-2024 09:48:23] ERROR ARM: arm_ripper.rip_visual_media MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[09-05-2024 09:48:23] ERROR ARM: main.<module> 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 327, in run_makemkv
    subprocess.run(f"{cmd} >> {logfile}", capture_output=True, shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon mkv --profile=/etc/arm/config/profile.xml  -r --progress=/home/arm/logs/progress/12.log --messages=-stdout dev:/dev/sr0 all /home/arm/media/raw/The-Lego-Movie-2--The-Second-Part_172552962130 --minlength=600 >> /home/arm/logs/LEGO_Movie_2_172552962130.log' returned non-zero exit status 11.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 80, in makemkv
    run_makemkv(cmd, logfile)
  File "/opt/arm/arm/ripper/makemkv.py", line 329, in run_makemkv
    raise MakeMkvRuntimeError(mkv_error) from mkv_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 213, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
```

### Anything else?

It seems the error is related to the drive? I have ripped many BR and DVDs with this drive, so I'm a bit confused why this is suddenly an issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
This is in part a limitation due to the Python GIL and the way logs are fed to stout.

A separate process is started for handbrake, but a monitor is not able to sit and supervise as handbrake runs as a blocking process. The logs are fed in using the UI, looking for changes, not the best solution but it works in most cases.

I will have a look to see what error handling processes could be improved. The focus at the moment is on rewriting ARM in v3.0, so will see if we can roll that into future ARM.

**Comment by microtechno9000** [comment]
Closing as a duplicate issue has been raised, in what appears to be an issue with new MakeMKV #1195
