### ISSUE TITLE
🐛 Process stuck at [[ARM] Starting ARM for Bluray on sr0

### ISSUE THREAD

**Issue by SunnyMoonSchott** [automatic-ripping-machine/automatic-ripping-machine#1209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After inserting a disc the docker logs show:

```
Oct  5 23:36:50 ea0335bc99a6 ARM: [ARM] Entering docker wrapper
Oct  5 23:36:50 ea0335bc99a6 ARM: Sat Oct  5 23:36:50 UTC 2024 [[ARM] Starting ARM for Bluray on sr0
```
or 

```
Oct  5 23:39:21 ea0335bc99a6 ARM: [ARM] Entering docker wrapper
Oct  5 23:39:23 ea0335bc99a6 ARM: [ARM] Starting ARM for DVD on sr0
```

Showing that the udev rules are working and it's recogizing the disc as either dvd or Bluray but then there is no other movement, no logs are created and there is no further output in the docker logs until the disc is ejected.

### To Reproduce

1. Follow Docker Pre-build instructions and start the docker container.
2. Insert a dvd or BluRay and wait.

This is my start_arm_containers.sh
```
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1001" \
    -e ARM_GID="1002" \
    -v "/home/arm:/home/arm" \
    -v "/media/arm/music:/home/arm/music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/media/arm/media:/home/arm/media" \
    -v "/home/sunny/automatic-ripping-machine/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
   --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='1' \
    automaticrippingmachine/automatic-ripping-machine:latest
```

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.8.1
Current git version: 3de4d52

### Expected behavior?

Expected behaviour would be for the process of ripping to begin.

### Relevant log output

```shell
*** Running /etc/my_init.d/10_syslog-ng.init...
Oct  5 23:35:50 ea0335bc99a6 syslog-ng[13]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm user id from 1000 to 1001...
Updating arm group id from 1000 to 1002...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1002
Removing any link between music and Music
Checking ownership of /etc/arm/config
[OK]: ARM UID and GID set correctly, ARM has access to '/etc/arm/config' using 1001:1002
Checking location of abcde configuration files
/etc/abcde.conf link doesnt exist
*** Running /etc/my_init.d/start_udev.sh...
/etc/my_init.d/start_udev.sh: 0: can't access tty; job control turned off
Trying to start udev
# # # # # # 
udev Started successfully
*** Booting runit daemon...
*** Runit started as PID 107
Starting web ui
Oct  5 23:35:54 ea0335bc99a6 cron[110]: (CRON) INFO (pidfile fd = 3)
Oct  5 23:35:54 ea0335bc99a6 cron[110]: (CRON) INFO (Running @reboot jobs)
[2024-10-05 23:35:56,972] INFO ARM: __init__.<module> Setting log level to: INFO
[2024-10-05 23:35:57,418] INFO ARM: runui.<module> Starting ARM-UI on interface address - 172.17.0.2:8080
[2024-10-05 23:35:57,439] INFO ARM: wasyncore.log_info Serving on http://172.17.0.2:8080
Oct  5 23:36:13 ea0335bc99a6 ARM: [ARM] Entering docker wrapper
Oct  5 23:36:13 ea0335bc99a6 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Oct  5 23:36:15 ea0335bc99a6 ARM: [ARM] Entering docker wrapper
Oct  5 23:36:15 ea0335bc99a6 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Oct  5 23:36:50 ea0335bc99a6 ARM: [ARM] Entering docker wrapper
Oct  5 23:36:50 ea0335bc99a6 ARM: Sat Oct  5 23:36:50 UTC 2024 [[ARM] Starting ARM for Bluray on sr0
```
```


### Anything else?

Ubuntu 24.04.1

I suspect it might be to do with this udev rules issue as I don't get any output here, but it's unclear from the wiki what actions should be taken to rectify this. 

<img width="952" alt="Screenshot 2024-10-06 at 12 50 41 AM" src="https://github.com/user-attachments/assets/1a509d48-0503-4c8a-89f0-9981fae09052">


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SunnyMoonSchott** [comment]
i've just noticed that after a while it will add to the docker logs:

```
[2024-10-05 23:50:50,897] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
[2024-10-05 23:55:51,172] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by microtechno9000** [comment]
Does the web page show the job and do you get a log for the job?

Can you post with logging set to debug

**Comment by SunnyMoonSchott** [comment]
The web UI is fully functional (I'm able to change settings through it to
add API keys) but no jobs appear.

**Comment by microtechno9000** [comment]
Do you get any logs in the logs directory?

The ripper creates a log for each job, seperate to the Web page

**Comment by SunnyMoonSchott** [comment]
Nope, no logs created. Just checked and the log folder was owned by root, as was the /home/arm folder so I've changed that to arm:arm and I'll run it again, see if that helps.

**Comment by microtechno9000** [comment]
That will help, as it won't be able to write to the folder

**Comment by SunnyMoonSchott** [comment]
```
Loading log: BEST_EXOTIC_F1_172821050469.log...
[10-06-2024 10:28:24] INFO ARM: ARM version: 2.8.1
[10-06-2024 10:28:24] INFO ARM: Python version: 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0]
[10-06-2024 10:28:24] INFO ARM: User is: arm
[10-06-2024 10:28:24] INFO ARM: Alembic head is: b326a3663939
[10-06-2024 10:28:24] INFO ARM: Database version is: b326a3663939
[10-06-2024 10:28:24] INFO ARM: ************* Starting ARM processing at 2024-10-06 10:28:24.729885 *************
[10-06-2024 10:28:25] INFO ARM: Looking for log files older than 1 days old.
[10-06-2024 10:28:25] INFO ARM: Checking path /home/arm/logs/ for old log files...
[10-06-2024 10:28:25] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[10-06-2024 10:28:25] INFO ARM: Job: BEST_EXOTIC_F1
[10-06-2024 10:28:25] INFO ARM: Job #2 with PID 375 is currently running.
[10-06-2024 10:28:25] INFO ARM: Starting Disc identification
[10-06-2024 10:28:25] INFO ARM: Mounting disc to: /mnt/dev/sr0
[10-06-2024 10:28:27] INFO ARM: Mounting disc was successful
[10-06-2024 10:28:28] INFO ARM: Disc identified as video
[10-06-2024 10:28:30] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:31] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:32] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:33] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:34] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:35] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:36] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:36] INFO ARM: Disc title Post ident -  title:THE-BEST-EXOTIC-MARIGOLD-HOTEL year:2012 video_type:unknown disctype: bluray
[10-06-2024 10:28:36] INFO ARM: We have no previous rips/jobs matching this label
[10-06-2024 10:28:36] INFO ARM: Waiting 60 seconds for manual override.
[10-06-2024 10:29:36] INFO ARM: ******************* Logging ARM variables *******************
[10-06-2024 10:29:36] INFO ARM: devpath: /dev/sr0
[10-06-2024 10:29:36] INFO ARM: mountpoint: /mnt/dev/sr0
[10-06-2024 10:29:36] INFO ARM: title: THE-BEST-EXOTIC-MARIGOLD-HOTEL
[10-06-2024 10:29:36] INFO ARM: year: 2012
[10-06-2024 10:29:36] INFO ARM: video_type: unknown
[10-06-2024 10:29:36] INFO ARM: hasnicetitle: False
[10-06-2024 10:29:36] INFO ARM: label: BEST_EXOTIC_F1
[10-06-2024 10:29:36] INFO ARM: disctype: bluray
[10-06-2024 10:29:36] INFO ARM: ******************* End of ARM variables *******************
[10-06-2024 10:29:36] INFO ARM: ******************* Logging config parameters *******************
[10-06-2024 10:29:36] INFO ARM: skip_transcode: False
[10-06-2024 10:29:36] INFO ARM: mainfeature: False
[10-06-2024 10:29:36] INFO ARM: minlength: 600
[10-06-2024 10:29:36] INFO ARM: maxlength: 99999
[10-06-2024 10:29:36] INFO ARM: videotype: auto
[10-06-2024 10:29:36] INFO ARM: manual_wait: True
[10-06-2024 10:29:36] INFO ARM: manual_wait_time: 60
[10-06-2024 10:29:36] INFO ARM: ripmethod: mkv
[10-06-2024 10:29:36] INFO ARM: mkv_args: 
[10-06-2024 10:29:36] INFO ARM: delrawfiles: True
[10-06-2024 10:29:36] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[10-06-2024 10:29:36] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[10-06-2024 10:29:36] INFO ARM: hb_args_dvd: --subtitle scan -F
[10-06-2024 10:29:36] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[10-06-2024 10:29:36] INFO ARM: raw_path: /home/arm/media/raw/
[10-06-2024 10:29:36] INFO ARM: transcode_path: /home/arm/media/transcode/
[10-06-2024 10:29:36] INFO ARM: completed_path: /home/arm/media/completed/
[10-06-2024 10:29:36] INFO ARM: extras_sub: extras
[10-06-2024 10:29:36] INFO ARM: emby_refresh: False
[10-06-2024 10:29:36] INFO ARM: emby_server: 
[10-06-2024 10:29:36] INFO ARM: emby_port: 8096
[10-06-2024 10:29:36] INFO ARM: notify_rip: True
[10-06-2024 10:29:36] INFO ARM: notify_transcode: True
[10-06-2024 10:29:36] INFO ARM: max_concurrent_transcodes: 0
[10-06-2024 10:29:36] INFO ARM: ******************* End of config parameters *******************
[10-06-2024 10:29:36] INFO ARM: Checking for fstab entry.
[10-06-2024 10:29:36] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[10-06-2024 10:29:36] INFO ARM: Output directory "/home/arm/media/transcode/unidentified/THE-BEST-EXOTIC-MARIGOLD-HOTEL (2012)" already exists.
[10-06-2024 10:29:36] INFO ARM: Final Output directory "/home/arm/media/transcode/unidentified/THE-BEST-EXOTIC-MARIGOLD-HOTEL (2012)_172821050469"
[10-06-2024 10:29:36] INFO ARM: Output directory "/home/arm/media/completed/unidentified/THE-BEST-EXOTIC-MARIGOLD-HOTEL (2012)" already exists.
[10-06-2024 10:29:36] INFO ARM: Final Output directory "/home/arm/media/completed/unidentified/THE-BEST-EXOTIC-MARIGOLD-HOTEL (2012)_172821050469"
[10-06-2024 10:29:36] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/THE-BEST-EXOTIC-MARIGOLD-HOTEL (2012)_172821050469
[10-06-2024 10:29:36] INFO ARM: ************* Ripping disc with MakeMKV *************
[10-06-2024 10:29:36] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-WaI15n3jLrzWU88y7liOljd7UIR0mormcZo2oO5xt_9CSj3Mg6mOxR1eUvU_CA569e
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[10-06-2024 10:29:38] INFO ARM: Starting MakeMKV rip. Method is mkv
[10-06-2024 10:29:38] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[10-06-2024 10:29:38] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[10-06-2024 10:29:38] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 46, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 53, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 213, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[10-06-2024 10:29:38] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

Looks like that's helped shed some light, looks similar to this issue: https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/1195

I'll try running makemkv from within the container as a next step.

**Comment by SunnyMoonSchott** [comment]
Running in the docker container gives me the following:

```
root@be44f92e4928:/home/arm# makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'
makemkvcon: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by makemkvcon)
makemkvcon: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by makemkvcon)
```

So I'm having a go at installing libc6.

**Comment by SunnyMoonSchott** [comment]
<img width="1304" alt="Screenshot 2024-10-06 at 5 55 25 PM" src="https://github.com/user-attachments/assets/095cb7c4-0c85-471f-b93f-6291b1b8a473">

Interestingly my omdb calls are failing with a 401 too, despite me having a valid paid key (double checked it's definitely correct in the ARM settings).

```
[10-06-2024 10:28:28] INFO ARM: Disc identified as video
[10-06-2024 10:28:30] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-06-2024 10:28:31] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
```

**Comment by SunnyMoonSchott** [comment]
```
root@be44f92e4928:/home/arm# apt install glibc-source
Reading package lists... Done
Building dependency tree       
Reading state information... Done
glibc-source is already the newest version (2.31-0ubuntu9.16).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@be44f92e4928:/home/arm# apt install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.31-0ubuntu9.16).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

reinstalling glibc-source and libc6 also haven't helped as they were already up to date.

**Comment by SunnyMoonSchott** [comment]
The other ticket with this issue mentioned `loading the sg module` but I'm not sure how relevant that is to my situation. That and it looks like they also changed the MakeMKV version.

**Comment by microtechno9000** [comment]
Good to see that you have resolved your issue, due to permissions.

Closing this issue as it is now a duplicate of the other MakeMKV issue #1195

**Comment by SunnyMoonSchott** [comment]
Yeah, thanks for your help!
