### ISSUE TITLE
file is missing  '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'.

### ISSUE THREAD

**Issue by Plexen85** [automatic-ripping-machine/automatic-ripping-machine#125]
Every time I extract a dvd I get that the follwoing file is missing  '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'. Music works fine, but not movies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 71, in <module>
    disc_title = clean_for_filename(getbluraytitle())
  File "/opt/arm/getmovietitle.py", line 39, in getbluraytitle
    with open(args.path + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'

**Comment by Plexen85** [comment]
tried a few things going to try re-installing handbreake cli and main application see if that fixes the issue

**Comment by Plexen85** [comment]
Re-install of handbreak cli did not fix the issue 
Install of handbrake full application did not fix the issue

After reinstall of cli Transcoding did work. but still the error message

**Comment by Plexen85** [comment]
Ah I get it now, seems makemkv and handbrake move on and try a different method for disc access. See thread below as to what the file is for

https://forum.videohelp.com/threads/306287-Custom-Blu-ray-meta-data
