### ISSUE TITLE
Emby refresh fails

### ISSUE THREAD

**Issue by muckngrind4** [automatic-ripping-machine/automatic-ripping-machine#242]
Looks like something changed with Emby and the refresh is failing:
```
[2018-08-14 00:02:37] INFO ARM: utils.scan_emby Sending Emby library scan request
[2018-08-14 00:02:37] DEBUG ARM: connectionpool._new_conn Starting new HTTP connection (1): 10.10.10.7
[2018-08-14 00:02:37] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fae8b2c4780>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.10.10.7', port=8096): Max retries exceeded with url: /Library/Refresh?api_key=9d5a2ed295344734bdb663d2d5056e2f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8b2c4780>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 296, in <module>
    main(logfile, disc)
  File "/opt/arm/arm/main.py", line 238, in main
    utils.scan_emby()
  File "/opt/arm/arm/utils.py", line 51, in scan_emby
    req = requests.post(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.10.10.7', port=8096): Max retries exceeded with url: /Library/Refresh?api_key=9d5a2ed295344734bdb663d2d5056e2f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae8b2c4780>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by muckngrind4** [comment]
Looks like an emby upgrade wiped out my api keys.  IjJust needed to regenerate the api key in emby and update the config file and it's working.
