### ISSUE TITLE
Error always on same blu-ray disc

### ISSUE THREAD

**Issue by KeppensJonas** [automatic-ripping-machine/automatic-ripping-machine#257]
### Description
I get always the same error on the same blu-ray disk. All other blu-ray discs are working fine except for one disc

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
* v2_fixes
  v2_master

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
```
TypeError: normalize() argument 2 must be str, not None 
bluray_title = unicodedata.normalize('NFKD', bluray_title).encode('ascii', 'ignore').decode() 
File "/opt/arm/arm/getmovietitle.py", line 75, in getbluraytitle 
disc_title, disc_year = getbluraytitle(disc) 
File "/opt/arm/arm/getmovietitle.py", line 111, in main 
disc.videotitle, disc.videoyear = getmovietitle.main(disc) 
File "/opt/arm/arm/identify.py", line 58, in identify 
identify.identify(disc, logfile) 
File "/opt/arm/arm/main.py", line 87, in main 
main(logfile, disc) 
File "/opt/arm/arm/main.py", line 296, in 
Traceback (most recent call last): 

During handling of the above exception, another exception occurred: 

pydvdid.exceptions.PathDoesNotExistException: Path '/mnt/dev/sr0/VIDEO_TS' does not exist. 
raise PathDoesNotExistException(video_ts_folder_path) 
File "/usr/local/lib/python3.6/dist-packages/pydvdid/functions.py", line 59, in _check_video_ts_path_exists 
_check_video_ts_path_exists(dvd_path) 
File "/usr/local/lib/python3.6/dist-packages/pydvdid/functions.py", line 26, in compute 
crc64 = pydvdid.compute(str(disc.mountpoint)) 
File "/opt/arm/arm/getmovietitle.py", line 30, in getdvdtitle 
disc_title, disc_year = getdvdtitle(disc) 
File "/opt/arm/arm/getmovietitle.py", line 102, in main 
Traceback (most recent call last): 
[2018-10-15 12:30:04] ERROR ARM: main. A fatal error has occured and ARM is exiting. See traceback below for details. 
[2018-10-15 12:30:04] DEBUG ARM: getmovietitle.getdvdtitle Disc: (devpath=/dev/sr0) (mountpoint=/mnt/dev/sr0) (videotitle=) (videoyear=) (videotype=) (hasnicetitle=False) (label=NANNY_BIG_BANG_G51) (disctype=bluray) (ejected=False) (errors=[]) 
[2018-10-15 12:30:04] INFO ARM: identify.identify Getting movie title... 
[2018-10-15 12:30:04] INFO ARM: identify.identify Disc identified as video 
[2018-10-15 12:30:04] DEBUG ARM: identify.identify Found: /mnt/dev/sr0/BDMV 
[2018-10-15 12:30:03] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr0 
[2018-10-15 12:30:03] DEBUG ARM: identify.identify Identification starting: Disc: (devpath=/dev/sr0) (mountpoint=/mnt/dev/sr0) (videotitle=) (videoyear=) (videotype=) (hasnicetitle=False) (label=NANNY_BIG_BANG_G51) (disctype=bluray) (ejected=False) (errors=[]) 
[2018-10-15 12:30:03] INFO ARM: main.main Starting Disc identification 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params **** End udev attributes **** 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:144320544143 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params TAGS::uaccess:seat:systemd: 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params SYSTEMD_MOUNT_DEVICE_BOUND:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params SUBSYSTEM:block 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params MINOR:0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params MAJOR:11 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_VENDOR_ID:13fd 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_VENDOR_ENC:ASUS\x20\x20\x20\x20 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_VENDOR:ASUS 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_USB_INTERFACE_NUM:00 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_USB_INTERFACES::080650: 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_USB_DRIVER:usb-storage 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_TYPE:cd 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_SERIAL_SHORT:3248433031354B4A30303030 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_SERIAL:ASUS_SBC-06D2X-U_3248433031354B4A30303030-0:0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_REVISION:1.03 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_PATH_TAG:pci-0000_00_14_0-usb-0_8_1_0-scsi-0_0_0_0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_PATH:pci-0000:00:14.0-usb-0:8:1.0-scsi-0:0:0:0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_MODEL_ID:0940 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_MODEL_ENC:SBC-06D2X-U\x20\x20\x20\x20\x20 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_MODEL:SBC-06D2X-U 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_INSTANCE:0:0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_VERSION:2.80 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_UUID_ENC:8ccd20cfaa3b8618 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_UUID:8ccd20cfaa3b8618 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_USAGE:filesystem 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_TYPE:udf 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_LABEL_ENC:NANNY_BIG_BANG_G51 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FS_LABEL:NANNY_BIG_BANG_G51 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_FOR_SEAT:block-pci-0000_00_14_0-usb-0_8_1_0-scsi-0_0_0_0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MRW_W:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MRW:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT_DATA:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_STATE:complete 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_SESSION_COUNT:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_BD:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RW:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RAM:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_R:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R_DL:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_RW:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_DVD:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_CD_RW:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_CD_R:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_CD:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM_BD:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_CDROM:1 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params ID_BUS:usb 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params DEVTYPE:disk 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8:1.0/host6/target6:0:0/6:0:0:0/block/sr0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr0 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params DEVLINKS:/dev/cdrw /dev/disk/by-path/pci-0000:00:14.0-usb-0:8:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-ASUS_SBC-06D2X-U_3248433031354B4A30303030-0:0 /dev/disk/by-uuid/8ccd20cfaa3b8618 /dev/dvd /dev/cdrom /dev/disk/by-label/NANNY_BIG_BANG_G51 /dev/dvdrw 
[2018-10-15 12:30:03] DEBUG ARM: main.log_udev_params **** Logging udev attributes **** 
[2018-10-15 12:30:03] INFO ARM: logger.cleanuplogs Looking for log files older than 1 days old. 
[2018-10-15 12:30:03] INFO ARM: main. Python version: 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
[2018-10-15 12:30:03] INFO ARM: main. ARM version: 2.0.1-stable 
[2018-10-15 12:30:03] INFO ARM: main. Starting ARM processing at 2018-10-15 12:30:03.968483 

```

**Comment by xFusionLordx** [comment]
Seems to still be an issue in 2.6.18.
Attempting to rip: Fast & Furious (fourth entry in the series)

[FAST_AND_FURIOUS.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/11073658/FAST_AND_FURIOUS.log)
