### ISSUE TITLE
move_files fails

### ISSUE THREAD

**Issue by mccorvie** [automatic-ripping-machine/automatic-ripping-machine#298]
### Description
Final copy of finished files fails for Blu-ray disks owing to API mismatch

### Environment
Ubuntu 18.04
v2.1_dev

### Log file
[2019-07-11 19:35:21] ERROR ARM: A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 416, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 207, in main
    utils.move_files(hbinpath, f, job.hasnicetitle, job, True)
TypeError: move_files() takes from 3 to 4 positional arguments but 5 were given

**Comment by SirLeto** [comment]
I seem to have this error every time I rip but still end up with working files.
