### ISSUE TITLE
http permission error while changing the title from the runui.py interface

### ISSUE THREAD

**Issue by jeffeb3** [automatic-ripping-machine/automatic-ripping-machine#302]
### Description
Since the MS movie db is dead I switched to v2_dev. I think I figured out how to edit the titles of movies if they aren't available by running the runui.py and navigating to the website and clicking around. When I do, I get this error when hitting the submit button (in the log file).

The runui was ran by the arm user, and the arm user has permissions for the db folder and file. The arm rips are working fine.

### Environment
Ubuntu 18.04.
```
git log -n 1
commit 39b550237cbfd9a3f62ce5d7b41689b009416868 (HEAD -> v2.1_dev, origin/v2.1_dev)
Author: Derek Christensen <22111345+muckngrind4@users.noreply.github.com>
Date:   Sat Jul 6 00:46:38 2019 -0700

    Handle MakeMKV error code 253 "Version out of date"
```

### Log file
```
10.0.2.128 - - [29/Jul/2019 13:40:21] "GET /list_titles?title=Shawshank_Redemption&year=1994&job_id=3 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arm/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arm/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arm/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/arm/arm/ui/routes.py", line 104, in list_titles
    dvd_info = call_omdb_api(title, year)
  File "/opt/arm/arm/ui/utils.py", line 61, in call_omdb_api
    title_info_json = urllib.request.urlopen(strurl).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by jeffeb3** [comment]
Aha. I didn't have an omdb api set. I set that and restarted the runui and now it's working. I'll leave it to you to close this if you want.
