### ISSUE TITLE
ARM Fails at getvideotype with JSONDecodeError

### ISSUE THREAD

**Issue by mooscomputer** [automatic-ripping-machine/automatic-ripping-machine#305]
### Description
Unable to get any DVD to rip.  Tried manually setting videotype to series and movie.  Same error on Ubuntu 18 and 16 LTS

### Environment
jason@ARM:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

MasterV2

### Log file
[2019-08-17 07:30:40] INFO ARM: main.<module> Starting ARM processing at 2019-08-17 07:30:40.353743
[2019-08-17 07:30:40] INFO ARM: main.<module> ARM version: 2.0.1-stable
[2019-08-17 07:30:40] INFO ARM: main.<module> Python version: 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
[2019-08-17 07:30:40] INFO ARM: logger.cleanuplogs Looking for log files older than 1 days old.
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params **** Logging udev attributes ****
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params DEVLINKS:/dev/cdrom /dev/disk/by-path/pci-0000:00:09.0-ata-2 /dev/disk/by-id/ata-ATAPI_DVD_A_DH16AAL_3A9941009856 /dev/dvd /dev/dvdrw /dev/cdrw
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr0
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:09.0/ata2/host1/target1:0:0/1:0:0:0/block/sr0
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params DEVTYPE:disk
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_ATA:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_ATA_SATA:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_ATA_SATA_SIGNAL_RATE_GEN1:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_BUS:ata
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_CD:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_CD_R:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_CD_RW:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_RW:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R_DL:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_R:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RAM:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RW:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_MRW:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_CDROM_MRW_W:1
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_FOR_SEAT:block-pci-0000_00_09_0-ata-2
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_MODEL:ATAPI_DVD_A_DH16AAL
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_MODEL_ENC:ATAPI\x20\x20\x20DVD\x20A\x20\x20DH16AAL\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_PATH:pci-0000:00:09.0-ata-2
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_PATH_TAG:pci-0000_00_09_0-ata-2
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_REVISION:LHD3
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_SERIAL:ATAPI_DVD_A_DH16AAL_3A9941009856
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_SERIAL_SHORT:3A9941009856
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params ID_TYPE:cd
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params MAJOR:11
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params MINOR:0
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params SUBSYSTEM:block
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params TAGS::uaccess:systemd:seat:
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:4703571
[2019-08-17 07:30:40] DEBUG ARM: main.log_udev_params **** End udev attributes ****
[2019-08-17 07:30:40] INFO ARM: main.main Starting Disc identification
[2019-08-17 07:30:40] DEBUG ARM: identify.identify Identification starting: Disc: (ejected=False) (videotype=) (errors=[]) (videotitle=) (devpath=/dev/sr1) (disctype=dvd) (label=FMP_FUMOFFU_D1) (hasnicetitle=False) (mountpoint=/mnt/dev/sr1) (videoyear=)
[2019-08-17 07:30:40] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr1
[2019-08-17 07:30:44] DEBUG ARM: identify.identify Found: /mnt/dev/sr1/VIDEO_TS
[2019-08-17 07:30:44] INFO ARM: identify.identify Disc identified as video
[2019-08-17 07:30:44] INFO ARM: identify.identify Getting movie title...
[2019-08-17 07:30:44] DEBUG ARM: getmovietitle.getdvdtitle Disc: (ejected=False) (videotype=) (errors=[]) (videotitle=) (devpath=/dev/sr1) (disctype=dvd) (label=FMP_FUMOFFU_D1) (hasnicetitle=False) (mountpoint=/mnt/dev/sr1) (videoyear=)
[2019-08-17 07:30:44] INFO ARM: getmovietitle.getdvdtitle DVD CRC64 hash is: 63f39d949d32aae1
[2019-08-17 07:30:44] DEBUG ARM: getmovietitle.getdvdtitle http://metaservices.windowsmedia.com/pas_dvd_B/template/GetMDRDVDByCRC.xml?CRC=63f39d949d32aae1
[2019-08-17 07:30:44] ERROR ARM: getmovietitle.getdvdtitle Failed to reach windowsmedia web service
[2019-08-17 07:30:44] WARNING ARM: getmovietitle.main DVD title not found
[2019-08-17 07:30:44] INFO ARM: getmovietitle.main FMP_FUMOFFU_D1 : 0000
[2019-08-17 07:30:44] INFO ARM: getmovietitle.main Returning: FMP_FUMOFFU_D1, 0000
[2019-08-17 07:30:44] INFO ARM: identify.identify Getting video type...
[2019-08-17 07:30:44] DEBUG ARM: getvideotype.main Entering getvideotype module
[2019-08-17 07:30:44] DEBUG ARM: getvideotype.getdvdtype Title: FMP_FUMOFFU_D1 | Year: 0000
[2019-08-17 07:30:44] DEBUG ARM: getvideotype.getdvdtype Calling webservice with title: FMP+FUMOFFU+D1 and year: 0000
[2019-08-17 07:30:44] DEBUG ARM: getvideotype.callwebservice ***Calling webservice with Title: FMP+FUMOFFU+D1 and Year: 0000
[2019-08-17 07:30:44] DEBUG ARM: getvideotype.callwebservice http://www.omdbapi.com/?t=FMP+FUMOFFU+D1&y=0000&plot=short&r=json&apikey=key_hidden
[2019-08-17 07:30:44] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 296, in <module>
    main(logfile, disc)
  File "/opt/arm/arm/main.py", line 87, in main
    identify.identify(disc, logfile)
  File "/opt/arm/arm/identify.py", line 62, in identify
    disc.videotype, disc.videoyear = getvideotype.main(disc)
  File "/opt/arm/arm/getvideotype.py", line 116, in main
    dvd_type, year = getdvdtype(disc)
  File "/opt/arm/arm/getvideotype.py", line 41, in getdvdtype
    dvd_type = callwebservice(omdb_api_key, dvd_title_clean, year)
  File "/opt/arm/arm/getvideotype.py", line 102, in callwebservice
    doc = json.loads(dvd_title_info_json.decode())
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 2e0byo** [comment]
AFAIK microsoft discontinued the service this depended on earlier this year.

https://support.microsoft.com/en-hk/help/4488539/changes-metadata-services-windows-media-center-media-player

This ARM currently doesn't work.
