### ISSUE TITLE
ImportError: cannot import name 'cached_property'

### ISSUE THREAD

**Issue by sjbrownie** [automatic-ripping-machine/automatic-ripping-machine#327]
### Description
Cannot run the script.  Fails with the following error

sbrown@Plex3:/home/arm$ sudo /usr/bin/python3 /opt/arm/arm/main.py -d sr0
Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 19, in <module>
    from getkeys import grabkeys
  File "/opt/arm/arm/getkeys.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'

### Environment
Ubuntu 18.04
V2_master

### Log file
brown@Plex3:/home/arm$ sudo /usr/bin/python3 /opt/arm/arm/main.py -d sr0
Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 19, in <module>
    from getkeys import grabkeys
  File "/opt/arm/arm/getkeys.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'

**Comment by sjbrownie** [comment]
I found a workaround for this. 

Werkzeug has been changed the line in robobrowser/browser.py ln 8 SHOULD READ

from werkzeug.utils import cached_property

**Comment by jsl4980** [comment]
You can also specify an older version of werkzeug in the requirements.txt file by adding the line:
Werkzeug==0.16.1
