### ISSUE TITLE
No logs,  UDEV rules help needed?

### ISSUE THREAD

**Issue by jeremytourville** [automatic-ripping-machine/automatic-ripping-machine#328]
### Description
Question - Troubleshooting
I think I need help with udev rules as the burn process doesn't seem to be starting.  If it does start, it errors out.  Please see attached logs from /var/log/syslog.  I systematically tried one option at a time with varying results.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]

```
user@arm:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
```
user@arm:/opt/arm$ git branch

* v2_master
user@arm:/opt/arm$ git log -l
fatal: Option 'l' requires a value
user@arm:/opt/arm$ git log -1
commit 3f40908a32c265d548857cc7d9eb4f0d72f2099b (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 1ed41eb b64bbf0
Author: Derek <22111345+muckngrind4@users.noreply.github.com>
Date:   Mon Aug 13 23:54:26 2018 -0700

    Merge pull request #241 from automatic-ripping-machine/v2_fixes

    Added -l option to su in arm_wrapper.  Fixes #237
```

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
There is no log even though /opt/arm/arm.yaml defines this-

```
# Path to directory to hold log files
# Make sure to include trailing /
LOGPATH: "/home/arm/logs/"

# Log level.  DEBUG, INFO, WARNING, ERROR, CRITICAL
# The default is INFO
LOGLEVEL: "DEBUG"

# How long to let log files live before deleting (in days)
LOGLIFE: 1
```

Try 1
 ```
$sudo nano /opt/arm/setup/51-automedia.rules
# ID_CDROM_MEDIA_BD = Bluray
ID_CDROM_MEDIA_DVD = DVD
# ID_CDROM_MEDIA_CD = CD
ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm_wrapper.sh"
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm/main.py -l '%E{ID_FS_LABEL}' -d '%E{DEVNAME}'"
# ACTION=="change", SUBSYSTEM=="block", TAG+="systemd", KERNEL=="sr[0-9]*|vdisk*|xvd*", ENV{DEVTYPE}=="disk", RUN+="/bin/systemctl start arm@%k.service"
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/scripts/arm_wrapper.sh %k"
```

```
$sudo tail -f /var/log/syslog
Mar  9 20:16:26 arm systemd[709]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:16:26 arm systemd[709]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:16:26 arm systemd[709]: Reached target Sockets.
Mar  9 20:16:26 arm systemd[709]: Reached target Basic System.
Mar  9 20:16:26 arm systemd[709]: Reached target Default.
Mar  9 20:16:26 arm systemd[709]: Startup finished in 247ms.
Mar  9 20:16:26 arm systemd[1]: Started User Manager for UID 1000.
Mar  9 20:16:44 arm systemd[1]: Starting Stop ureadahead data collection...
Mar  9 20:16:44 arm systemd[1]: Started Stop ureadahead data collection.
Mar  9 20:17:01 arm CRON[759]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```
***<insert disc>***
```
Mar  9 20:19:38 arm kernel: [  239.766634] sr 3:0:0:0: [sr0] tag#30 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:19:38 arm kernel: [  239.766637] sr 3:0:0:0: [sr0] tag#30 Sense Key : Illegal Request [current]
Mar  9 20:19:38 arm kernel: [  239.766640] sr 3:0:0:0: [sr0] tag#30 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:19:38 arm kernel: [  239.766643] sr 3:0:0:0: [sr0] tag#30 CDB: Read(10) 28 00 00 27 31 00 00 00 40 00
Mar  9 20:19:38 arm kernel: [  239.766646] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:19:38 arm kernel: [  239.826629] sr 3:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:19:38 arm kernel: [  239.826632] sr 3:0:0:0: [sr0] tag#0 Sense Key : Illegal Request [current]
Mar  9 20:19:38 arm kernel: [  239.826634] sr 3:0:0:0: [sr0] tag#0 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:19:38 arm kernel: [  239.826637] sr 3:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 27 31 00 00 00 01 00
Mar  9 20:19:38 arm kernel: [  239.826639] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:19:38 arm kernel: [  239.826676] Buffer I/O error on dev sr0, logical block 2568448, async page read
Mar  9 20:19:38 arm [775]: failed to execute '/opt/arm/arm_wrapper.sh' '/opt/arm/arm_wrapper.sh': No such file or directory
Mar  9 20:19:38 arm systemd-udevd[763]: Process '/opt/arm/arm_wrapper.sh' failed with exit code 2.
```
***<remove disc>***
```
Mar  9 20:20:49 arm (spawn)[780]: failed to execute '/opt/arm/arm_wrapper.sh' '/opt/arm/arm_wrapper.sh': No such file or directory
Mar  9 20:20:49 arm systemd-udevd[778]: Process '/opt/arm/arm_wrapper.sh' failed with exit code 2.
Mar  9 20:20:52 arm [794]: failed to execute '/opt/arm/arm_wrapper.sh' '/opt/arm/arm_wrapper.sh': No such file or directory
Mar  9 20:20:52 arm systemd-udevd[782]: Process '/opt/arm/arm_wrapper.sh' failed with exit code 2.
```
/home/arm/logs/ is empty

Try 2
```
$sudo nano /opt/arm/setup/51-automedia.rules
# ID_CDROM_MEDIA_BD = Bluray
ID_CDROM_MEDIA_DVD = DVD
# ID_CDROM_MEDIA_CD = CD
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm_wrapper.sh"
ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm/main.py -l '%E{ID_FS_LABEL}' -d '%E{DEVNAME}'"
# ACTION=="change", SUBSYSTEM=="block", TAG+="systemd", KERNEL=="sr[0-9]*|vdisk*|xvd*", ENV{DEVTYPE}=="disk", RUN+="/bin/systemctl start arm@%k.service"
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/scripts/arm_wrapper.sh %k"
```

```
$sudo tail -f /var/log/syslog
Mar  9 20:24:22 arm systemd[685]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:24:22 arm systemd[685]: Listening on GnuPG network certificate management daemon.
Mar  9 20:24:22 arm systemd[685]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:24:22 arm systemd[685]: Reached target Sockets.
Mar  9 20:24:22 arm systemd[685]: Reached target Basic System.
Mar  9 20:24:22 arm systemd[685]: Reached target Default.
Mar  9 20:24:22 arm systemd[685]: Startup finished in 249ms.
Mar  9 20:24:22 arm systemd[1]: Started User Manager for UID 1000.
Mar  9 20:24:56 arm systemd[1]: Starting Stop ureadahead data collection...
Mar  9 20:24:56 arm systemd[1]: Started Stop ureadahead data collection.
```
***<insert disc>***
```
Mar  9 20:27:40 arm kernel: [  231.523587] sr 3:0:0:0: [sr0] tag#26 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:27:40 arm kernel: [  231.523590] sr 3:0:0:0: [sr0] tag#26 Sense Key : Illegal Request [current]
Mar  9 20:27:40 arm kernel: [  231.523594] sr 3:0:0:0: [sr0] tag#26 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:27:40 arm kernel: [  231.523598] sr 3:0:0:0: [sr0] tag#26 CDB: Read(10) 28 00 00 27 31 00 00 00 40 00
Mar  9 20:27:40 arm kernel: [  231.523600] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:27:40 arm kernel: [  231.583554] sr 3:0:0:0: [sr0] tag#27 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:27:40 arm kernel: [  231.583557] sr 3:0:0:0: [sr0] tag#27 Sense Key : Illegal Request [current]
Mar  9 20:27:40 arm kernel: [  231.583560] sr 3:0:0:0: [sr0] tag#27 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:27:40 arm kernel: [  231.583563] sr 3:0:0:0: [sr0] tag#27 CDB: Read(10) 28 00 00 27 31 00 00 00 01 00
Mar  9 20:27:40 arm kernel: [  231.583564] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:27:40 arm kernel: [  231.583600] Buffer I/O error on dev sr0, logical block 2568448, async page read
Mar  9 20:27:42 arm systemd-udevd[739]: Process '/opt/arm/arm/main.py -l 'BILL_AND_TEDS_EXCELLENT_ADVEN' -d '/dev/sr0'' failed with exit code 1.```](url)
```

***<remove disc>***

```
Mar  9 20:28:41 arm systemd-udevd[755]: Process '/opt/arm/arm/main.py -l '' -d '/dev/sr0'' failed with exit code 1.
Mar  9 20:28:46 arm systemd-udevd[762]: Process '/opt/arm/arm/main.py -l '' -d '/dev/sr0'' failed with exit code 1.
```

/home/arm/logs/ is empty

Try 3

```
$sudo nano /opt/arm/setup/51-automedia.rules
# ID_CDROM_MEDIA_BD = Bluray
ID_CDROM_MEDIA_DVD = DVD
# ID_CDROM_MEDIA_CD = CD
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm_wrapper.sh"
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm/main.py -l '%E{ID_FS_LABEL}' -d '%E{DEVNAME}'"
ACTION=="change", SUBSYSTEM=="block", TAG+="systemd", KERNEL=="sr[0-9]*|vdisk*|xvd*", ENV{DEVTYPE}=="disk", RUN+="/bin/systemctl start arm@%k.service"
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/scripts/arm_wrapper.sh %k"
```

```
$sudo tail -f /var/log/syslog
Mar  9 20:34:59 arm systemd[675]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:34:59 arm systemd[675]: Reached target Paths.
Mar  9 20:34:59 arm systemd[675]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:34:59 arm systemd[675]: Reached target Sockets.
Mar  9 20:34:59 arm systemd[675]: Reached target Basic System.
Mar  9 20:34:59 arm systemd[675]: Reached target Default.
Mar  9 20:34:59 arm systemd[675]: Startup finished in 247ms.
Mar  9 20:34:59 arm systemd[1]: Started User Manager for UID 1000.
Mar  9 20:35:08 arm systemd[1]: Starting Stop ureadahead data collection...
Mar  9 20:35:08 arm systemd[1]: Started Stop ureadahead data collection.
```
***<insert disc>***
```
Mar  9 20:36:56 arm kernel: [  174.737589] sr 3:0:0:0: [sr0] tag#28 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:36:56 arm kernel: [  174.737592] sr 3:0:0:0: [sr0] tag#28 Sense Key : Illegal Request [current]
Mar  9 20:36:56 arm kernel: [  174.737595] sr 3:0:0:0: [sr0] tag#28 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:36:56 arm kernel: [  174.737599] sr 3:0:0:0: [sr0] tag#28 CDB: Read(10) 28 00 00 27 31 00 00 00 40 00
Mar  9 20:36:56 arm kernel: [  174.737601] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:36:56 arm kernel: [  174.805601] sr 3:0:0:0: [sr0] tag#29 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:36:56 arm kernel: [  174.805604] sr 3:0:0:0: [sr0] tag#29 Sense Key : Illegal Request [current]
Mar  9 20:36:56 arm kernel: [  174.805607] sr 3:0:0:0: [sr0] tag#29 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:36:56 arm kernel: [  174.805611] sr 3:0:0:0: [sr0] tag#29 CDB: Read(10) 28 00 00 27 31 00 00 00 01 00
Mar  9 20:36:56 arm kernel: [  174.805613] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:36:56 arm kernel: [  174.805654] Buffer I/O error on dev sr0, logical block 2568448, async page read
Mar  9 20:36:56 arm systemd-udevd[724]: Process '/bin/systemctl start arm@sr0.service' failed with exit code 5.
```
***<remove disc>***
```
Mar  9 20:37:53 arm systemd-udevd[739]: Process '/bin/systemctl start arm@sr0.service' failed with exit code 5.
Mar  9 20:37:56 arm systemd-udevd[743]: Process '/bin/systemctl start arm@sr0.service' failed with exit code 5.
```
/home/arm/logs/ is empty

Try 4

```
$sudo nano /opt/arm/setup/51-automedia.rules
# ID_CDROM_MEDIA_BD = Bluray
ID_CDROM_MEDIA_DVD = DVD
# ID_CDROM_MEDIA_CD = CD
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm_wrapper.sh"
# ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/arm/main.py -l '%E{ID_FS_LABEL}' -d '%E{DEVNAME}'"
# ACTION=="change", SUBSYSTEM=="block", TAG+="systemd", KERNEL=="sr[0-9]*|vdisk*|xvd*", ENV{DEVTYPE}=="disk", RUN+="/bin/systemctl start arm@%k.service"
ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/scripts/arm_wrapper.sh %k"
```

```
$sudo tail -f /var/log/syslog
Mar  9 20:08:49 arm systemd[758]: Reached target Timers.
Mar  9 20:08:49 arm systemd[758]: Listening on GnuPG cryptographic agent and passphrase cache.
Mar  9 20:08:49 arm systemd[758]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:08:49 arm systemd[758]: Reached target Sockets.
Mar  9 20:08:49 arm systemd[758]: Reached target Basic System.
Mar  9 20:08:49 arm systemd[758]: Reached target Default.
Mar  9 20:08:49 arm systemd[758]: Startup finished in 248ms.
Mar  9 20:08:49 arm systemd[1]: Started User Manager for UID 1000.
Mar  9 20:09:13 arm systemd[1]: Starting Stop ureadahead data collection...
Mar  9 20:09:13 arm systemd[1]: Started Stop ureadahead data collection.
```
***<insert disc>***
```
Mar  9 20:09:47 arm kernel: [   99.934641] sr 3:0:0:0: [sr0] tag#24 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:09:47 arm kernel: [   99.934644] sr 3:0:0:0: [sr0] tag#24 Sense Key : Illegal Request [current]
Mar  9 20:09:47 arm kernel: [   99.934647] sr 3:0:0:0: [sr0] tag#24 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:09:47 arm kernel: [   99.934650] sr 3:0:0:0: [sr0] tag#24 CDB: Read(10) 28 00 00 27 31 00 00 00 40 00
Mar  9 20:09:47 arm kernel: [   99.934652] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:09:47 arm kernel: [   99.994676] sr 3:0:0:0: [sr0] tag#25 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar  9 20:09:47 arm kernel: [   99.994679] sr 3:0:0:0: [sr0] tag#25 Sense Key : Illegal Request [current]
Mar  9 20:09:47 arm kernel: [   99.994682] sr 3:0:0:0: [sr0] tag#25 Add. Sense: Read of scrambled sector without authentication
Mar  9 20:09:47 arm kernel: [   99.994685] sr 3:0:0:0: [sr0] tag#25 CDB: Read(10) 28 00 00 27 31 00 00 00 01 00
Mar  9 20:09:47 arm kernel: [   99.994687] print_req_error: I/O error, dev sr0, sector 10273792
Mar  9 20:09:47 arm kernel: [   99.994729] Buffer I/O error on dev sr0, logical block 2568448, async page read
Mar  9 20:09:47 arm ARM: Starting ARM on sr0
Mar  9 20:09:47 arm systemd[1]: Created slice User Slice of arm.
Mar  9 20:09:47 arm systemd[1]: Starting User Manager for UID 1001...
Mar  9 20:09:47 arm systemd[1]: Started Session c1 of user arm.
Mar  9 20:09:47 arm systemd[827]: Reached target Timers.
Mar  9 20:09:48 arm systemd[827]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:09:48 arm systemd[827]: Reached target Paths.
Mar  9 20:09:48 arm systemd[827]: Listening on GnuPG network certificate management daemon.
Mar  9 20:09:48 arm systemd[827]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:09:48 arm systemd[827]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:09:48 arm systemd[827]: Listening on GnuPG cryptographic agent and passphrase cache.
Mar  9 20:09:48 arm systemd[827]: Reached target Sockets.
Mar  9 20:09:48 arm systemd[827]: Reached target Basic System.
Mar  9 20:09:48 arm systemd[827]: Reached target Default.
Mar  9 20:09:48 arm systemd[827]: Startup finished in 55ms.
Mar  9 20:09:48 arm systemd[1]: Started User Manager for UID 1001.
Mar  9 20:09:48 arm systemd[1]: Stopping User Manager for UID 1001...
Mar  9 20:09:48 arm systemd[827]: Stopped target Default.
Mar  9 20:09:48 arm systemd[827]: Stopped target Basic System.
Mar  9 20:09:48 arm systemd[827]: Stopped target Sockets.
Mar  9 20:09:48 arm systemd[827]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:09:48 arm systemd[827]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:09:48 arm systemd[827]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:09:48 arm systemd[827]: Closed GnuPG cryptographic agent and passphrase cache.
Mar  9 20:09:48 arm systemd[827]: Stopped target Timers.
Mar  9 20:09:48 arm systemd[827]: Stopped target Paths.
Mar  9 20:09:48 arm systemd[827]: Closed GnuPG network certificate management daemon.
Mar  9 20:09:48 arm systemd[827]: Reached target Shutdown.
Mar  9 20:09:48 arm systemd[827]: Starting Exit the Session...
Mar  9 20:09:48 arm systemd[827]: Received SIGRTMIN+24 from PID 844 (kill).
Mar  9 20:09:48 arm systemd[1]: Stopped User Manager for UID 1001.
Mar  9 20:09:48 arm systemd[1]: Removed slice User Slice of arm.
Mar  9 20:09:50 arm postfix/pickup[723]: 5F3D16A078D: uid=1001 from=<arm>
Mar  9 20:09:50 arm postfix/cleanup[851]: 5F3D16A078D: message-id=<20200310010950.5F3D16A078D@arm.lan>
Mar  9 20:09:50 arm postfix/qmgr[724]: 5F3D16A078D: from=<arm@arm.lan>, size=816, nrcpt=1 (queue active)
Mar  9 20:09:50 arm postfix/local[853]: 5F3D16A078D: to=<arm@arm.lan>, orig_to=<arm>, relay=local, delay=0.37, delays=0.19/0.11/0/0.06, dsn=2.0.0, status=sent (delivered to mailbox)
Mar  9 20:09:50 arm postfix/qmgr[724]: 5F3D16A078D: removed
```
***<remove disc>***
```
Mar  9 20:11:42 arm ARM: Starting ARM on sr0
Mar  9 20:11:42 arm systemd[1]: Created slice User Slice of arm.
Mar  9 20:11:42 arm systemd[1]: Starting User Manager for UID 1001...
Mar  9 20:11:42 arm systemd[1]: Started Session c2 of user arm.
Mar  9 20:11:42 arm systemd[860]: Reached target Timers.
Mar  9 20:11:42 arm systemd[860]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:11:42 arm systemd[860]: Listening on GnuPG network certificate management daemon.
Mar  9 20:11:42 arm systemd[860]: Listening on GnuPG cryptographic agent and passphrase cache.
Mar  9 20:11:42 arm systemd[860]: Reached target Paths.
Mar  9 20:11:42 arm systemd[860]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:11:42 arm systemd[860]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:11:42 arm systemd[860]: Reached target Sockets.
Mar  9 20:11:42 arm systemd[860]: Reached target Basic System.
Mar  9 20:11:42 arm systemd[860]: Reached target Default.
Mar  9 20:11:42 arm systemd[1]: Started User Manager for UID 1001.
Mar  9 20:11:42 arm systemd[860]: Startup finished in 33ms.
Mar  9 20:11:42 arm systemd[1]: Stopping User Manager for UID 1001...
Mar  9 20:11:42 arm systemd[860]: Stopped target Default.
Mar  9 20:11:42 arm systemd[860]: Stopped target Basic System.
Mar  9 20:11:42 arm systemd[860]: Stopped target Timers.
Mar  9 20:11:42 arm systemd[860]: Stopped target Paths.
Mar  9 20:11:42 arm systemd[860]: Stopped target Sockets.
Mar  9 20:11:42 arm systemd[860]: Closed GnuPG network certificate management daemon.
Mar  9 20:11:42 arm systemd[860]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:11:42 arm systemd[860]: Closed GnuPG cryptographic agent and passphrase cache.
Mar  9 20:11:42 arm systemd[860]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:11:42 arm systemd[860]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:11:42 arm systemd[860]: Reached target Shutdown.
Mar  9 20:11:42 arm systemd[860]: Starting Exit the Session...
Mar  9 20:11:42 arm systemd[860]: Received SIGRTMIN+24 from PID 880 (kill).
Mar  9 20:11:42 arm systemd[1]: Stopped User Manager for UID 1001.
Mar  9 20:11:42 arm systemd[1]: Removed slice User Slice of arm.
Mar  9 20:11:43 arm postfix/pickup[723]: 693876A078D: uid=1001 from=<arm>
Mar  9 20:11:43 arm postfix/cleanup[885]: 693876A078D: message-id=<20200310011143.693876A078D@arm.lan>
Mar  9 20:11:43 arm postfix/qmgr[724]: 693876A078D: from=<arm@arm.lan>, size=816, nrcpt=1 (queue active)
Mar  9 20:11:43 arm postfix/local[887]: 693876A078D: to=<arm@arm.lan>, orig_to=<arm>, relay=local, delay=0.12, delays=0.09/0.01/0/0.03, dsn=2.0.0, status=sent (delivered to mailbox)
Mar  9 20:11:43 arm postfix/qmgr[724]: 693876A078D: removed
Mar  9 20:11:46 arm ARM: Starting ARM on sr0
Mar  9 20:11:46 arm systemd[1]: Created slice User Slice of arm.
Mar  9 20:11:46 arm systemd[1]: Started Session c3 of user arm.
Mar  9 20:11:46 arm systemd[1]: Starting User Manager for UID 1001...
Mar  9 20:11:46 arm systemd[904]: Reached target Paths.
Mar  9 20:11:46 arm systemd[904]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:11:46 arm systemd[904]: Reached target Timers.
Mar  9 20:11:46 arm systemd[904]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:11:46 arm systemd[904]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:11:46 arm systemd[904]: Listening on GnuPG cryptographic agent and passphrase cache.
Mar  9 20:11:46 arm systemd[904]: Listening on GnuPG network certificate management daemon.
Mar  9 20:11:46 arm systemd[904]: Reached target Sockets.
Mar  9 20:11:46 arm systemd[904]: Reached target Basic System.
Mar  9 20:11:46 arm systemd[904]: Reached target Default.
Mar  9 20:11:46 arm systemd[904]: Startup finished in 33ms.
Mar  9 20:11:46 arm systemd[1]: Started User Manager for UID 1001.
Mar  9 20:11:46 arm systemd[1]: Stopping User Manager for UID 1001...
Mar  9 20:11:46 arm systemd[904]: Stopped target Default.
Mar  9 20:11:46 arm systemd[904]: Stopped target Basic System.
Mar  9 20:11:46 arm systemd[904]: Stopped target Timers.
Mar  9 20:11:46 arm systemd[904]: Stopped target Sockets.
Mar  9 20:11:46 arm systemd[904]: Closed GnuPG cryptographic agent and passphrase cache.
Mar  9 20:11:46 arm systemd[904]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  9 20:11:46 arm systemd[904]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Mar  9 20:11:46 arm systemd[904]: Closed GnuPG network certificate management daemon.
Mar  9 20:11:46 arm systemd[904]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Mar  9 20:11:46 arm systemd[904]: Stopped target Paths.
Mar  9 20:11:46 arm systemd[904]: Reached target Shutdown.
Mar  9 20:11:46 arm systemd[904]: Starting Exit the Session...
Mar  9 20:11:46 arm systemd[904]: Started Exit the Session.
Mar  9 20:11:46 arm systemd[904]: Received SIGRTMIN+24 from PID 923 (n/a).
Mar  9 20:11:46 arm systemd[1]: Stopped User Manager for UID 1001.
Mar  9 20:11:46 arm systemd[1]: Removed slice User Slice of arm.
Mar  9 20:11:47 arm postfix/pickup[723]: 2D95E6A0790: uid=1001 from=<arm>
Mar  9 20:11:47 arm postfix/cleanup[885]: 2D95E6A0790: message-id=<20200310011147.2D95E6A0790@arm.lan>
Mar  9 20:11:47 arm postfix/qmgr[724]: 2D95E6A0790: from=<arm@arm.lan>, size=816, nrcpt=1 (queue active)
Mar  9 20:11:47 arm postfix/local[887]: 2D95E6A0790: to=<arm@arm.lan>, orig_to=<arm>, relay=local, delay=0.12, delays=0.07/0/0/0.04, dsn=2.0.0, status=sent (delivered to mailbox)
Mar  9 20:11:47 arm postfix/qmgr[724]: 2D95E6A0790: removed
```

/home/arm/logs/ is empty

**Comment by shelvacu** [comment]
Look in `arm`'s local mailbox with the `mail` command. You should also try running arm manually with `/opt/arm/arm/main.py sr0` and see if you get any errors.

**Comment by andrewguest** [comment]
I just had this same issue. I tried to manually run `/opt/arm/arm/main.py -d sr0` but I was getting this error:

> Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 19, in <module>
    from getkeys import grabkeys
  File "/opt/arm/arm/getkeys.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'

Turns out there's already an issue, #327, to fix this bad import. It should read:
`from werkzeug.utils import cached_property`

There's an open PR on the robobrowser's GitHub page for this same issue: [PR 94](https://github.com/jmcarp/robobrowser/pull/94)


After changing that I was able to manually run the script and ARM started working automatically.

**Comment by shelvacu** [comment]
you can also downgrade the werkzeug dependency:

`python3 -m pip install -U werkzeug==0.16.0`
