### ISSUE TITLE
Ripping data disks errors right before it starts the procedure. 

### ISSUE THREAD

**Issue by pitastrudl** [automatic-ripping-machine/automatic-ripping-machine#381]
### Description
When inserting the disc, it waits a bit, then ejects it. In the **media** folder the directories are made but they are empty. Logs show a python error.  I followed the guide on the README.md. 

### Environment
Ubuntu destkop LTS 20.04, ARM version of 
ARM version: 2.1.0-dev
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

### Log file
The error happens and then the log ends. I enabled DEBUG mode. 

```
[2020-12-22 19:56:49] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 432, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 355, in main
    if utils.rip_data(job, datapath, logfile):
  File "/opt/arm/arm/ripper/utils.py", line 316, in rip_data
    cfg["DATA_RIP_PARAMETERS"],
NameError: name 'cfg' is not defined
```

/etc/fstab

```
# /etc/fstab: static file system information.                                                 
#                                                                                             
# Use 'blkid' to print the universally unique identifier for a                                
# device; this may be used with UUID= as a more robust way to name devices                    
# that works even if disks are added and removed. See fstab(5).                               
#                                                                                             
# <file system> <mount point>   <type>  <options>       <dump>  <pass>                        
# / was on /dev/sda5 during installation                                                      
UUID=4e42ce93-a205-48c6-991d-ae53682311df /               ext4    errors=remount-ro 0       1 
# /boot/efi was on /dev/sda1 during installation                                              
UUID=343A-774D  /boot/efi       vfat    umask=0077      0       1                             
/swapfile                                 none            swap    sw              0       0   
/dev/fd0        /media/floppy0  auto    rw,user,noauto,exec,utf8 0       0                    
                                                                                              
/dev/sr0  /mnt/dev/sr0  udf,iso9660  user,noauto,exec,utf8  0  0                              
/dev/sr1  /mnt/dev/sr1  udf,iso9660  user,noauto,exec,utf8  0  0                              
/dev/sr2  /mnt/dev/sr2  udf,iso9660  user,noauto,exec,utf8  0  0       
```                       

[empty.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5731587/empty.log)

[None_160866339491.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5731590/None_160866339491.log)

[SERVERGUIDE8.1.02_160866340357.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5731586/SERVERGUIDE8.1.02_160866340357.log)

**Comment by pitastrudl** [comment]
This is the config file. 

[arm.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5731741/arm.txt)

**Comment by 1337-server** [comment]
You will need to modify /opt/arm/arm/ripper/utils.py

find `cfg["DATA_RIP_PARAMETERS"]` replace it with `job.config.DATA_RIP_PARAMETERS`

**Comment by pitastrudl** [comment]
thank you, that has worked for me! happily chugging the disks.
