### ISSUE TITLE
Two tasks show up in Active Rips (once thats fixed i'll move on to makemkvcon doesn't see a drive)

### ISSUE THREAD

**Issue by cooljimy84** [automatic-ripping-machine/automatic-ripping-machine#387]
### Description
When inserting a disk i get two tasks for the same disk, within a few seconds of each other.

MOHABBATEIN_160995278901.log | 2021-01-06 17:11:29 | 12.3 | tail | arm | full | download
-- | -- | -- | -- | -- | -- | --
MOHABBATEIN.log | 2021-01-06 17:11:24 | 11.0 | tail | arm | full | download

Also makemkvcon can't see a drive..

### Environment
ubuntu server 18.04.5LTS
commit 88516d57e39069000f50c504ae9d79790a390a2c (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 199156f f7450fb
Author: flammableliquids <geforbes@gmail.com>
Date:   Fri Nov 13 15:55:41 2020 +1100

    Merge pull request #366 from flammableliquids/v2.2_dev
    
    Updates to Master for logging improvements and HandBrake limiter.
    Plus instructions on sysmail configuration, Ubuntu 20 instructions / improvements and GPU assisted trans-coding instructions.

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

Loading log: MOHABBATEIN_160995278901.log...

[2021-01-06 17:06:29] INFO ARM: main.<module> Starting ARM processing at 2021-01-06 17:06:29.007815
[2021-01-06 17:06:29] DEBUG ARM: utils.check_db_version Head is: c3a3fa694636
[2021-01-06 17:06:29] DEBUG ARM: utils.check_db_version Database version is: c3a3fa694636
[2021-01-06 17:06:29] INFO ARM: utils.check_db_version Database is up to date
[2021-01-06 17:06:29] INFO ARM: main.<module> ARM version: 2.1.0-dev
[2021-01-06 17:06:29] INFO ARM: main.<module> Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
[2021-01-06 17:06:29] INFO ARM: main.<module> User is: arm
[2021-01-06 17:06:29] INFO ARM: logger.cleanuplogs Looking for log files older than 1 days old.
[2021-01-06 17:06:29] INFO ARM: main.<module> Job: MOHABBATEIN
[2021-01-06 17:06:29] INFO ARM: main.<module> Job #13 with PID 991 is currently running.
[2021-01-06 17:06:29] INFO ARM: main.<module> Job #14 with PID 1037 is currently running.
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params **** Logging udev attributes ****
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params DEVLINKS:/dev/disk/by-path/pci-0000:00:01.1-ata-2 /dev/disk/by-label/MOHABBATEIN /dev/disk/by-id/ata-QEMU_DVD-ROM_QM00003 /dev/cdrom /dev/disk/by-uuid/021c8b3620202020 /dev/dvd
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr0
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:01.1/ata2/host1/target1:0:0/1:0:0:0/block/sr0
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params DEVTYPE:disk
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_ATA:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_BUS:ata
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_DVD:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_DVD:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_SESSION_COUNT:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_STATE:complete
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT_DATA:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MRW:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_CDROM_MRW_W:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FOR_SEAT:block-pci-0000_00_01_1-ata-2
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_LABEL:MOHABBATEIN
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_LABEL_ENC:MOHABBATEIN
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_TYPE:udf
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_USAGE:filesystem
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_UUID:021c8b3620202020
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_UUID_ENC:021c8b3620202020
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_FS_VERSION:2.80
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_MODEL:QEMU_DVD-ROM
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_MODEL_ENC:QEMU\x20DVD-ROM\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_PATH:pci-0000:00:01.1-ata-2
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_PATH_TAG:pci-0000_00_01_1-ata-2
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_REVISION:2.5+
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_SERIAL:QEMU_DVD-ROM_QM00003
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_SERIAL_SHORT:QM00003
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params ID_TYPE:cd
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params MAJOR:11
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params MINOR:0
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params SUBSYSTEM:block
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params SYSTEMD_MOUNT_DEVICE_BOUND:1
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params TAGS::seat:uaccess:systemd:
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:1133428
[2021-01-06 17:06:29] DEBUG ARM: main.log_udev_params **** End udev attributes ****
[2021-01-06 17:06:29] INFO ARM: main.main Starting Disc identification
[2021-01-06 17:06:29] DEBUG ARM: identify.identify Identification starting: Job: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f5c81469780>) (job_length=None) (poster_url_auto=None) (ejected=False) (year_manual=None) (poster_url_manual=None) (status=active) (updated=False) (video_type=unknown) (devpath=/dev/sr0) (no_of_titles=None) (pid=1037) (video_type_auto=None) (job_id=14) (mountpoint=/mnt/dev/sr0) (title=None) (video_type_manual=None) (arm_version=2.1.0-dev) (pid_hash=8264589899175957207) (hasnicetitle=False) (title_auto=None) (crc_id=None) (imdb_id=None) (errors=None) (title_manual=None) (logfile=MOHABBATEIN_160995278901.log) (imdb_id_auto=None) (disctype=dvd) (year=None) (imdb_id_manual=None) (start_time=2021-01-06 17:06:29.010476) (label=MOHABBATEIN) (year_auto=None) (stop_time=None) (poster_url=None) (config=Config: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f5c8094d828>) (MAX_CONCURRENT_TRANSCODES=1) (DATA_RIP_PARAMETERS=conv=noerror,sync) (VIDEOTYPE=auto) (SET_MEDIA_PERMISSIONS=False) (EMBY_REFRESH=False) (PO_APP_KEY=) (EXTRAS_SUB=extras) (HASHEDKEYS=False) (EMBY_PASSWORD=) (MINLENGTH=600) (CHMOD_VALUE=777) (EMBY_SERVER=) (OMDB_API_KEY=5528626c) (INSTALLPATH=/opt/arm/) (HB_PRESET_DVD=HQ 720p30 Surround) (EMBY_API_KEY=) (MAXLENGTH=99999) (SET_MEDIA_OWNER=False) (EMBY_PORT=8096) (LOGPATH=/home/arm/logs/) (HB_PRESET_BD=HQ 1080p30 Surround) (NOTIFY_RIP=True) (MANUAL_WAIT=True) (CHOWN_USER=None) (EMBY_CLIENT=ARM) (CONFIG_ID=14) (LOGLEVEL=DEBUG) (DEST_EXT=mkv) (NOTIFY_TRANSCODE=True) (MANUAL_WAIT_TIME=300) (CHOWN_GROUP=None) (EMBY_DEVICE=ARM) (job_id=14) (LOGLIFE=1) (HANDBRAKE_CLI=HandBrakeCLI) (PB_KEY=) (ARMPATH=/home/arm/media/completed/) (RIPMETHOD=backup) (EMBY_DEVICEID=ARM) (ARM_CHECK_UDF=True) (DBFILE=/home/arm/db/arm.db) (MAINFEATURE=False) (IFTTT_KEY=) (RAWPATH=/home/arm/media/raw/) (MKV_ARGS=) (EMBY_USERNAME=) (GET_VIDEO_TITLE=True) (WEBSERVER_IP=x.x.x.x) (HB_ARGS_DVD=--subtitle scan -F) (IFTTT_EVENT=arm_event) (MEDIA_DIR=/home/arm/media/movies/) (DELRAWFILES=True) (EMBY_USERID=) (SKIP_TRANSCODE=False) (WEBSERVER_PORT=8080) (HB_ARGS_BD=--subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio) (PO_USER_KEY=) ) 
[2021-01-06 17:06:29] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr0
[2021-01-06 17:06:29] DEBUG ARM: identify.identify Found: /mnt/dev/sr0/BDMV
[2021-01-06 17:06:29] INFO ARM: identify.identify Disc identified as video
[2021-01-06 17:06:29] ERROR ARM: identify.identify_bluray Disc is a bluray, but bdmt_eng.xml could not be found.  Disc cannot be identified.  Error number is: 2
[2021-01-06 17:06:29] INFO ARM: identify.identify Disc title: None : None : unknown
[2021-01-06 17:06:29] DEBUG ARM: identify.identify Identification complete: Job: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f5c81469780>) (job_length=None) (poster_url_auto=None) (ejected=False) (year_manual=None) (poster_url_manual=None) (status=active) (updated=False) (video_type=unknown) (devpath=/dev/sr0) (no_of_titles=None) (pid=1037) (video_type_auto=None) (job_id=14) (mountpoint=/mnt/dev/sr0) (title=None) (video_type_manual=None) (arm_version=2.1.0-dev) (pid_hash=8264589899175957207) (hasnicetitle=False) (title_auto=None) (crc_id=None) (imdb_id=None) (errors=None) (title_manual=None) (logfile=MOHABBATEIN_160995278901.log) (imdb_id_auto=None) (disctype=bluray) (year=None) (imdb_id_manual=None) (start_time=2021-01-06 17:06:29.010476) (label=MOHABBATEIN) (year_auto=None) (stop_time=None) (poster_url=None) 
[2021-01-06 17:06:29] INFO ARM: main.main Waiting 300 seconds for manual override.
[2021-01-06 17:11:29] INFO ARM: main.main Manual override found.  Overriding auto identification values.
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params **** Logging ARM variables ****
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params devpath: /dev/sr0
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params mountpoint: /mnt/dev/sr0
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params title: Mohabbatein
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params year: 2000
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params video_type: movie
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params hasnicetitle: True
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params label: MOHABBATEIN
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params disctype: bluray
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params **** End of ARM variables ****
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params **** Logging config parameters ****
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params skip_transcode: False
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params mainfeature: False
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params minlength: 600
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params maxlength: 99999
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params videotype: auto
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params manual_wait: True
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params wait_time: 300
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params ripmethod: backup
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params mkv_args: 
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params delrawfile: True
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params hb_preset_dvd: HQ 720p30 Surround
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params hb_preset_bd: HQ 1080p30 Surround
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params hb_args_dvd: --subtitle scan -F
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params logfile: /home/arm/logs/MOHABBATEIN_160995278901.log
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params armpath: /home/arm/media/completed/
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params rawpath: /home/arm/media/raw/
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params media_dir: /home/arm/media/movies/
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params extras_sub: extras
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params emby_refresh: False
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params emby_server: 
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params emby_port: 8096
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params notify_rip: True
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params notify_transcode True
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params max_concurrent_transcodes 1
[2021-01-06 17:11:29] INFO ARM: main.log_arm_params **** End of config parameters ****
[2021-01-06 17:11:29] INFO ARM: main.check_fstab Checking for fstab entry.
[2021-01-06 17:11:29] INFO ARM: main.check_fstab fstab entry is: /dev/sr0	/mnt/dev/sr0	udf,iso9660	user,noauto,exec,utf8	0	0
[2021-01-06 17:11:29] DEBUG ARM: utils.make_dir Creating directory: /home/arm/media/completed/Mohabbatein
[2021-01-06 17:11:29] INFO ARM: main.main Processing files to: /home/arm/media/completed/Mohabbatein
[2021-01-06 17:11:29] INFO ARM: makemkv.makemkv Starting MakeMKV rip. Method is backup
[2021-01-06 17:11:29] DEBUG ARM: makemkv.makemkv Getting MakeMKV disc number
[2021-01-06 17:11:29] ERROR ARM: makemkv.makemkv Call to makemkv failed with code: 1(b'')
[2021-01-06 17:11:29] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 33, in makemkv
    shell=True
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999  |grep /dev/sr0 |grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 432, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 166, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 40, in makemkv
    raise RuntimeError(err)
RuntimeError: Call to makemkv failed with code: 1(b'')

Automatic Ripping Machine. Find us on github.

**Comment by 1337-server** [comment]
Can you attach both logs please ?

Not pasting text into the box. attach both the files. This makes it much easier to read then a huge webpage on github.

**Comment by cooljimy84** [comment]
[MOHABBATEIN_160996420125.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5778037/MOHABBATEIN_160996420125.log)
[MOHABBATEIN_160996420628.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5778038/MOHABBATEIN_160996420628.log)

Logs attached, I know it also fails with the MKV no disk found, but the fact it shows two tasks is painful when ripping data disc to iso as it create two folders and two files

**Comment by 1337-server** [comment]
Ive personally had a similar issue appear. This was because of a faulty drive in my own issue. This might not be the case in this issue.

However i got around the issue by disabling double rips of the same disc. And it worked great untill i bought a newer drive and the issue stopped happening.

Maybe adding the disabling of duplicate rips would be something that would work for you ?
I have already submitted a PR #373 that adds the option of disabling dupe rips.

**Comment by cooljimy84** [comment]
Thanks, i'll give that a go, tho it's a virtual guest with an ISO passed as the drive (so might well be the issue as makemkv is saying it can't see any drive).
I'm also gonna try the v2.0 on a 18.04 server and/or try this 2.2 on a 20.04 server

**Comment by 1337-server** [comment]
Appologies. This is a comfirmed bug, i missed it i thought this had already been patched out.
The problem is that ARM adds a duplicate job when ever you update the job via the ARMui.

The code causing this error is located in /opt/arm/arm/ui/routes.py
look for 

```
    job.poster_url = poster_url
    job.hasnicetitle = True
    db.session.add(job)
    db.session.commit()
```

change it to

```
    job.poster_url = poster_url
    job.hasnicetitle = True
    db.session.commit()
```

This will stop the dupe jobs when ever you update a disc.

**Comment by 1337-server** [comment]
Assuming this is now resolved.
