### ISSUE TITLE
Web UI error Due to Processor Name

### ISSUE THREAD

**Issue by n8detar** [automatic-ripping-machine/automatic-ripping-machine#402]
### Description
Web UI is not loading correctly. 
"automatic-ripping-machine/arm/ui/routes.py" determines processor name (At least that's what I'm assuming the function get_processor_name() is doing) from "cat /proc/cpuinfo" and includes "GHz" as part of the filter. On my system model name looks like this:
`model name      : AMD Ryzen 7 3700X 8-Core Processor`
It doesn't include GHz at the end of the line. This means it fails to determine the processor name and the webpage doesn't work. Simply removing just the GHz part from line 251 seems to fix the issue, though I'm definitely not an expert when it comes to this sort of stuff and there may be a reason it was included.

### Environment
Unraid Host, Ubuntu VM
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

v2_master

### Website Error

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/arm/arm/ui/routes.py", line 229, in home
    ourcpu = get_processor_name()
  File "/opt/arm/arm/ui/routes.py", line 253, in get_processor_name
    speeds = str(speeds.group())
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 1337-server** [comment]
Can you test this commit change ?

**Comment by n8detar** [comment]
Sure, however, I'm not sure how to import the change into my setup.

**Comment by n8detar** [comment]
Just tested the change and it is working correctly. Thanks!

**Comment by 1337-server** [comment]
Glad its fixed.
