### ISSUE TITLE
arm v2 master

### ISSUE THREAD

**Issue by cpesko** [automatic-ripping-machine/automatic-ripping-machine#418]
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:38005401
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params **** End udev attributes ****
[2021-03-28 06:38:18] INFO ARM: main.main Starting Disc identification
[2021-03-28 06:38:18] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr2
[2021-03-28 06:38:52] DEBUG ARM: identify.identify Found: /mnt/dev/sr2/video_ts
[2021-03-28 06:38:52] INFO ARM: identify.identify Disc identified as video
[2021-03-28 06:38:52] ERROR ARM: identify.identify_dvd Pydvdid failed with the error: Path '/mnt/dev/sr2/VIDEO_TS' does not exist.
[2021-03-28 06:38:52] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 502, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 133, in main
    identify.identify(job, logfile)
  File "/opt/arm/arm/ripper/identify.py", line 66, in identify
    res = identify_dvd(job)
  File "/opt/arm/arm/ripper/identify.py", line 171, in identify_dvd
    logging.info("DVD CRC64 hash is: " + str(crc64))
UnboundLocalError: local variable 'crc64' referenced before assignment
[2021-03-28 06:38:56] DEBUG ARM: models.eject failed to eject/dev/sr2

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by cpesko** [comment]
Loading log: FRIDAY_161691349810.log...
[2021-03-28 06:38:18] INFO ARM: main.<module> Starting ARM processing at 2021-03-28 06:38:18.101405
[2021-03-28 06:38:18] DEBUG ARM: utils.check_db_version Head is: c3a3fa694636
[2021-03-28 06:38:18] DEBUG ARM: utils.check_db_version Database version is: c3a3fa694636
[2021-03-28 06:38:18] INFO ARM: utils.check_db_version Database is up to date
[2021-03-28 06:38:18] INFO ARM: main.<module> ARM version: 2.2.0-dev
[2021-03-28 06:38:18] INFO ARM: main.<module> Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
[2021-03-28 06:38:18] INFO ARM: main.<module> User is: arm
[2021-03-28 06:38:18] INFO ARM: logger.cleanuplogs Looking for log files older than 1 days old.
[2021-03-28 06:38:18] INFO ARM: main.<module> Job: FRIDAY
[2021-03-28 06:38:18] INFO ARM: main.<module> Job #3 with PID 6026 is currently running.
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params **** Logging udev attributes ****
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params DEVLINKS:/dev/disk/by-id/ata-ATAPI_iHAS124_C_3524434_2C8230502125 /dev/disk/by-path/pci-0000:04:00.0-ata-1 /dev/cdrom
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr0
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:05.0/0000:04:00.0/ata3/host2/target2:0:0/2:0:0:0/block/sr0
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params DEVTYPE:disk
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_ATA:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_ATA_SATA:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_ATA_SATA_SIGNAL_RATE_GEN1:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_BUS:ata
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_CD:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_CD_R:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_CD_RW:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_RW:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R_DL:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_R:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RAM:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RW:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_FOR_SEAT:block-pci-0000_04_00_0-ata-1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_MODEL:ATAPI_iHAS124_C
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_MODEL_ENC:ATAPI\x20\x20\x20iHAS124\x20\x20\x20C\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_PATH:pci-0000:04:00.0-ata-1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_PATH_TAG:pci-0000_04_00_0-ata-1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_REVISION:LL0E
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_SCSI:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_SCSI_INQUIRY:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_SERIAL:ATAPI_iHAS124_C_3524434_2C8230502125
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_SERIAL_SHORT:3524434_2C8230502125
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params ID_TYPE:cd
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params MAJOR:11
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params MINOR:0
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SCSI_MODEL:iHAS124_C
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SCSI_MODEL_ENC:iHAS124\x20\x20\x20C\x20\x20\x20\x20\x20
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SCSI_REVISION:LL0E
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SCSI_TPGS:0
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SCSI_TYPE:cd/dvd
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SUBSYSTEM:block
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SYSTEMD_MOUNT_DEVICE_BOUND:1
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params SYSTEMD_READY:0
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params TAGS::systemd:seat:uaccess:
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:38005401
[2021-03-28 06:38:18] DEBUG ARM: main.log_udev_params **** End udev attributes ****
[2021-03-28 06:38:18] INFO ARM: main.main Starting Disc identification
[2021-03-28 06:38:18] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr2
[2021-03-28 06:38:52] DEBUG ARM: identify.identify Found: /mnt/dev/sr2/video_ts
[2021-03-28 06:38:52] INFO ARM: identify.identify Disc identified as video
[2021-03-28 06:38:52] ERROR ARM: identify.identify_dvd Pydvdid failed with the error: Path '/mnt/dev/sr2/VIDEO_TS' does not exist.
[2021-03-28 06:38:52] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 502, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 133, in main
    identify.identify(job, logfile)
  File "/opt/arm/arm/ripper/identify.py", line 66, in identify
    res = identify_dvd(job)
  File "/opt/arm/arm/ripper/identify.py", line 171, in identify_dvd
    logging.info("DVD CRC64 hash is: " + str(crc64))
UnboundLocalError: local variable 'crc64' referenced before assignment
[2021-03-28 06:38:56] DEBUG ARM: models.eject failed to eject/dev/sr2

**Comment by 1337-server** [comment]
Pull that i linked should fix this issue.

**Comment by cpesko** [comment]
link?

**Comment by 1337-server** [comment]
https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/419
