### ISSUE TITLE
Data disc fails to rip

### ISSUE THREAD

**Issue by sukuoru** [automatic-ripping-machine/automatic-ripping-machine#432]
### Description
[Description of Bug, Feature, Question, etc.]
This was the first data dvd I tried to rip, movies and cds have been fine so far. It just spits the disc out with the error I have pasted lower. It seemed similar to other issues, but wasn't quite sure. I really was just trying to see how the data rip would work.

Thanks in advance!

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
* v2_master

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[2021-05-31 18:13:04] INFO ARM: Drive appears to be empty or is not ready.  Exiting ARM.
[2021-05-31 18:18:04] INFO ARM: main.<module> Starting ARM processing at 2021-05-31 18:18:04.083182
[2021-05-31 18:18:04] DEBUG ARM: utils.check_db_version Head is: c3a3fa694636
[2021-05-31 18:18:04] DEBUG ARM: utils.check_db_version Database version is: c3a3fa694636
[2021-05-31 18:18:04] INFO ARM: utils.check_db_version Database is up to date
[2021-05-31 18:18:04] INFO ARM: main.<module> ARM version: 2.2.0-dev
[2021-05-31 18:18:04] INFO ARM: main.<module> Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
[2021-05-31 18:18:04] INFO ARM: main.<module> User is: arm
[2021-05-31 18:18:04] INFO ARM: logger.cleanuplogs Looking for log files older than 1 days old.
[2021-05-31 18:18:04] INFO ARM: main.<module> Job: None
[2021-05-31 18:18:04] INFO ARM: main.<module> Job #212 with PID 178497 is currently running.
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params **** Logging udev attributes ****
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params DEVLINKS:/dev/disk/by-path/pci-0000:00:13.0-ata-2 /dev/disk/by-id/wwn-0x5001480000000000 /dev/dvdrw /dev/disk/by-id/ata-hp_DVD-RAM_GH40L_948CD049359 /dev/cdrw /dev/cdrom /dev/dvd
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr0
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:13.0/ata2/host1/target1:0:0/1:0:0:0/block/sr0
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params DEVTYPE:disk
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_ATA:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_ATA_SATA:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_ATA_SATA_SIGNAL_RATE_GEN1:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_BUS:ata
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_CD:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_CD_R:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_CD_RW:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_RW:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R_DL:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_R:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RAM:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RW:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_DVD:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_SESSION_COUNT:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_STATE:complete
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT_DATA:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_FOR_SEAT:block-pci-0000_00_13_0-ata-2
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_MODEL:hp_DVD-RAM_GH40L
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_MODEL_ENC:hp\x20\x20\x20\x20\x20\x20DVD-RAM\x20GH40L\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_PART_TABLE_TYPE:mac
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_PATH:pci-0000:00:13.0-ata-2
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_PATH_TAG:pci-0000_00_13_0-ata-2
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_REVISION:RB0E
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_SERIAL:hp_DVD-RAM_GH40L_948CD049359
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_SERIAL_SHORT:948CD049359
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_TYPE:cd
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_WWN:0x5001480000000000
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params ID_WWN_WITH_EXTENSION:0x5001480000000000
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params MAJOR:11
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params MINOR:0
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params SUBSYSTEM:block
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params SYSTEMD_MOUNT_DEVICE_BOUND:1
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params TAGS::uaccess:seat:systemd:
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:2097876
[2021-05-31 18:18:04] DEBUG ARM: main.log_udev_params **** End udev attributes ****
[2021-05-31 18:18:04] INFO ARM: main.main Starting Disc identification
[2021-05-31 18:18:04] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr0
[2021-05-31 18:18:04] DEBUG ARM: identify.identify Did not find valid dvd/bd files. Changing disctype to 'data'
[2021-05-31 18:18:04] INFO ARM: main.main Waiting 60 seconds for manual override.
[2021-05-31 18:19:04] INFO ARM: main.main No manual override found.
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params **** Logging ARM variables ****
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params devpath: /dev/sr0
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params mountpoint: /mnt/dev/sr0
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params title: None
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params year: None
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params video_type: unknown
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params hasnicetitle: False
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params label: None
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params disctype: data
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params **** End of ARM variables ****
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params **** Logging config parameters ****
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params skip_transcode: False
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params mainfeature: False
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params minlength: 600
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params maxlength: 99999
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params videotype: auto
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params manual_wait: True
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params wait_time: 60
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params ripmethod: backup
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params mkv_args: 
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params delrawfile: True
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params hb_preset_dvd: HQ 720p30 Surround
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params hb_preset_bd: HQ 1080p30 Surround
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params hb_args_dvd: --subtitle-lang-list eng --all-subtitles --native-language eng --subtitle-default=scan --subtitle-burned=none
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params logfile: /home/arm/logs/empty.log
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params armpath: /home/arm/media/completed/
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params rawpath: /home/arm/media/raw/
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params media_dir: /home/arm/media/movies/
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params extras_sub: extras
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params emby_refresh: False
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params emby_server: 
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params emby_port: 8096
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params notify_rip: True
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params notify_transcode True
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params max_concurrent_transcodes 3
[2021-05-31 18:19:04] INFO ARM: main.log_arm_params **** End of config parameters ****
[2021-05-31 18:19:04] INFO ARM: main.check_fstab Checking for fstab entry.
[2021-05-31 18:19:04] INFO ARM: main.check_fstab fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8  0  0
[2021-05-31 18:19:04] DEBUG ARM: utils.make_dir Creating directory: /home/arm/media/completed/None_162249954496
[2021-05-31 18:19:04] INFO ARM: utils.rip_data Disc identified as data
[2021-05-31 18:19:04] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 504, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 427, in main
    if utils.rip_data(job, datapath, logfile):
  File "/opt/arm/arm/ripper/utils.py", line 1023, in rip_data
    filename = os.path.join(datapath, job.label + ".iso")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2021-05-31 18:19:04] DEBUG ARM: models.eject we unmounted disc/dev/sr0
[2021-05-31 18:19:09] DEBUG ARM: models.eject failed to eject/dev/sr0
[2021-05-31 18:19:16] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.

**Comment by 1337-server** [comment]
Can you modify 

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/851db6f4862a3872702a64e5467a853cca0d058d/arm/ripper/utils.py#L1020

and change it to

`if job.label == "" or job.label is None:`

**Comment by sukuoru** [comment]
After changing that it stopped trying the drive automatically, and I had to manually run ARM. this was the result:

python3 main.py -d sr0
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa: E402
  File "/opt/arm/arm/ripper/__init__.py", line 1, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, getkeys  # noqa F401
  File "/opt/arm/arm/ripper/utils.py", line 1021
    if job.label == "" or job.label is None:
                                           ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by 1337-server** [comment]
Try this, the space at the beginning is important.

```
        if job.label == "" or job.label is None:
```

**Comment by sukuoru** [comment]
Same error, the ^ is underneath the : after None
I backspaced and tabbed that bit forward so it was the same spacing as the original bit.

**Comment by 1337-server** [comment]
Dont use tabs, use 4 spaces instead.


Can you try posting the code again in code blocks ?  The formatting seems to have gotten messed up.

You can use 3 backticks to keep code formatting like this.

 \`\`\` 
insert code here
 \`\`\`

**Comment by sukuoru** [comment]
After replacing the tab with 4 spaces, a new error:
````
python3 /opt/arm/arm/ripper/main.py -d sr0
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 17, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa: E402
  File "/opt/arm/arm/ripper/__init__.py", line 1, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, getkeys  # noqa F401
  File "/opt/arm/arm/ripper/utils.py", line 1024
    filename = os.path.join(datapath, job.label + ".iso")
                                                        ^
IndentationError: unindent does not match any outer indentation level
````

code snippet:
```
    if job.disctype == "data":
        logging.info("Disc identified as data")

#        if job.label == "":
    if job.label == "" or job.label is None:
            job.label = "datadisc"

        filename = os.path.join(datapath, job.label + ".iso")

        logging.info("Ripping data disc to: " + filename)

        #  Added from pull 366
        cmd = 'dd if="{0}" of="{1}" {2} 2>> {3}'.format(
            job.devpath,
            filename,
            job.config.DATA_RIP_PARAMETERS,
            logfile
        )

        logging.debug("Sending command: " + cmd)
```

**Comment by sukuoru** [comment]
Thank you for your help! Looks like it's time for me to learn Python!
