### ISSUE TITLE
Rips Fail 

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#446]
### Description
Rip failed,  in fact, I haven't been able to get a rip of anything.  THe full size untanscoded mkv files are getting ripped,  but it seems to fail on trying to finish compressing the file

### Environment
[OS Distribution and version 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

* v2_devel
* 
[DVD_VIDEO_162837619706.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6951260/DVD_VIDEO_162837619706.log)

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

HEre's what I get in my log 

[08-08-2021 13:28:05] DEBUG ARM: main.main New Title is Motion Picture and Video Lighting DVD Second Edition
[08-08-2021 13:28:05] INFO ARM: main.main Moving Movie Pollock_t00.mkv to /home/arm/media/completed/movies/Motion Picture and Video Lighting DVD Second Edition (2007)
[08-08-2021 13:28:05] DEBUG ARM: main.main_feature_test track main is false - checking size
[08-08-2021 13:28:05] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 440, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 314, in main
    utils.move_files(hb_out_path, track.filename, job, main_feature_test(main_feature, track))
  File "/opt/arm/arm/ripper/main.py", line 304, in main_feature_test
    if m.length == t.length:
AttributeError: 'NoneType' object has no attribute 'length'
[08-08-2021 13:28:05] DEBUG ARM: models.eject we unmounted disc/dev/sr0
[08-08-2021 13:28:05] DEBUG ARM: models.eject failed to eject/dev/sr0

**Comment by 1337-server** [comment]
It looks like ARM is passing in a None type instead of the track object from the database. Not sure why this is happening.

try blocks will most likely need to be added so that ARM doesnt die and continues as best as it can. Or a check of the type the **t** (track) variable to make sure its not None

**Comment by 1337-server** [comment]
Ok it seems that 'None' is passed in from the mainfeature as none of the tracks are flagged as the main_feature true. And wasn't the **T** variable but the **m** variable. I've removed this until i can find a better way of checking the size of all the tracks.
