### ISSUE TITLE
Crash with TypeError in join()

### ISSUE THREAD

**Issue by PriamX** [automatic-ripping-machine/automatic-ripping-machine#459]
### Description
Crashes when with type error in the join() function after inserting bluray.

### Environment
Fedora release 34 (Thirty Four)
ARM version: 2.1.0-dev
Python version: 3.9.7

### Log file
[2021-10-27 13:19:34] INFO ARM: Starting ARM processing at 2021-10-27 13:19:34.922131
[2021-10-27 13:19:34] INFO ARM: Database is up to date
[2021-10-27 13:19:34] INFO ARM: ARM version: 2.1.0-dev
[2021-10-27 13:19:34] INFO ARM: Python version: 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
[2021-10-27 13:19:34] INFO ARM: User is: arm
[2021-10-27 13:19:34] INFO ARM: Looking for log files older than 7 days old.
[2021-10-27 13:19:34] INFO ARM: Deleting log file: music_cd.log
[2021-10-27 13:19:34] INFO ARM: Deleting log file: empty.log
[2021-10-27 13:19:34] INFO ARM: Deleting log file: THE_BIRDMEN.log
[2021-10-27 13:19:34] INFO ARM: Deleting log file: None_163451176750.log
[2021-10-27 13:19:34] INFO ARM: Job: SNAFU
[2021-10-27 13:19:34] INFO ARM: Job #34 with PID 1633394 is currently running.
[2021-10-27 13:19:34] INFO ARM: Starting Disc identification
[2021-10-27 13:19:34] INFO ARM: Mounting disc to: /mnt/dev/sr0
[2021-10-27 13:19:38] INFO ARM: Disc identified as video
[2021-10-27 13:19:38] ERROR ARM: Disc is a bluray, but bdmt_eng.xml could not be found.  Disc cannot be identified.  Error number is: 2
[2021-10-27 13:19:38] INFO ARM: Disc title: None : None : unknown
[2021-10-27 13:19:38] INFO ARM: Waiting 120 seconds for manual override.
[2021-10-27 13:21:38] INFO ARM: No manual override found.
[2021-10-27 13:21:38] INFO ARM: **** Logging ARM variables ****
[2021-10-27 13:21:38] INFO ARM: devpath: /dev/sr0
[2021-10-27 13:21:38] INFO ARM: mountpoint: /mnt/dev/sr0
[2021-10-27 13:21:38] INFO ARM: title: None
[2021-10-27 13:21:38] INFO ARM: year: None
[2021-10-27 13:21:38] INFO ARM: video_type: unknown
[2021-10-27 13:21:38] INFO ARM: hasnicetitle: False
[2021-10-27 13:21:38] INFO ARM: label: SNAFU
[2021-10-27 13:21:38] INFO ARM: disctype: bluray
[2021-10-27 13:21:38] INFO ARM: **** End of ARM variables ****
[2021-10-27 13:21:38] INFO ARM: **** Logging config parameters ****
[2021-10-27 13:21:38] INFO ARM: skip_transcode: False
[2021-10-27 13:21:38] INFO ARM: mainfeature: False
[2021-10-27 13:21:38] INFO ARM: minlength: 600
[2021-10-27 13:21:38] INFO ARM: maxlength: 99999
[2021-10-27 13:21:38] INFO ARM: videotype: auto
[2021-10-27 13:21:38] INFO ARM: manual_wait: True
[2021-10-27 13:21:38] INFO ARM: wait_time: 120
[2021-10-27 13:21:38] INFO ARM: ripmethod: mkv
[2021-10-27 13:21:38] INFO ARM: mkv_args: 
[2021-10-27 13:21:38] INFO ARM: delrawfile: True
[2021-10-27 13:21:38] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[2021-10-27 13:21:38] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[2021-10-27 13:21:38] INFO ARM: hb_args_dvd: --subtitle scan -F
[2021-10-27 13:21:38] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[2021-10-27 13:21:38] INFO ARM: logfile: /home/arm/logs/SNAFU.log
[2021-10-27 13:21:38] INFO ARM: armpath: /home/arm/media/completed/
[2021-10-27 13:21:38] INFO ARM: rawpath: /home/arm/media/raw/
[2021-10-27 13:21:38] INFO ARM: media_dir: /home/arm/media/movies/
[2021-10-27 13:21:38] INFO ARM: extras_sub: extras
[2021-10-27 13:21:38] INFO ARM: emby_refresh: False
[2021-10-27 13:21:38] INFO ARM: emby_server: 
[2021-10-27 13:21:38] INFO ARM: emby_port: 8096
[2021-10-27 13:21:38] INFO ARM: notify_rip: True
[2021-10-27 13:21:38] INFO ARM: notify_transcode True
[2021-10-27 13:21:38] INFO ARM: max_concurrent_transcodes 3
[2021-10-27 13:21:38] INFO ARM: **** End of config parameters ****
[2021-10-27 13:21:38] INFO ARM: Checking for fstab entry.
[2021-10-27 13:21:38] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  user,noauto,exec,utf8  0  0
[2021-10-27 13:21:38] INFO ARM: Processing files to: /home/arm/media/completed/None
[2021-10-27 13:21:38] INFO ARM: Starting MakeMKV rip. Method is mkv
[2021-10-27 13:21:45] INFO ARM: MakeMKV disc number: 0
[2021-10-27 13:21:45] ERROR ARM: A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 432, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 166, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 43, in makemkv
    rawpath = os.path.join(job.config.RAWPATH, job.title)
  File "/usr/lib64/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by 1337-server** [comment]
Was fixed in v2.2
