### ISSUE TITLE
Server does not start ripping - errors 

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#468]
### Description
Server does not start ripping - errors out 

### Environment
Ubuntu 18.04
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
dev/sr0
Log: /home/arm/logs/STAR_TREK_V.log 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 470, in <module>
    db.session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 249, in save_obj
    insert,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1224, in _emit_insert_statements
    execution_options=execution_options,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO job (arm_version, crc_id, logfile, start_time, stop_time, job_length, status, no_of_titles, title, title_auto, title_manual, year, year_auto, year_manual, video_type, video_type_auto, video_type_manual, imdb_id, imdb_id_auto, imdb_id_manual, poster_url, poster_url_auto, poster_url_manual, devpath, mountpoint, hasnicetitle, errors, disctype, label, ejected, updated, pid, pid_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, None, 'STAR_TREK_V.log', '2022-01-06 13:13:24.879423', None, None, 'active', None, None, None, None, None, None, None, 'unknown', None, None, None, None, None, None, None, None, '/dev/sr0', '/mnt/dev/sr0', 0, None, 'dvd', 'STAR_TREK_V', 0, 0, 22205, -3833214082276599944)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
` sqlite3.OperationalError: attempt to write a readonly database`

Normally means that the database file isn't writeable by the arm user. Check the permission of the database file.

**Comment by 1337-server** [comment]
Assuming this is now resolved
