### ISSUE TITLE
Web UI doen't work

### ISSUE THREAD

**Issue by theGrinchUK** [automatic-ripping-machine/automatic-ripping-machine#470]
Sorry guys, fairly new to Linux apart from some RPi projects.
Made a completely new install of Ubuntu 18.04, then ARM following the how to here.

When I open the IP:8080 nothing happened.
I put the actual IP into the arm.yaml and rebootet, now I'm getting this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/arm/arm/ui/routes.py", line 79, in jobdetail
    tracks = jobs.tracks.all()
AttributeError: 'NoneType' object has no attribute 'tracks'

Any ideas?

**Comment by theGrinchUK** [comment]
After installing cockpit it now works...
