### ISSUE TITLE
Database locked error when ripping multiple dvd's

### ISSUE THREAD

**Issue by FlashyDuck** [automatic-ripping-machine/automatic-ripping-machine#500]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Ripping multiple dvd's at once will result in random errors. Some DVD's get processed, others result in error.

**To Reproduce**
1. Run ubuntu server 20.04 > use custom ubuntu server install script for installing ARM
2. setup ARM, no major changes, just no transcoding and set output folder to cache drive of other server on network
3. put in several DVD's

### Environment
Ubuntu Server 20.04
Arm 2.6 (latest, installed with ubuntu server script for auto install)
9 optical drives
250GB SSD for Ubuntu Server
1TB cache drive on my other server on the network where ARM writes the rips

### Log file
```
[2022-05-11 15:09:41] DEBUG ARM: utils.check_db_version Head is: c54d68996895
[2022-05-11 15:09:41] DEBUG ARM: utils.check_db_version Database version is: c54d68996895
[2022-05-11 15:09:41] INFO ARM: utils.check_db_version Database is up to date
[2022-05-11 15:09:42] DEBUG ARM: utils.database_adder Trying to add User
[2022-05-11 15:09:48] DEBUG ARM: utils.database_adder database is locked - try 0/90
[2022-05-11 15:09:48] DEBUG ARM: utils.database_adder Trying to add User
[2022-05-11 15:09:49] DEBUG ARM: utils.database_adder database is locked - try 1/90
[2022-05-11 15:09:49] DEBUG ARM: utils.database_adder Trying to add User
[2022-05-11 15:09:50] DEBUG ARM: utils.database_adder database is locked - try 2/90
[2022-05-11 15:09:50] DEBUG ARM: utils.database_adder Trying to add User
...
[2022-05-11 15:11:14] DEBUG ARM: utils.database_adder Trying to add User
[2022-05-11 15:11:15] DEBUG ARM: utils.database_adder database is locked - try 87/90
[2022-05-11 15:11:15] DEBUG ARM: utils.database_adder Trying to add User
[2022-05-11 15:11:16] DEBUG ARM: utils.database_adder database is locked - try 88/90
[2022-05-11 15:11:16] DEBUG ARM: utils.database_adder Trying to add User
[2022-05-11 15:11:17] DEBUG ARM: utils.database_adder database is locked - try 89/90
[2022-05-11 15:11:17] DEBUG ARM: utils.database_adder successfully written User to the database

```

After that ARM just does nothing with the DVD. I need to manually open/close the drive for ARM to see the disk again and try again.

Oh, and the DVD's that do seem to get ripped but in the end fail give a different error. Related?

```
[2022-05-11 15:10:09] INFO ARM: makemkv.prep_mkv Prepping MakeMkv for usage...
[2022-05-11 15:11:11] INFO ARM: makemkv.prep_mkv MakeMKV is working as expected!
[2022-05-11 15:11:11] INFO ARM: makemkv.makemkv Starting MakeMKV rip. Method is mkv
[2022-05-11 15:11:11] DEBUG ARM: makemkv.makemkv Getting MakeMKV disc number
[2022-05-11 15:12:15] INFO ARM: makemkv.makemkv MakeMKV disc number: 7
7
[2022-05-11 15:12:15] INFO ARM: makemkv.setup_rawpath Destination is /media/share/rips/Foyle_s_war_9
[2022-05-11 15:12:15] INFO ARM: makemkv.makemkv Processing files to: /media/share/rips/Foyle_s_war_9
[2022-05-11 15:12:15] INFO ARM: makemkv.get_track_info Using MakeMKV to get information on all the tracks on the disc. This will take a few minutes...
[2022-05-11 15:12:15] DEBUG ARM: makemkv.get_track_info Sending command: makemkvcon -r --progress=-stdout --messages=-stdout --minlength=300 --cache=1 info disc:7
7

[2022-05-11 15:14:09] ERROR ARM: makemkv.__init__ Call to MakeMKV failed with code: 127 (b'MSG:1005,0,1,"MakeMKV v1.16.7 linux(x64-release) started","%1 started","MakeMKV v1.16.7 linux(x64-release)"\nPRGT:5018,0,"Scanning CD-ROM devices"\nPRGC:5018,0,"Scanning CD-ROM devices"\nPRGV:0,0,65536\nPRGV:0,0,65536\nPRGV:6553,0,65536\nPRGV:6553,6553,65536\nPRGV:19660,6553,65536\nPRGV:19660,19660,65536\nPRGV:45875,19660,65536\nPRGV:45875,45875,65536\nPRGV:65536,45875,65536\nPRGV:65536,65536,65536\nDRV:0,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CF30046V","Foyles war 17","/dev/sr2"\nDRV:1,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224FB SB00 S16S6YAGC005JB","RCV_WAR_GAMES_NL","/dev/sr5"\nDRV:2,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224BB SB00 R8WS68AC800XL9","RCV_LESSONS_IN_MURDER_NL","/dev/sr8"\nDRV:3,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB00 R93E6YDD3001ZK","Foyle\'s war 10_Enemy Fire","/dev/sr6"\nDRV:4,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CDC02J1C","RCV_AMONG_THE_FEW_NL","/dev/sr0"\nDRV:5,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CDC028SZ","RCV_THE_FUNK_HOLE_NL","/dev/sr3"\nDRV:6,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68FDC015SX","RCV_EAGLE_DAY_NL","/dev/sr1"\nDRV:7,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224BB SB00 R8WS68DCA03C48","Foyle\'s war 9","/dev/sr4"\nDRV:8,2,999,1,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CF30003K","RCV_FIFTY_SHIPS_NL","/dev/sr7"\nDRV:9,256,999,0,"","",""\nDRV:10,256,999,0,"","",""\nDRV:11,256,999,0,"","",""\nDRV:12,256,999,0,"","",""\nDRV:13,256,999,0,"","",""\nDRV:14,256,999,0,"","",""\nDRV:15,256,999,0,"","",""\nPRGV:0,65536,65536\nPRGV:0,0,65536\nPRGT:3100,0,"Opening DVD disc"\nMSG:3007,0,0,"Using direct disc access mode","Using direct disc access mode"\nPRGC:3102,0,"Processing title sets"\nPRGV:0,0,65536\nPRGV:0,0,65536\nPRGV:8192,0,65536\nPRGV:8192,2730,65536\nPRGV:16384,2730,65536\nPRGV:16384,5461,65536\nPRGV:24576,5461,65536\nPRGV:24576,8192,65536\nPRGV:32768,8192,65536\nPRGV:32768,10922,65536\nPRGV:40960,10922,65536\nPRGV:40960,13653,65536\nPRGV:49152,13653,65536\nPRGV:49152,16384,65536\nPRGV:57344,16384,65536\nPRGV:57344,19114,65536\nPRGV:65536,19114,65536\nPRGV:65536,21845,65536\nPRGC:3103,0,"Processing titles"\nPRGV:0,21845,65536\nMSG:3025,0,3,"Title #1 has length of 15 seconds which is less than minimum title length of 300 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","1","15","300"\nPRGV:8192,21845,65536\nPRGV:8192,24576,65536\nMSG:3025,0,3,"Title #2 has length of 17 seconds which is less than minimum title length of 300 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","2","17","300"\nPRGV:16384,24576,65536\nPRGV:16384,27306,65536\nMSG:3025,0,3,"Title #3 has length of 107 seconds which is less than minimum title length of 300 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","3","107","300"\nPRGV:24576,27306,65536\nPRGV:24576,30037,65536\nMSG:3025,0,3,"Title #4 has length of 155 seconds which is less than minimum title length of 300 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","4","155","300"\nPRGV:32768,30037,65536\nPRGV:32768,32768,65536\nMSG:3025,0,3,"Title #5 has length of 135 seconds which is less than minimum title length of 300 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","5","135","300"\nPRGV:40960,32768,65536\nPRGV:40960,35498,65536\nMSG:3025,0,3,"Title #6 has length of 9 seconds which is less than minimum title length of 300 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","6","9","300"\nPRGV:49152,35498,65536\nPRGV:49152,38229,65536\nMSG:3028,0,3,"Title #7 was added (11 cell(s), 1:33:34)","Title #%1 was added (%2 cell(s), %3)","7","11","1:33:34"\nPRGC:3104,0,"Decrypting data"\nPRGV:0,38229,65536\nPRGV:49152,38229,65536\nPRGV:49152,54613,65536\nPRGV:65536,54613,65536\nPRGV:65536,60074,65536\nMSG:5011,0,0,"Operation successfully completed","Operation successfully completed"\nDRV:0,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CF30046V","","/dev/sr2"\nDRV:1,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224FB SB00 S16S6YAGC005JB","","/dev/sr5"\nDRV:2,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224BB SB00 R8WS68AC800XL9","","/dev/sr8"\nDRV:3,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB00 R93E6YDD3001ZK","","/dev/sr6"\nDRV:4,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CDC02J1C","","/dev/sr0"\nDRV:5,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CDC028SZ","","/dev/sr3"\nDRV:6,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68FDC015SX","","/dev/sr1"\nDRV:8,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E68CF30003K","","/dev/sr7"\nTCOUNT:1\nCINFO:1,6206,"DVD disc"\nCINFO:2,0,"Foyle\'s war 9"\nCINFO:30,0,"Foyle\'s war 9"\nCINFO:31,6119,"<b>Source information</b><br>"\nCINFO:32,0,"Foyle\'s war 9"\nCINFO:33,0,"0"\nTINFO:0,8,0,"11"\nTINFO:0,9,0,"1:33:34"\nTINFO:0,10,0,"3.7 GB"\nTINFO:0,11,0,"4036380672"\nTINFO:0,24,0,"07"\nTINFO:0,25,0,"1"\nTINFO:0,26,0,"1-11"\nTINFO:0,27,0,"title_t00.mkv"\nTINFO:0,30,0,"11 chapter(s) , 3.7 GB"\nTINFO:0,31,6120,"<b>Title information</b><br>"\nTINFO:0,33,0,"0"\nSINFO:0,0,1,6201,"Video"\nSINFO:0,0,5,0,"V_MPEG2"\nSINFO:0,0,6,0,"Mpeg2"\nSINFO:0,0,7,0,"Mpeg2"\nSINFO:0,0,13,0,"7 Mb/s"\nSINFO:0,0,19,0,"720x576"\nSINFO:0,0,20,0,"16:9"\nSINFO:0,0,21,0,"25"\nSINFO:0,0,22,0,"0"\nSINFO:0,0,30,0,"Mpeg2"\nSINFO:0,0,31,6121,"<b>Track information</b><br>"\nSINFO:0,0,33,0,"0"\nSINFO:0,0,38,0,""\nSINFO:0,0,42,5088,"( Lossless conversion )"\nSINFO:0,1,1,6202,"Audio"\nSINFO:0,1,2,5091,"Stereo"\nSINFO:0,1,3,0,"eng"\nSINFO:0,1,4,0,"English"\nSINFO:0,1,5,0,"A_AC3"\nSINFO:0,1,6,0,"DD"\nSINFO:0,1,7,0,"Dolby Digital"\nSINFO:0,1,13,0,"192 Kb/s"\nSINFO:0,1,14,0,"2"\nSINFO:0,1,17,0,"48000"\nSINFO:0,1,22,0,"0"\nSINFO:0,1,30,0,"DD Stereo English"\nSINFO:0,1,31,6121,"<b>Track information</b><br>"\nSINFO:0,1,33,0,"90"\nSINFO:0,1,38,0,"d"\nSINFO:0,1,39,0,"Default"\nSINFO:0,1,40,0,"stereo"\nSINFO:0,1,42,5088,"( Lossless conversion )"\nSINFO:0,2,1,6203,"Subtitles"\nSINFO:0,2,3,0,"dut"\nSINFO:0,2,4,0,"Dutch"\nSINFO:0,2,5,0,"S_VOBSUB"\nSINFO:0,2,6,0,""\nSINFO:0,2,7,0,"Dvd Subtitles"\nSINFO:0,2,22,0,"0"\nSINFO:0,2,30,0," Dutch"\nSINFO:0,2,31,6121,"<b>Track information</b><br>"\nSINFO:0,2,33,0,"90"\nSINFO:0,2,38,0,"d"\nSINFO:0,2,39,0,"Default"\nSINFO:0,2,42,5088,"( Lossless conversion )"\n/bin/sh: 2: 7: not found\n')
[2022-05-11 15:14:09] ERROR ARM: arm_ripper.rip_visual_media MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[2022-05-11 15:14:09] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
[2022-05-11 15:14:09] DEBUG ARM: selector_events.__init__ Using selector: EpollSelector
[2022-05-11 15:14:09] DEBUG ARM: models.eject Unmounted disc /dev/sr4
[2022-05-11 15:14:12] DEBUG ARM: models.eject Failed to eject /dev/sr4
```

**Comment by FlashyDuck** [comment]
Have done a bit more 'testing' and it seems that ARM doesn't like it when you give it multiple dvds at the same time. ARM needs time to process, start a job and only then you can give it another DVD. So closing drivebays over the course of 10 minutes or so will result in all 9 jobs showing and it will run perfectly fine.

Is this normal behavior? Having to wait between feeding ARM dvds?

But even when doing that I will still get an occasional fatal error from MKV. Same as the second error in my first post. 

Hope this helps.

**Comment by 1337-server** [comment]
I thought I added a workaround to this, It's not working. 

Thanks for reporting this.

**Comment by garbled1** [comment]
With my slurm setup, I have hit this a few times.  Most of the time it's ok, but once in awhile, it will just lock up.  I can usually fix it by killing off the main python process of the most recent rip.  This usually leaves a dead entry in the db, and I cannot abandon it, or it will lock the db again.  (armui goes bezerk on a locked db).  If I wait for my queue to flush out and finish, I can then delete the entry and go about doing the last few dvd's.

**Comment by 1337-server** [comment]
Closing as stale

**Comment by TallPatrick** [comment]
I've been seeing this issue intermittently in the Docker environment.  It seems very sporadic to reproduce.  There were times before I had Hardware encoding setup where I would have 9+ DVDs that were all transcoding and never had this issue, but occasionally when I have one that's transcoding and another is ripping I'll see this issue.  Next time it happens I'll grab the ARM log, as well as the log for each of the two discs being ripped so it might be possible to hone in on when in the ripping process the database is getting locked.

If nothing else, a solution I'd be happy to see implemented would just be a simple wait 30 seconds and retry.

**Comment by microtechno9000** [comment]
thanks, logs will help

there is a wrapper for the database, but not all of arm uses it. The wrapper has a retry timeout, so it might be working for some and then reach one of the none protected db calls.

will have a look over the weekend and see what can be done

**Comment by TallPatrick** [comment]
Out of sheer luck, hit the issue today ripping Pirates of the Carribean and the bonus disc of extras.  I'm attaching all the logs
[logs.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/11971266/logs.zip)
Not sure why there are two for "pirates of the Caribbean", but the one that includes the sub title (curse of the black flag) is the one that ripped first, and got the database locked error

**Comment by microtechno9000** [comment]
thanks for the logs, seems that in completing the job ARM is trying to finish up and write data, but the database is locked

seems only a single process can have access to the database, https://docs.sqlalchemy.org/en/20/dialects/sqlite.html#database-locking-behavior-concurrency.

some changes to the UI and ripper will need to be made to allow for checks and time outs. I have added this task to the project for tasking

**Comment by 1337-server** [comment]
Adding for later: Issue is here

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/09443809d329deda0265f86df725cbe954714b68/arm/ripper/handbrake.py#L208

**Comment by TallPatrick** [comment]
I just hit this error with only one disc transcoding, and no other discs ripping.  I'm using the latest docker container with the 2.6.40 version of ARM.
[arm.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/13034139/arm.log)

[DJANGO_UNCHAINED.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/13034141/DJANGO_UNCHAINED.log)

Logs for the disc being transcoded, and my ARM log are attached.

**Comment by JulleeeK** [comment]
Just wanted to mention that this issue seems to still exist, I had this error when ripping a new disk while it was still encoding the previous rip:

[10-12-2025 08:20:08] DEBUG ARM: handbrake.handbrake_mkv Handbrake exit code: 
[10-12-2025 08:20:08] DEBUG ARM: handbrake.handbrake_mkv title_t08.mkv
[10-12-2025 08:20:13] ERROR ARM: main.<module> (sqlalchemy.exc.OperationalError) (sqlite3.OperationalError) database is locked
[SQL: SELECT track.track_id AS track_track_id, track.job_id AS track_job_id, track.track_number AS track_track_number, track.length AS track_length, track.aspect_ratio AS track_aspect_ratio, track.fps AS track_fps, track.main_feature AS track_main_feature, track.basename AS track_basename, track.filename AS track_filename, track.orig_filename AS track_orig_filename, track.new_filename AS track_new_filename, track.ripped AS track_ripped, track.status AS track_status, track.error AS track_error, track.source AS track_source, track.process AS track_process 
FROM track 
WHERE ? = track.job_id AND track.filename = ?]
[parameters: [{}]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
