### ISSUE TITLE
Makemkv error 127

### ISSUE THREAD

**Issue by BobFish** [automatic-ripping-machine/automatic-ripping-machine#507]
I've installed ARM on Ubuntu 20.04 and got it all setup I believe. The UI is working. However whenever I insert a blu-ray disc it sits for about a minute and then ejects. This is my log file:

It seems to be this line "[30-05-2022 19:27:50] ERROR ARM: Call to MakeMKV failed with code: 127 (b'')" that may be the most useful. I googled this error code and found this thread: https://forum.makemkv.com/forum/viewtopic.php?p=116095 which mentions it could be a firewall issue? I'm very new to linux so not sure what is happening. I'm running ubuntu on a vmware VM.

Thanks in advance :)
```
[30-05-2022 19:26:37] INFO ARM: Starting ARM processing at 2022-05-30 19:26:37.495095
[30-05-2022 19:26:37] INFO ARM: Database is up to date
[30-05-2022 19:26:38] INFO ARM: ARM version: 2.6.0
[30-05-2022 19:26:38] INFO ARM: Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
[30-05-2022 19:26:38] INFO ARM: User is: arm
[30-05-2022 19:26:38] INFO ARM: Looking for log files older than 1 days old.
[30-05-2022 19:26:38] INFO ARM: Job: Avatar_Book_1_Disc_1
[30-05-2022 19:26:38] INFO ARM: Job #4 with PID 8234 is currently running.
[30-05-2022 19:26:38] INFO ARM: Starting Disc identification
[30-05-2022 19:26:38] INFO ARM: Mounting disc to: /mnt/dev/sr0
[30-05-2022 19:26:48] INFO ARM: Disc identified as video
[30-05-2022 19:26:48] INFO ARM: Disc title Post ident -  title:Avatar- The Last Airbender Book One- Water Disc 1 year:2018 video_type:unknown disctype: bluray
[30-05-2022 19:26:48] ERROR ARM: There are service(s) to notify
[30-05-2022 19:26:48] INFO ARM: Waiting 60 seconds for manual override.
[30-05-2022 19:27:48] INFO ARM: No manual override found.
[30-05-2022 19:27:48] INFO ARM: **** Logging ARM variables ****
[30-05-2022 19:27:48] INFO ARM: devpath: /dev/sr0
[30-05-2022 19:27:48] INFO ARM: mountpoint: /mnt/dev/sr0
[30-05-2022 19:27:48] INFO ARM: title: Avatar- The Last Airbender Book One- Water Disc 1
[30-05-2022 19:27:48] INFO ARM: year: 2018
[30-05-2022 19:27:48] INFO ARM: video_type: unknown
[30-05-2022 19:27:48] INFO ARM: hasnicetitle: False
[30-05-2022 19:27:48] INFO ARM: label: Avatar_Book_1_Disc_1
[30-05-2022 19:27:48] INFO ARM: disctype: bluray
[30-05-2022 19:27:48] INFO ARM: **** End of ARM variables ****
[30-05-2022 19:27:48] INFO ARM: **** Logging config parameters ****
[30-05-2022 19:27:48] INFO ARM: skip_transcode: True
[30-05-2022 19:27:48] INFO ARM: mainfeature: False
[30-05-2022 19:27:48] INFO ARM: minlength: 600
[30-05-2022 19:27:48] INFO ARM: maxlength: 99999
[30-05-2022 19:27:48] INFO ARM: videotype: auto
[30-05-2022 19:27:48] INFO ARM: manual_wait: True
[30-05-2022 19:27:48] INFO ARM: manual_wait_time: 60
[30-05-2022 19:27:48] INFO ARM: ripmethod: mkv
[30-05-2022 19:27:48] INFO ARM: mkv_args: 
[30-05-2022 19:27:48] INFO ARM: delrawfiles: True
[30-05-2022 19:27:48] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[30-05-2022 19:27:48] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[30-05-2022 19:27:48] INFO ARM: hb_args_dvd: --subtitle scan -F
[30-05-2022 19:27:48] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[30-05-2022 19:27:48] INFO ARM: raw_path: /home/arm/media/raw/
[30-05-2022 19:27:48] INFO ARM: transcode_path: /home/arm/media/transcode/
[30-05-2022 19:27:48] INFO ARM: completed_path: /home/arm/media/completed/
[30-05-2022 19:27:48] INFO ARM: extras_sub: extras
[30-05-2022 19:27:48] INFO ARM: emby_refresh: False
[30-05-2022 19:27:48] INFO ARM: emby_server: 
[30-05-2022 19:27:48] INFO ARM: emby_port: 8096
[30-05-2022 19:27:48] INFO ARM: notify_rip: True
[30-05-2022 19:27:48] INFO ARM: notify_transcode: True
[30-05-2022 19:27:48] INFO ARM: max_concurrent_transcodes: 0
[30-05-2022 19:27:48] INFO ARM: **** End of config parameters ****
[30-05-2022 19:27:48] INFO ARM: Checking for fstab entry.
[30-05-2022 19:27:48] INFO ARM: fstab entry is: /dev/sr0    /mnt/dev/sr0    udf,iso9660    users,noauto,exec,utf8    0    0
[30-05-2022 19:27:50] INFO ARM: Handbrake Output directory "/home/arm/media/transcode/unidentified/Avatar- The Last Airbender Book One- Water Disc 1 (2018)" already exists.
[30-05-2022 19:27:50] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/Avatar- The Last Airbender Book One- Water Disc 1 (2018)_165390287024
[30-05-2022 19:27:50] INFO ARM: Prepping MakeMkv for usage...
[30-05-2022 19:27:50] ERROR ARM: Call to MakeMKV failed with code: 127 (b'')
[30-05-2022 19:27:50] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 163, in prep_mkv
    subprocess.run(cmd, capture_output=True, shell=True, check=True)  # noqa: F841
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon info /dev/sr0' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 474, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 280, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 37, in makemkv
    prep_mkv(job)
  File "/opt/arm/arm/ripper/makemkv.py", line 180, in prep_mkv
    raise MakeMkvRuntimeError(mkv_error)
  File "/opt/arm/arm/ripper/makemkv.py", line 24, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException
[30-05-2022 19:27:50] ERROR ARM: There are service(s) to notify
```

**Comment by 1337-server** [comment]
Can you try running this in a terminal `makemkvcon`

And past the output in code block please as it messed with the repo. 

You can use code blocks with 3 backticks \`\`\` at the start and at the end of the code.\`\`\`
Like this
\`\`\`
This is code
\`\`\`

Thanks

**Comment by BobFish** [comment]
I just got this error:

```
Command 'makemkvcon' not found, but can be installed with:
sudo snap install makemkv
```

**Comment by 1337-server** [comment]
That means MakeMKV isn't installed.

Try installing it again via the steps in the wiki
