### ISSUE TITLE
Issues after installing on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by Kev1112005** [automatic-ripping-machine/automatic-ripping-machine#663]
- [ X ] I have checked the wiki
- [ X ] I have searched for similar issues

**Describe the bug**
After a fresh installation of Ubuntu 20.04.5 and ARM, I am unable to reference the History or Database tabs in ArmUI. When I do so, I get a screen that states: TypeError: paginate() takes 1 positional argument but 4 were given.

I did the install manually following the guide in the Wiki, and also tried running the script to reinstall in case I had missed a step for configuration. No dice.

**To Reproduce**
1. Fresh install of Ubuntu 20.04.5 LTS
2. Fresh install of ARM
3. Login to ArmUI, click "History" or "Database"

### Environment

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

* v2_master
commit a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d (HEAD -> v2_master, origin/v2_master, origin/HEAD)

### Log file
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/arm/arm/../arm/ui/routes.py", line 228, in database
    jobs = Job.query.order_by(db.desc(Job.job_id)).paginate(page, 100, False)
TypeError: paginate() takes 1 positional argument but 4 were given

![image](https://user-images.githubusercontent.com/30413531/212610363-230e001c-8285-4f90-86dd-841c18d9e915.png)

**Comment by Kev1112005** [comment]
Looks like Flask was running 3.X. Rips weren't starting automatically either, and after troubleshooting it looks like all I had to do was downgrade to 2.5.1 (following the steps found in the comments of #596) and rips started working. Going to reload armui in the morning and see if the history page is resolved.

**Comment by Kev1112005** [comment]
Yep, looks like restarting armui after fixing the Flask version was the issue. Doh.

**Comment by microtechno9000** [comment]
Hey @Kev1112005 , welcome to the ARM community. 

This is an error that I have seen a few users raise with Ubuntu 22.04, although your using 20.04. It appears that a newer version of SQLAlchemy has been installed or pulled in, the newer version causes issues with ARM. Can you confirm what version you are running.
`pip show SQLAlchemy`
