### ISSUE TITLE
Continue to have a heck of a time trying to get up and running

### ISSUE THREAD

**Issue by aiohdfgaiuhg** [automatic-ripping-machine/automatic-ripping-machine#672]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
Ubuntu 20.04 installer script fails

**To Reproduce**
Re-image drive with Ubuntu 20.04.0 desktop
Download 2.6.10 release
make ubuntu-20.04.sh executable and run as sudo

### Environment
Ubuntu 20.04.0 Desktop (notably not 20.04.5 LTS which I could also never get to work but think the flask version was too new)

### Log file
Installing collected packages: pip, wheel, setuptools, psutil, pyudev
  WARNING: The scripts pip, pip3, pip3.10 and pip3.8 are installed in '/home/arm/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wheel is installed in '/home/arm/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.3.1 psutil-5.9.4 pyudev-0.24.0 setuptools-66.1.0 wheel-0.38.4
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3249, in <module>
    def _initialize_master_working_set():
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3223, in _call_aside
    f(*args, **kwargs)
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3261, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 619, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 632, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/home/arm/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)

**Comment by microtechno9000** [comment]
Hi @aiohdfgaiuhg , sorry your having trouble installing and setting up ARM

The issue you found has been resolved in PR #667

**Comment by shitwolfymakes** [comment]
Closing this as fixed until the OP says otherwise

**Comment by aiohdfgaiuhg** [comment]
Can confirm - this fix solved my issue with getting started.
