### ISSUE TITLE
No title found Issue

### ISSUE THREAD

**Issue by Ivolution-dev** [automatic-ripping-machine/automatic-ripping-machine#681]
**Describe the bug**
I can't get the title and I am not able to rip anything

**To Reproduce**
1. Installed everything like in the wiki
2. insert disk

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
$ git branch
* v2_master
* $ git log -1
commit a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Author: 1337-server <sndspamfilter@gmail.com>
Date:   Mon Jun 27 18:31:48 2022 +0100

### Log file
```
[23-01-2023 10:33:44] INFO ARM: Starting ARM processing at 2023-01-23 10:33:44.921733
[23-01-2023 10:33:44] INFO ARM: Database is up to date
[23-01-2023 10:33:45] INFO ARM: ARM version: 2.6.0
[23-01-2023 10:33:45] INFO ARM: Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
[23-01-2023 10:33:45] INFO ARM: User is: arm
[23-01-2023 10:33:45] INFO ARM: Looking for log files older than 1 days old.
[23-01-2023 10:33:45] INFO ARM: Job: ANTMAN
[23-01-2023 10:33:45] INFO ARM: Job #4 with PID 7076 is currently running.
[23-01-2023 10:33:45] INFO ARM: Starting Disc identification
[23-01-2023 10:33:45] INFO ARM: Mounting disc to: /mnt/dev/sr0
[23-01-2023 10:33:48] INFO ARM: Disc identified as video
[23-01-2023 10:33:48] INFO ARM: DVD CRC64 hash is: a737ab0bf5e28715
[23-01-2023 10:33:49] INFO ARM: Disc title Post ident -  title:ANTMAN year:None video_type:unknown disctype: dvd
[23-01-2023 10:33:49] ERROR ARM: There are no service(s) to notify
[23-01-2023 10:33:49] INFO ARM: Setting umask to 0o002
[23-01-2023 10:33:49] INFO ARM: Waiting 60 seconds for manual override.
[23-01-2023 10:34:50] INFO ARM: No manual override found.
[23-01-2023 10:34:50] INFO ARM: **** Logging ARM variables ****
[23-01-2023 10:34:50] INFO ARM: devpath: /dev/sr0
[23-01-2023 10:34:50] INFO ARM: mountpoint: /mnt/dev/sr0
[23-01-2023 10:34:50] INFO ARM: title: ANTMAN
[23-01-2023 10:34:50] INFO ARM: year: None
[23-01-2023 10:34:50] INFO ARM: video_type: unknown
[23-01-2023 10:34:50] INFO ARM: hasnicetitle: False
[23-01-2023 10:34:50] INFO ARM: label: ANTMAN
[23-01-2023 10:34:50] INFO ARM: disctype: dvd
[23-01-2023 10:34:50] INFO ARM: **** End of ARM variables ****
[23-01-2023 10:34:50] INFO ARM: **** Logging config parameters ****
[23-01-2023 10:34:50] INFO ARM: skip_transcode: False
[23-01-2023 10:34:50] INFO ARM: mainfeature: False
[23-01-2023 10:34:50] INFO ARM: minlength: 600
[23-01-2023 10:34:50] INFO ARM: maxlength: 99999
[23-01-2023 10:34:50] INFO ARM: videotype: auto
[23-01-2023 10:34:50] INFO ARM: manual_wait: True
[23-01-2023 10:34:50] INFO ARM: manual_wait_time: 60
[23-01-2023 10:34:50] INFO ARM: ripmethod: backup
[23-01-2023 10:34:50] INFO ARM: mkv_args: 
[23-01-2023 10:34:50] INFO ARM: delrawfiles: True
[23-01-2023 10:34:50] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[23-01-2023 10:34:50] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[23-01-2023 10:34:50] INFO ARM: hb_args_dvd: --subtitle scan -F
[23-01-2023 10:34:50] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[23-01-2023 10:34:50] INFO ARM: raw_path: /home/arm/media/raw/
[23-01-2023 10:34:50] INFO ARM: transcode_path: /home/arm/media/transcode/
[23-01-2023 10:34:50] INFO ARM: completed_path: /home/arm/media/completed/
[23-01-2023 10:34:50] INFO ARM: extras_sub: extras
[23-01-2023 10:34:50] INFO ARM: emby_refresh: False
[23-01-2023 10:34:50] INFO ARM: emby_server: 
[23-01-2023 10:34:50] INFO ARM: emby_port: 8096
[23-01-2023 10:34:50] INFO ARM: notify_rip: True
[23-01-2023 10:34:50] INFO ARM: notify_transcode: True
[23-01-2023 10:34:50] INFO ARM: max_concurrent_transcodes: 0
[23-01-2023 10:34:50] INFO ARM: **** End of config parameters ****
[23-01-2023 10:34:50] INFO ARM: Checking for fstab entry.
[23-01-2023 10:34:50] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8  0  0
[23-01-2023 10:34:50] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/ANTMAN
[23-01-2023 10:34:50] INFO ARM: Transcode limit is disabled
[23-01-2023 10:34:50] INFO ARM: Starting BluRay/DVD transcoding - All titles
[23-01-2023 10:34:50] INFO ARM: Using HandBrake to get information on all the tracks on the disc.  This will take a few minutes...
[23-01-2023 10:35:42] ERROR ARM: Couldn't find a valid track with utf-8 encoding. Trying with cp437
[23-01-2023 10:35:42] ERROR ARM: Specific error is: Command 'HandBrakeCLI -i /dev/sr0 -t 0 --scan' returned non-zero exit status 2.
[23-01-2023 10:35:59] ERROR ARM: Couldn't find a valid track. Try running the command manually to see more specific errors.
[23-01-2023 10:35:59] ERROR ARM: Specific error is: Command 'HandBrakeCLI -i /dev/sr0 -t 0 --scan' returned non-zero exit status 2.
[23-01-2023 10:35:59] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 478, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 313, in main
    handbrake.handbrake_all(hb_in_path, hb_out_path, logfile, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 117, in handbrake_all
    get_track_info(srcpath, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 257, in get_track_info
    for line in hb:
TypeError: 'int' object is not iterable
[23-01-2023 10:35:59] ERROR ARM: There are no service(s) to notify
```

When i execute it manually:
```
root@hvn:/home/ivo# HandBrakeCLI -i /dev/sr0 -t 0
[11:48:39] Compile-time hardening features are enabled
[11:48:39] hb_init: starting libhb thread
[11:48:39] thread 7f47a63ff640 started ("libhb")
HandBrake 1.5.1 (2022030700) - Linux x86_64 - https://handbrake.fr
12 CPUs detected
Opening /dev/sr0...
[11:48:39] CPU: Common KVM processor
[11:48:39]  - logical processor count: 12
[11:48:39] hb_scan: path=/dev/sr0, title_index=0
Scanning title 1 of 1, 0.00 %disc.c:437: error opening file BDMV/index.bdmv
disc.c:437: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2652: nav_get_title_list((null)) failed
[11:48:40] bd: not a bd - trying as a stream/file instead
Scanning title 1 of 1, 0.00 %libdvdnav: DVD Title: ANTMAN
libdvdnav: DVD Serial Number: 47366D42
libdvdnav: DVD Title (Alternative): ANTMAN
libdvdnav: DVD disk reports itself with Region mask 0x00ed0000. Regions: 02 05
libdvdread: Attempting to retrieve all CSS keys
libdvdread: This can take a _long_ time, please be patient
libdvdread: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x0006e2da
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_01_1.VOB at 0x0006e36a
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_02_0.VOB at 0x0006e45a
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_02_1.VOB at 0x0006ea23
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_03_0.VOB at 0x00071073
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_03_1.VOB at 0x0009cc8d
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_04_0.VOB at 0x0009ccae
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_04_1.VOB at 0x0009ccc7
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_05_0.VOB at 0x0009ccdf
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_05_1.VOB at 0x0009ccf8
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_06_0.VOB at 0x0009cd0f
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_06_1.VOB at 0x0009cd20
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_07_1.VOB at 0x0009cfa2
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_08_1.VOB at 0x000a4ea2
libdvdread: Elapsed time 0
libdvdread: Found 8 VTS's
libdvdread: Elapsed time 0
Scanning title 1 of 1, 0.00 %[11:48:42] scan: DVD has 9 title(s)
[11:48:42] scan: scanning title 1
[11:48:42] scan: duration is 01:52:18 (6738480 ms)
[11:48:42] pgc_id: 1, pgn: 1: pgc: 0x7f47980314d0
[11:48:42] scan: checking audio 1
[11:48:42] scan: id=0x80bd, lang=English (AC3), 3cc=eng ext=1
[11:48:42] scan: checking audio 2
[11:48:42] scan: id=0x81bd, lang=Deutsch (AC3), 3cc=deu ext=1
[11:48:42] scan: checking audio 3
[11:48:42] scan: id=0x82bd, lang=italiano (AC3), 3cc=ita ext=1
[11:48:42] scan: checking audio 4
[11:48:42] scan: id=0x83bd, lang=Türkçe (AC3), 3cc=tur ext=1
[11:48:42] scan: checking subtitle 1
[11:48:42] scan: id=0x20bd, lang=English Closed Caption (Wide Screen) [VOBSUB], 3cc=eng ext=5
[11:48:42] scan: id=0x21bd, lang=English Closed Caption (Letterbox) [VOBSUB], 3cc=eng ext=5
[11:48:42] scan: checking subtitle 2
[11:48:42] scan: id=0x22bd, lang=Deutsch (Wide Screen) [VOBSUB], 3cc=deu ext=1
[11:48:42] scan: id=0x23bd, lang=Deutsch (Letterbox) [VOBSUB], 3cc=deu ext=1
[11:48:42] scan: checking subtitle 3
[11:48:42] scan: id=0x24bd, lang=italiano (Wide Screen) [VOBSUB], 3cc=ita ext=1
[11:48:42] scan: id=0x25bd, lang=italiano (Letterbox) [VOBSUB], 3cc=ita ext=1
[11:48:42] scan: checking subtitle 4
[11:48:42] scan: id=0x26bd, lang=Türkçe (Wide Screen) [VOBSUB], 3cc=tur ext=1
[11:48:42] scan: id=0x27bd, lang=Türkçe (Letterbox) [VOBSUB], 3cc=tur ext=1
[11:48:42] scan: checking subtitle 5
[11:48:42] scan: id=0x28bd, lang=Deutsch Forced (Wide Screen) [VOBSUB], 3cc=deu ext=9
[11:48:42] scan: id=0x29bd, lang=Deutsch Forced (Letterbox) [VOBSUB], 3cc=deu ext=9
[11:48:42] scan: checking subtitle 6
[11:48:42] scan: id=0x2abd, lang=italiano Forced (Wide Screen) [VOBSUB], 3cc=ita ext=9
[11:48:42] scan: id=0x2bbd, lang=italiano Forced (Letterbox) [VOBSUB], 3cc=ita ext=9
[11:48:42] scan: title 1 has 17 chapters
[11:48:42] scan: chap 1, 122800 ms
[11:48:42] scan: chap 2, 375320 ms
[11:48:42] scan: chap 3, 388080 ms
[11:48:42] scan: chap 4, 263640 ms
[11:48:42] scan: chap 5, 451200 ms
[11:48:42] scan: chap 6, 304040 ms
[11:48:42] scan: chap 7, 332520 ms
[11:48:42] scan: chap 8, 328480 ms
[11:48:42] scan: chap 9, 274280 ms
[11:48:42] scan: chap 10, 481240 ms
[11:48:42] scan: chap 11, 177000 ms
[11:48:42] scan: chap 12, 328680 ms
[11:48:42] scan: chap 13, 968400 ms
[11:48:42] scan: chap 14, 632240 ms
[11:48:42] scan: chap 15, 761200 ms
[11:48:42] scan: chap 16, 548880 ms
[11:48:42] scan: chap 17, 480 ms
[11:48:42] scan: aspect = 16:9
[11:48:42] scan: scanning title 2
[11:48:42] scan: duration is 00:00:00 (480 ms)
[11:48:42] scan: ignoring title (too short)
[11:48:42] scan: scanning title 3
[11:48:42] scan: duration is 00:00:20 (20480 ms)
[11:48:42] pgc_id: 1, pgn: 1: pgc: 0x7f4798037ee0
[11:48:42] scan: title 3 has 5 chapters
[11:48:42] scan: chap 1, 5000 ms
[11:48:42] scan: chap 2, 5000 ms
[11:48:42] scan: chap 3, 5000 ms
[11:48:42] scan: chap 4, 5000 ms
[11:48:42] scan: chap 5, 480 ms
[11:48:42] scan: aspect = 16:9
[11:48:42] scan: scanning title 4
[11:48:42] scan: duration is 00:01:28 (88120 ms)
[11:48:42] pgc_id: 5, pgn: 1: pgc: 0x7f4798039240
[11:48:42] scan: checking audio 1
[11:48:42] scan: id=0x80bd, lang=English (AC3), 3cc=eng ext=1
[11:48:42] scan: checking audio 2
[11:48:42] scan: id=0x81bd, lang=Deutsch (AC3), 3cc=deu ext=1
[11:48:42] scan: checking audio 3
[11:48:42] scan: id=0x82bd, lang=italiano (AC3), 3cc=ita ext=1
[11:48:42] scan: checking subtitle 1
[11:48:42] scan: id=0x20bd, lang=Deutsch (Wide Screen) [VOBSUB], 3cc=deu ext=1
[11:48:42] scan: id=0x21bd, lang=Deutsch (Letterbox) [VOBSUB], 3cc=deu ext=1
[11:48:42] scan: checking subtitle 2
[11:48:42] scan: id=0x22bd, lang=italiano (Wide Screen) [VOBSUB], 3cc=ita ext=1
[11:48:42] scan: id=0x23bd, lang=italiano (Letterbox) [VOBSUB], 3cc=ita ext=1
[11:48:42] scan: checking subtitle 3
[11:48:42] scan: id=0x24bd, lang=Türkçe (Wide Screen) [VOBSUB], 3cc=tur ext=1
[11:48:42] scan: id=0x25bd, lang=Türkçe (Letterbox) [VOBSUB], 3cc=tur ext=1
[11:48:42] scan: title 4 has 2 chapters
[11:48:42] scan: chap 1, 87640 ms
[11:48:42] scan: chap 2, 480 ms
[11:48:42] scan: aspect = 16:9
[11:48:42] scan: scanning title 5
[11:48:42] scan: duration is 00:01:28 (88120 ms)
[11:48:42] pgc_id: 1, pgn: 1: pgc: 0x7f4798039210
[11:48:42] scan: checking audio 1
[11:48:42] scan: id=0x80bd, lang=English (AC3), 3cc=eng ext=1
[11:48:42] scan: checking audio 2
[11:48:42] scan: id=0x81bd, lang=Deutsch (AC3), 3cc=deu ext=1
[11:48:42] scan: checking audio 3
[11:48:42] scan: id=0x82bd, lang=italiano (AC3), 3cc=ita ext=1
[11:48:42] scan: checking subtitle 1
[11:48:42] scan: id=0x20bd, lang=Deutsch (Wide Screen) [VOBSUB], 3cc=deu ext=1
[11:48:42] scan: id=0x21bd, lang=Deutsch (Letterbox) [VOBSUB], 3cc=deu ext=1
[11:48:42] scan: checking subtitle 2
[11:48:42] scan: id=0x22bd, lang=italiano (Wide Screen) [VOBSUB], 3cc=ita ext=1
[11:48:42] scan: id=0x23bd, lang=italiano (Letterbox) [VOBSUB], 3cc=ita ext=1
[11:48:42] scan: checking subtitle 3
[11:48:42] scan: id=0x24bd, lang=Türkçe (Wide Screen) [VOBSUB], 3cc=tur ext=1
[11:48:42] scan: id=0x25bd, lang=Türkçe (Letterbox) [VOBSUB], 3cc=tur ext=1
[11:48:42] scan: title 5 has 2 chapters
[11:48:42] scan: chap 1, 87640 ms
[11:48:42] scan: chap 2, 480 ms
[11:48:42] scan: aspect = 16:9
[11:48:42] scan: scanning title 6
[11:48:42] scan: duration is 00:00:29 (29320 ms)
[11:48:42] pgc_id: 1, pgn: 1: pgc: 0x7f4798039210
[11:48:42] scan: checking audio 1
[11:48:42] scan: id=0x80bd, lang=English (AC3), 3cc=eng ext=1
[11:48:42] scan: title 6 has 2 chapters
[11:48:42] scan: chap 1, 28840 ms
[11:48:42] scan: chap 2, 480 ms
[11:48:42] scan: aspect = 16:9
[11:48:42] scan: scanning title 7
[11:48:42] scan: duration is 00:00:00 (720 ms)
[11:48:42] scan: ignoring title (too short)
[11:48:42] scan: scanning title 8
[11:48:42] scan: duration is 00:00:00 (480 ms)
[11:48:42] scan: ignoring title (too short)
[11:48:42] scan: scanning title 9
[11:48:42] scan: duration is 00:00:00 (480 ms)
[11:48:42] scan: ignoring title (too short)
libdvdnav: DVD disk reports itself with Region mask 0x00ed0000. Regions: 02 05
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: Last error repeated 1 times
ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: dvdnav: Read Error, Error reading from DVD.
Scanning title 9 of 9, 50.00 %[11:48:54] scan: decoding previews for title 1
libdvdnav: DVD disk reports itself with Region mask 0x00ed0000. Regions: 02 05
[11:48:54] scan: title angle(s) 1
Scanning title 1 of 5, preview 1, 51.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: Last error repeated 1 times
ERROR: dvdnav: Read Error, Error reading from DVD.
[11:48:56] Warning: Could not read data for preview 1, skipped
[11:48:56] scan: Too few previews (0), trying harder
[11:48:56] scan: decoding previews for title 1
[11:48:56] scan: title angle(s) 1
Scanning title 1 of 5, preview 1, 51.00 %ERROR: dvdnav: Read Error, Error reading from DVD.
ERROR: dvdnav: Read Error, Error reading from DVD.
[11:49:00] Warning: Could not read data for preview 1, skipped
[11:49:00] scan: decoding previews for title 3
^[[Blibdvdread: Invalid IFO for title 6 (VTS_06_0.IFO).
Scanning title 1 of 4, preview 1, 50.00 %libdvdread: Invalid IFO for title 6 (VTS_06_0.BUP).
[11:49:00] ifoOpen failed
[11:49:00] scan: title angle(s) 1
ERROR: dvdnav: Read Error, Error reading NAV packet.
Scanning title 1 of 4, preview 7, 58.75 %[11:49:01] scan: Too few previews (0), trying harder
[11:49:01] scan: decoding previews for title 3
Scanning title 1 of 4, preview 10, 62.50 %libdvdread: Invalid IFO for title 6 (VTS_06_0.IFO).
libdvdread: Invalid IFO for title 6 (VTS_06_0.BUP).
[11:49:01] ifoOpen failed
[11:49:01] scan: title angle(s) 1
Scanning title 1 of 4, preview 1, 51.25 %ERROR: dvdnav: Read Error, Error reading NAV packet.
ERROR: Last error repeated 11 times
ERROR: dvdnav: Read Error, Error reading NAV packet.
Scanning title 1 of 4, preview 6, 57.50 %[11:49:02] scan: decoding previews for title 4
Scanning title 1 of 3, preview 1, 50.00 %libdvdread: Invalid IFO for title 7 (VTS_07_0.IFO).
Scanning title 1 of 3, preview 1, 50.00 %libdvdread: Invalid IFO for title 7 (VTS_07_0.BUP).
[11:49:02] ifoOpen failed
[11:49:02] scan: title angle(s) 1
ERROR: dvdnav: Read Error, Error reading NAV packet.
ERROR: Last error repeated 10 times
ERROR: dvdnav: Read Error, Error reading NAV packet.
Scanning title 1 of 3, preview 10, 66.67 %[11:49:03] scan: Too few previews (0), trying harder
[11:49:03] scan: decoding previews for title 4
libdvdread: Invalid IFO for title 7 (VTS_07_0.IFO).
Scanning title 1 of 3, preview 10, 66.67 %libdvdread: Invalid IFO for title 7 (VTS_07_0.BUP).
[11:49:03] ifoOpen failed
[11:49:03] scan: title angle(s) 1
Scanning title 1 of 3, preview 5, 58.33 %ERROR: dvdnav: Read Error, Error reading NAV packet.
ERROR: Last error repeated 11 times
ERROR: dvdnav: Read Error, Error reading NAV packet.
Scanning title 1 of 3, preview 10, 66.67 %[11:49:04] scan: decoding previews for title 5
libdvdread: Invalid IFO for title 7 (VTS_07_0.IFO).
Scanning title 1 of 2, preview 1, 50.00 %libdvdread: Invalid IFO for title 7 (VTS_07_0.BUP).
[11:49:04] ifoOpen failed
[11:49:04] scan: title angle(s) 1
Scanning title 1 of 2, preview 4, 60.00 %ERROR: dvdnav: Read Error, Error reading NAV packet.
ERROR: Last error repeated 11 times
ERROR: dvdnav: Read Error, Error reading NAV packet.
Scanning title 1 of 2, preview 10, 75.00 %[11:49:04] scan: Too few previews (0), trying harder
[11:49:04] scan: decoding previews for title 5
libdvdread: Invalid IFO for title 7 (VTS_07_0.IFO).
Scanning title 1 of 2, preview 10, 75.00 %libdvdread: Invalid IFO for title 7 (VTS_07_0.BUP).
[11:49:05] ifoOpen failed
[11:49:05] scan: title angle(s) 1
Scanning title 1 of 2, preview 9, 72.50 %ERROR: dvdnav: Read Error, Error reading NAV packet.
ERROR: Last error repeated 10 times
ERROR: dvdnav: Read Error, Error reading NAV packet.
[11:49:05] scan: decoding previews for title 6
libdvdread: Invalid IFO for title 2 (VTS_02_0.IFO).
Scanning title 1 of 1, preview 1, 50.00 %libdvdread: Invalid IFO for title 2 (VTS_02_0.BUP).
[11:49:06] ifoOpen failed
[11:49:06] scan: title angle(s) 1
Scanning title 1 of 1, preview 8, 90.00 %ERROR: dvdnav: Read Error, Error reading NAV packet.
ERROR: Last error repeated 10 times
ERROR: dvdnav: Read Error, Error reading NAV packet.
[11:49:06] scan: Too few previews (0), trying harder
[11:49:06] scan: decoding previews for title 6
Scanning title 1 of 1, preview 10, 100.00 %libdvdread: Invalid IFO for title 2 (VTS_02_0.IFO).
libdvdread: Invalid IFO for title 2 (VTS_02_0.BUP).
[11:49:07] ifoOpen failed
[11:49:07] scan: title angle(s) 1
Scanning title 1 of 1, preview 8, 90.00 %[11:49:07] libhb: scan thread found 0 valid title(s)
No title found.
```

I tried with multiple DVDs and none of them worked. Same Issue

**Comment by shitwolfymakes** [comment]
Ubuntu 22.04 is not supported. Please try installing ARM on a [supported OS](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki#supported-operating-systems)
