### ISSUE TITLE
🐛 missing docs/arm.yaml.sample

### ISSUE THREAD

**Issue by TheMinecraftGuyGuru** [automatic-ripping-machine/automatic-ripping-machine#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

hello, I have tried to follow the guide for manually installing ARM on Debian 11, and I noticed that for some reason the file /docs/arm.yaml.sample is missing, all the guides to make this work refer to that file, and the link in the wiki page for arm.yaml returns a 404 error.

### To Reproduce

1. view arm git
2. open docs folder
3. see missing arm.yaml.sample

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

can't get that far, but trying to install the latest one.

### Expected behavior?

the expected behavior is that the file exists

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
`docs/arm.yaml.sample` was moved to `setup/arm.yaml`

**Comment by shitwolfymakes** [comment]
Also, the Debian installation instructions are borked. Please use the docker container or ubuntu script installer

**Comment by MKE1138** [comment]
> `docs/arm.yaml.sample` was moved to `setup/arm.yaml`

Have the rest of the scripts been updated to reflect that? I'm getting the following:

Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 1, in <module>
    import arm.config
  File "/opt/arm/arm/../arm/config/__init__.py", line 1, in <module>
    from . import config  # noqa: F401
  File "/opt/arm/arm/../arm/config/config.py", line 30, in <module>
    cur_cfg = _load_config(arm_config_path)
  File "/opt/arm/arm/../arm/config/config.py", line 16, in _load_config
    with open(fp, "r") as yaml_file:
**FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/arm.yaml'**
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_arm_arm_runui.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 1, in <module>
    import arm.config
  File "/opt/arm/arm/../arm/config/__init__.py", line 1, in <module>
    from . import config  # noqa: F401
  File "/opt/arm/arm/../arm/config/config.py", line 30, in <module>
    cur_cfg = _load_config(arm_config_path)
  File "/opt/arm/arm/../arm/config/config.py", line 16, in _load_config
    with open(fp, "r") as yaml_file:
**FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/arm.yaml'**
