### ISSUE TITLE
🐋 web ui fails to start, TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by joelishness** [automatic-ripping-machine/automatic-ripping-machine#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Cannot connect to docker web ui

docker indicates constantly "starting"
```
docker ps
CONTAINER ID   IMAGE                                                        COMMAND           CREATED         STATUS                            PORTS                                       NAMES
cc50a2f41dbe   automaticrippingmachine/automatic-ripping-machine:v2_devel   "/sbin/my_init"   7 minutes ago   Up 3 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   arm-rippers
```

docker non-daemon shows "Starting web ui" loop
```
Starting web ui
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import app, db
  File "/opt/arm/arm/../arm/ui/__init__.py", line 17, in <module>
    sqlitefile = 'sqlite:///' + cfg.arm_config['DBFILE']
TypeError: 'NoneType' object is not subscriptable
```

### To Reproduce

start_arm_container.sh

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

arm-rippers and web ui should start

### Relevant log output

```shell
docker ps
CONTAINER ID   IMAGE                                                        COMMAND           CREATED         STATUS                            PORTS                                       NAMES
cc50a2f41dbe   automaticrippingmachine/automatic-ripping-machine:v2_devel   "/sbin/my_init"   7 minutes ago   Up 3 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   arm-rippers

start_arm_container.sh
Starting web ui
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import app, db
  File "/opt/arm/arm/../arm/ui/__init__.py", line 17, in <module>
    sqlitefile = 'sqlite:///' + cfg.arm_config['DBFILE']
TypeError: 'NoneType' object is not subscriptable
```

### Anything else?

Was working fine until trascode dir filled up.
I could not abandon the jobs (got error message).
Deleted the jobs, then removed files from raw and transcode directories.

Upgraded host (Ubuntu 22.04) and docker (v2_devel), then current issue.
Tried downgrading the host (only 5 packages were updated), but issue remains.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joelishness** [comment]
Hello, I figured it out, my config/arm.yaml file was corrupted.
Think I tried to save the config (from the web ui) while the drive was full, resulting in empty arm.yaml

I reconstructed arm.yaml and now working normally again
