### ISSUE TITLE
Error with bcrypt

### ISSUE THREAD

**Issue by MKE1138** [automatic-ripping-machine/automatic-ripping-machine#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

No UI is available at LAN IP:8080.

```
sudo systemctl status armui
[sudo] password for mike: 
● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-03-28 16:06:09 EDT; 1s ago
    Process: 3378 ExecStartPre=/bin/bash -xc /usr/bin/systemctl is-active --quiet armui.service && exit 1 || exit 0 (code=exited,>
    Process: 3380 ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py (code=exited, status=1/FAILURE)
   Main PID: 3380 (code=exited, status=1/FAILURE)
```

/home/arm/logs/WebUI.log:

```
home/arm/logs$ cat WebUI.log 
+ /usr/bin/systemctl is-active --quiet armui.service
+ exit 0
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 16, in <module>
    import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
```

### To Reproduce

Installed arm using the link: https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation

Tried 
```
sudo apt-get install build-essential libffi-dev python3-dev
pip3 install bcrypt
```
Followed by reboot, error persists.

```
ln -s /etc/.abcde.conf /etc/arm/config/abcde.conf
ln: failed to create symbolic link '/etc/arm/config/abcde.conf': File exists
```

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

Settings page does not load.

### Expected behavior?

sudo systemctl status armui would not return the error

### Relevant log output

```shell
/home/arm/logs$ cat WebUI.log 
+ /usr/bin/systemctl is-active --quiet armui.service
+ exit 0
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 16, in <module>
    import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
+ /usr/bin/systemctl is-active --quiet armui.service
+ exit 0
```

### Anything else?

Refer to https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/592
and https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/587

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MKE1138** [comment]
Was a dumbass, installed via docker.
