### ISSUE TITLE
🐛 Alembic upgrade and downgrade 'Working outside of application context.'

### ISSUE THREAD

**Issue by microtechno9000** [automatic-ripping-machine/automatic-ripping-machine#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Current configuration for the alembic .env file is missing something. Unable to run any of the alembic commands 'alembic upgrade 1' for example.

No impact to the operation of ARM; however, does effect the modification of the database and usability for Devs during database changes.

### To Reproduce

in /opt/arm/arm/migrations
run  $alembic upgrade 1
or  $alembic downgrade 1

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.27
420fa125d276e5e4c441f2532394bf717cee713b
(on a branch 'notifications', although issue has been present for multiple versions of ARM)

### Expected behavior?

alembic upgraded or downgraded the database

### Relevant log output

```shell
$alembic upgrade 1
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mtech/Projects/automatic-ripping-machine/arm/migrations/./env.py", line 21, in <module>
    current_app.config.get('SQLALCHEMY_DATABASE_URI'))
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 278, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 407, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/flask/globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.


$alembic downgrade 1
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 366, in downgrade
    script.run_env()
  File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mtech/Projects/automatic-ripping-machine/arm/migrations/./env.py", line 21, in <module>
    current_app.config.get('SQLALCHEMY_DATABASE_URI'))
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 278, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 407, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/flask/globals.py", line 47, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Even when this works i get `FAILED: Can't locate revision identified by '1'
`

**Comment by 1337-server** [comment]
**arm/arm/migrations/env.py**
```python
from __future__ import with_statement
from alembic import context
from sqlalchemy import engine_from_config, pool
import sys
import os
# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
# fileConfig(config.config_file_name)
# logger = logging.getLogger('alembic.env')

# add your model's MetaData object here
# for 'autogenerate' support
# from myapp import mymodel
# target_metadata = mymodel.Base.metadata
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from arm.ui import app, db
config.set_main_option('sqlalchemy.url',
                       app.config.get('SQLALCHEMY_DATABASE_URI'))
target_metadata = app.extensions['migrate'].db.metadata


# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.

# flake8: noqa: W291,E122,E128

def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url)

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    # this callback is used to prevent an auto-migration from being generated
    # when there are no changes to the schema
    # reference: https://alembic.zzzcomputing.com/en/latest/cookbook.html
    def process_revision_directives(context, revision, directives):
        if getattr(config.cmd_opts, 'autogenerate', False):
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                logger.info('No changes in schema detected.')

    engine = engine_from_config(config.get_section(config.config_ini_section),
                                prefix='sqlalchemy.',
                                poolclass=pool.NullPool)

    connection = engine.connect()
    context.configure(connection=connection,
                      target_metadata=target_metadata,
                      process_revision_directives=process_revision_directives,
                      **app.extensions['migrate'].configure_args)

    try:
        with context.begin_transaction():
            context.run_migrations()
    finally:
        connection.close()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()

```

**Comment by microtechno9000** [comment]
Did some digging, ARM is using flask_migrate to manage alembic. Running the below causes an out of context issue, similar to the above. Linked PR fixes this issue.

alembic now linked to the ARM app context and able to run migrations

```
 $flask db current
[2023-06-04 14:20:54,333] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2023-06-04 14:20:54,578] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 2e0dc31fcb2e
[2023-06-04 14:20:54,619] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
[2023-06-04 14:20:54,619] DEBUG ARM: utils.arm_db_check Database is current. Head: 2e0dc31fcb2eDB: 2e0dc31fcb2e
[2023-06-04 14:20:54,623] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f8d930ed870>) (id=1) (bootstrap_skin=spacelab) (index_refresh=10) (notify_refresh=6500) (language=en) (use_icons=True) (save_remote_images=True) (database_limit=200) 
[2023-06-04 14:20:54,627] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 2e0dc31fcb2e
[2023-06-04 14:20:54,628] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
[2023-06-04 14:20:54,629] DEBUG ARM: utils.arm_db_check Database is current. Head: 2e0dc31fcb2eDB: 2e0dc31fcb2e
[2023-06-04 14:20:54,629] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f8d930ed870>) (id=1) (bootstrap_skin=spacelab) (index_refresh=10) (notify_refresh=6500) (language=en) (use_icons=True) (save_remote_images=True) (database_limit=200) 
Usage: flask db current [OPTIONS]
Try 'flask db current --help' for help.

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

```
