### ISSUE TITLE
🐛 Title Matching too aggressive, prevents ripping "Fast & Furious" if "The Fast and The Furious" has been ripped

### ISSUE THREAD

**Issue by TallPatrick** [automatic-ripping-machine/automatic-ripping-machine#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [ ] I'm using the latest release

### Describe the bug?

The Fast Saga has very similar names of movies in the series, particularly the first and 4th movies.  The names are very similar if you strip out all the normally ignorable words like "The" and "And".  This, I believe, is leading to the bug where ARM is not ripping one when I have ripped the other.

I have a workaround where I can delete whichever one I rip first from my local database, and the other will rip.

Also, I'm ripping discs from the blu-ray box set, so the release year being the same for the blu-ray versions might also be contributing to this issue.

### To Reproduce

1. Setup Docker Image
2. Rip "The Fast and The Furious" (The first movie in the Fast saga)
3. Insert disc for "Fast & Furious" (The Fourth move in the Fast saga)

Actual Result: Disc does not rip

Expected result: Disc does rip

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.29

### Expected behavior?

System is able to determine that "The Fast and the Furious" is a different movie from "Fast & Furious"

### Relevant log output

```shell
Logs provided no useful output.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TallPatrick** [comment]
I was able to reproduce this error and here's what the newest log file looks like.  Note that this is the full log, there is no "Traceback below" visible from the web interface:

[05-09-2023 07:26:47] INFO ARM: Database is up to date
[05-09-2023 07:26:47] INFO ARM: ************* Starting ARM processing at 2023-05-09 07:26:47.619614 *************
[05-09-2023 07:26:49] INFO ARM: Branch: main - Commit: d466bb1
[05-09-2023 07:26:49] INFO ARM: ARM version: 2.6.29
[05-09-2023 07:26:49] INFO ARM: Python version: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
[05-09-2023 07:26:49] INFO ARM: User is: arm
[05-09-2023 07:26:49] INFO ARM: Looking for log files older than 1 days old.
[05-09-2023 07:26:49] INFO ARM: Checking path /home/arm/logs/ for old log files...
[05-09-2023 07:26:49] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[05-09-2023 07:26:49] INFO ARM: Job: FAST_AND_FURIOUS
[05-09-2023 07:26:49] INFO ARM: Job #89 with PID 5528 is currently running.
[05-09-2023 07:26:49] INFO ARM: Job #90 with PID 84675 is currently running.
[05-09-2023 07:26:49] INFO ARM: Starting Disc identification
[05-09-2023 07:26:49] INFO ARM: Mounting disc to: /mnt/dev/sr1
[05-09-2023 07:26:49] INFO ARM: Mounting disc was successful
[05-09-2023 07:26:56] INFO ARM: Disc identified as video
[05-09-2023 07:26:56] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.

**Comment by microtechno9000** [comment]
Thanks for posting this issue, so we can get some more data can you set the log level to DEBUG and run it again. This can be set in the arm.yaml config or from the settings page.

LOGLEVEL: "DEBUG"

**Comment by TallPatrick** [comment]
I enabled debug logs like you suggested and here's what I got:


[05-10-2023 15:18:06] DEBUG ARM: utils.check_db_version Head is: 2e0dc31fcb2e
[05-10-2023 15:18:06] DEBUG ARM: utils.check_db_version Database version is: 2e0dc31fcb2e
[05-10-2023 15:18:06] INFO ARM: utils.check_db_version Database is up to date
[05-10-2023 15:18:06] DEBUG ARM: utils.database_adder Trying to add User
[05-10-2023 15:18:06] DEBUG ARM: utils.database_adder successfully written User to the database
[05-10-2023 15:18:06] INFO ARM: main.<module> ************* Starting ARM processing at 2023-05-10 15:18:06.468050 *************
[05-10-2023 15:18:06] DEBUG ARM: utils.database_adder Trying to add Job
[05-10-2023 15:18:06] DEBUG ARM: utils.database_adder successfully written Job to the database
[05-10-2023 15:18:07] DEBUG ARM: DriveUtils.update_drive_job Updating drive [/dev/sr1] current job, with id [92]
[05-10-2023 15:18:07] DEBUG ARM: DriveUtils.update_drive_job Database update with new Job ID to associated drive
[05-10-2023 15:18:07] DEBUG ARM: utils.database_adder Trying to add Config
[05-10-2023 15:18:07] DEBUG ARM: utils.database_adder successfully written Config to the database
[05-10-2023 15:18:07] INFO ARM: utils.get_git_commit Branch: main - Commit: d466bb1
[05-10-2023 15:18:07] INFO ARM: main.<module> ARM version: 2.6.29
[05-10-2023 15:18:07] INFO ARM: main.<module> Python version: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
[05-10-2023 15:18:07] INFO ARM: main.<module> User is: arm
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Looking for log files older than 1 days old.
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Checking path /home/arm/logs/ for old log files...
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Deleting log file: arm.log
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Deleting log file: FAST6_NA_168360392109.log
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Deleting log file: TFATF_168360331669.log
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Deleting log file: FAST_AND_FURIOUS.log
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Checking path /home/arm/logs/progress for old log files...
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Deleting log file: 89.log
[05-10-2023 15:18:07] INFO ARM: logger.clean_up_logs Deleting log file: 91.log
[05-10-2023 15:18:07] INFO ARM: main.<module> Job: FAST_AND_FURIOUS
[05-10-2023 15:18:07] INFO ARM: utils.clean_old_jobs Job #92 with PID 224 is currently running.
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ******************* Logging udev attributes *******************
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params DEVLINKS:/dev/dvdrw /dev/disk/by-label/FAST_AND_FURIOUS /dev/cdrw /dev/disk/by-path/pci-0000:02:1b.0-usb-0:1:1.0-scsi-0:0:0:0 /dev/dvd /dev/disk/by-id/usb-PIONEER_BD-RW_BDR-XS07U_1343021622801223-0:0 /dev/disk/by-uuid/8cbb64827bdaff01
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:1e.0/0000:02:1b.0/usb3/3-1/3-1:1.0/host3/target3:0:0/3:0:0:0/block/sr1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params DEVTYPE:disk
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params DISKSEQ:23
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_BUS:usb
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_BD:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_BD_R:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_BD_RE:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_CD:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_CD_R:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_CD_RW:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_RW:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_PLUS_R_DL:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_R:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RAM:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_DVD_RW:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_BD:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_SESSION_COUNT:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_STATE:complete
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MEDIA_TRACK_COUNT_DATA:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MRW:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_CDROM_MRW_W:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FOR_SEAT:block-pci-0000_02_1b_0-usb-0_1_1_0-scsi-0_0_0_0
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_LABEL:FAST_AND_FURIOUS
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_LABEL_ENC:FAST_AND_FURIOUS
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_TYPE:udf
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_USAGE:filesystem
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_UUID:8cbb64827bdaff01
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_UUID_ENC:8cbb64827bdaff01
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_FS_VERSION:2.50
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_INSTANCE:0:0
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_MODEL:BD-RW_BDR-XS07U
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_MODEL_ENC:BD-RW\x20\x20BDR-XS07U
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_MODEL_ID:017a
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_PATH:pci-0000:02:1b.0-usb-0:1:1.0-scsi-0:0:0:0
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_PATH_TAG:pci-0000_02_1b_0-usb-0_1_1_0-scsi-0_0_0_0
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_REVISION:1.02
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_SERIAL:PIONEER_BD-RW_BDR-XS07U_1343021622801223-0:0
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_SERIAL_SHORT:1343021622801223
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_TYPE:cd
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_USB_DRIVER:usb-storage
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_USB_INTERFACES::080250:
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_USB_INTERFACE_NUM:00
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_VENDOR:PIONEER
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_VENDOR_ENC:PIONEER\x20
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ID_VENDOR_ID:08e4
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params MAJOR:11
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params MINOR:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params SUBSYSTEM:block
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params SYSTEMD_MOUNT_DEVICE_BOUND:1
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params TAGS::seat:systemd:uaccess:
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params USEC_INITIALIZED:34199596
[05-10-2023 15:18:07] DEBUG ARM: main.log_udev_params ******************* End udev attributes *******************
[05-10-2023 15:18:07] INFO ARM: main.main Starting Disc identification
[05-10-2023 15:18:07] DEBUG ARM: identify.identify Identify Entry point --- job ----
[05-10-2023 15:18:07] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr1
[05-10-2023 15:18:08] INFO ARM: identify.check_if_mounted Mounting disc was successful
[05-10-2023 15:18:13] DEBUG ARM: models.get_disc_type Found: /mnt/dev/sr1/BDMV
[05-10-2023 15:18:13] INFO ARM: identify.identify Disc identified as video
[05-10-2023 15:18:13] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
[05-10-2023 15:18:13] DEBUG ARM: utils.database_adder Trying to add Notifications
[05-10-2023 15:18:13] DEBUG ARM: utils.database_adder successfully written Notifications to the database
[05-10-2023 15:18:13] DEBUG ARM: models.eject Failed to unmount /dev/sr1
[05-10-2023 15:18:19] DEBUG ARM: models.eject Failed to eject /dev/sr1

**Comment by microtechno9000** [comment]
thanks, will check through the code and the log

**Comment by 1337-server** [comment]
Does the notification give any more info ?

ARMs errors are slightly bugged at the moment, meaning some errors will only log to the notifications and not the job log.

**Comment by TallPatrick** [comment]
nah, there's nothing else in the notification after the "See traceback below for details."

**Comment by TallPatrick** [comment]
Somehow missed this comment.  next I get a break in DVD ripping I will give that a try.

**Comment by 1337-server** [comment]
Not sure if this is the same error, but when running the same(ish) discs, I get this error.
```
[07-09-2023 13:03:01] ERROR ARM: main.<module> normalize() argument 2 must be str, not None
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 202, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 93, in main
    identify.identify(job)
  File "/opt/arm/arm/ripper/identify.py", line 58, in identify
    res = identify_bluray(job)
  File "/opt/arm/arm/ripper/identify.py", line 99, in identify_bluray
    bluray_title = unicodedata.normalize('NFKD', bluray_title).encode('ascii', 'ignore').decode()
TypeError: normalize() argument 2 must be str, not None
```


I ripped `The Fast and The Furious` then tried to rip `Fast & Furious` and got that error.

Will dig into this later but it should be a simple fix.
