### ISSUE TITLE
🐛 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by kimzrn** [automatic-ripping-machine/automatic-ripping-machine#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Error when trying to rip
MakeMKV error out
'utf-8' codec can't decode

### To Reproduce

Debien 12 on metal. ( i belive it was the same error on debien 11 and ubuntu 22.04)
Install according to wiki, docker pull from hub.

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

v.2.6.60
I think I've had the error on older versions to

### Expected behavior?

Rip should have started

### Relevant log output

```shell
[07-16-2023 19:39:17] INFO ARM: Using MakeMKV to get information on all the tracks on the disc. This will take a few minutes...
[07-16-2023 19:39:47] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: 'utf-8' codec can't decode byte 0xff in position 339: invalid start byte
[07-16-2023 19:39:47] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 69, in makemkv
    get_track_info(mdisc, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 214, in get_track_info
    mkv = subprocess.check_output(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 339: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 202, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 109, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[07-16-2023 19:39:47] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

there was no problem when I used the same DVD in MakeMKV on my windows 10 laptop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaud7of8** [comment]
I had this problem for a while, tried new installs, copying the Dockerfile from a working install and manually building, all with the error about 'utf-8' codec can't decode.
It turned out to be that while installing I connected to a network that had DNS filtering on it.  My guess is that the while installing, even though I selected to install all third-party drivers, something that helps decode the utf-8 was not installed.  I did a fresh install connecting to a network without any DNS filtering and after changing the backup method from mkv to backup, a.r.m. ran as expected.  I realize this may be a very narrow use case/solution, but maybe it will help someone esle.

**Comment by kimzrn** [comment]
Thanks for the tips but it did not work for me. Thread it no Debien 12, Debien 11 and ubuntu 22.04 server now also. Get the same error when chancing to backup mode.

**Comment by kimzrn** [comment]
This turned out being a problem with one of the drivers. I tested all de drivs with makemkv outside of docker and had no problems.

**Comment by kimzrn** [comment]
I dont think it has anything to do with drivers. It was working fin in gui on the same os. So I think it has something to do with docker og makemkv cli.

I installed proxmox and trying emulate different hardware and shutdown individual ports. And on the same install when I shutdown the sata port for that disk drive the error disappeared and it works fine. When I moved the drive to another sata port the problem returned.
So my suggestion is to start with one drive to test and add drivs one at a time until you find the problematic one.

Maybe install a gui and makemkv on it and test if that will work.

**Comment by joelishness** [comment]
Hello,
I just had the same issue occur (I am using docker image).
Failed rip log is attached.
[POLICE_STATE.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/13694989/POLICE_STATE.log)


Also found another user posting about it on makemkv forum:
https://forum.makemkv.com/forum/viewtopic.php?t=31915
Seemed like too much of a coincidence that we are all using ARM.

I was able to resolve it entering the container:
`docker exec -it arm-rippers bash`

Then edit the following file:
`vim /opt/arm/arm/ripper/makemkv.py`

And change...
Line 49 from:
`        ).decode("utf-8")`
to:
`        ).decode("ISO-8859-1")`

And line 218 from:
`        ).decode("utf-8").splitlines()`

to:
`        ).decode("ISO-8859-1").splitlines()`



Got the hint to try the above from here:
https://stackoverflow.com/questions/19699367/for-line-in-results-in-unicodedecodeerror-utf-8-codec-cant-decode-byte

(not submitting a pull request with this change because I do not know enough about why/how this works, or the implications of making this change, etc)

**Comment by joelishness** [comment]
Hello, I had to implement the above workaround again today:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/901#issuecomment-1859053143

Figured I would condense it to a one-liner to make it easy:
`docker exec -it arm-rippers sed -i 's/utf-8/ISO-8859-1/g' /opt/arm/arm/ripper/makemkv.py`
