### ISSUE TITLE
HandBrake Exited with no title found

### ISSUE THREAD

**Issue by DaBlubber** [automatic-ripping-machine/automatic-ripping-machine#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The complete procedure stopps with fatal error when i try to ripp my BlueRay Disc
See the complete Log attached
[WASABI_BD.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/12377761/WASABI_BD.log)

### To Reproduce

1. I insert a BlueRay Disc
2. The ARM is starting

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

i am using the latest arm docker image from docker hub
A.R.M version: 2.6.60
Python version: 3.8.10
7e9dfcb5d34b419bf1e0bdd9cb394774804e9717

### Expected behavior?

The run dont stop with fatal error und finish succesfully

### Relevant log output

```shell
Encoding: task 2 of 2, 100.00 % (46.87 fps, avg 24.35 fps, ETA 00h00m02s)[08:32:34] work: average encoding speed for job is 24.352230 fps
[08:32:34] comb detect: heavy 489 | light 1560 | uncombed 132946 | total 134995
[08:32:34] decomb: deinterlaced 489 | blended 1560 | unfiltered 132946 | total 134995
[08:32:34] vfr: 134995 frames output, 0 dropped and 0 duped for CFR/PFR
[08:32:34] vfr: lost time: 0 (0 frames)
[08:32:34] vfr: gained time: 0 (0 frames) (0 not accounted for)

Encoding: task 2 of 2, 100.00 % (46.87 fps, avg 24.35 fps, ETA 00h00m02s)[08:32:34] dca-decoder done: 527852 frames, 0 decoder errors
[08:32:34] dca-decoder done: 527852 frames, 0 decoder errors
[08:32:34] h264-decoder done: 134995 frames, 0 decoder errors
[08:32:34] sync: got 134995 frames, 134994 expected
[08:32:34] sync: framerate min 23.976 fps, max 23.976 fps, avg 23.976 fps
x264 [info]: frame I:2281  Avg QP:18.50  size:145116
x264 [info]: frame P:41621 Avg QP:21.05  size: 58193
x264 [info]: frame B:91093 Avg QP:21.87  size: 28830
x264 [info]: consecutive B-frames:  9.3%  1.3%  2.4% 86.9%
x264 [info]: mb I  I16..4:  2.4% 93.7%  4.0%
x264 [info]: mb P  I16..4:  0.8% 12.4%  0.6%  P16..4: 51.6% 20.9%  8.8%  0.0%  0.0%    skip: 4.9%
x264 [info]: mb B  I16..4:  0.1%  1.5%  0.1%  B16..8: 52.8%  8.5%  1.5%  direct: 9.9%  skip:25.9%  L0:45.8% L1:48.3% BI: 5.9%
x264 [info]: 8x8 transform intra:90.9% inter:77.4%
x264 [info]: direct mvs  spatial:100.0% temporal:0.0%
x264 [info]: coded y,uvDC,uvAC intra: 91.0% 78.0% 33.5% inter: 44.0% 38.9% 1.0%
x264 [info]: i16 v,h,dc,p: 34% 16%  8% 43%
x264 [info]: i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  9%  7%  8% 11% 15% 14% 13% 12% 11%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12%  7%  3% 10% 15% 16% 13% 12% 11%
x264 [info]: i8c dc,h,v,p: 34% 25% 22% 18%
x264 [info]: Weighted P-Frames: Y:2.7% UV:1.7%
x264 [info]: ref P L0: 46.0% 12.1% 23.0%  9.3%  8.2%  1.3%  0.0%
x264 [info]: ref B L0: 72.1% 19.0%  6.8%  2.2%
x264 [info]: ref B L1: 93.3%  6.7%
x264 [info]: kb/s:7643.22
[08:32:34] mux: track 0, 134995 frames, 5379234279 bytes, 7643.05 kbps, fifo 1024
[08:32:34] mux: track 1, 263927 frames, 115005313 bytes, 163.40 kbps, fifo 2048
[08:32:34] mux: track 2, 175950 frames, 450432000 bytes, 639.99 kbps, fifo 2048
[08:32:34] Finished work at: Fri Aug 18 08:32:34 2023

[08:32:34] libhb: work result = 0

Encode done!
HandBrake has exited.

[18-08-2023 08:32:35] INFO ARM: Transcoding file @eaDir to '/home/arm/media/transcode/unidentified/Wasabi (2011)/@eaDir.mkv'
[08:32:35] Compile-time hardening features are enabled
[08:32:35] qsv: not available on this system
[08:32:35] vcn: not available on this system
Cannot load libnvidia-encode.so.1
[08:32:35] hb_init: starting libhb thread
[08:32:35] thread 7fa4b67bd700 started ("libhb")
HandBrake 1.6.1 (2023081600) - Linux x86_64 - https://handbrake.fr
10 CPUs detected
Opening /home/arm/media/raw/Wasabi/@eaDir...
[08:32:35] CPU: QEMU Virtual CPU version 2.5+
[08:32:35]  - logical processor count: 10
[08:32:35] Intel Quick Sync Video support: no
[08:32:35] hb_scan: path=/home/arm/media/raw/Wasabi/@eaDir, title_index=1
disc.c:437: error opening file BDMV/index.bdmv
disc.c:437: error opening file BDMV/BACKUP/index.bdmv
[08:32:35] bd: not a bd - trying as a stream/file instead
libdvdread: Couldn't find device name.
libdvdread: DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[08:32:35] dvd: not a dvd - trying as a stream/file instead
[08:32:35] hb_stream_open: open /home/arm/media/raw/Wasabi/@eaDir failed
[08:32:35] scan: unrecognized file type
[08:32:35] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.
libdvdread: Can't open file VIDEO_TS.IFO.

[18-08-2023 08:32:35] ERROR ARM: Handbrake encoding of file @eaDir failed with code: 2(b'')
[18-08-2023 08:32:35] ERROR ARM: Command 'nice HandBrakeCLI -i /home/arm/media/raw/Wasabi/@eaDir -o '/home/arm/media/transcode/unidentified/Wasabi (2011)/@eaDir.mkv' --preset "HQ 1080p30 Surround" --subtitle scan -F --subtitle-burned --audio-lang-list de--all-audio >> /home/arm/logs/WASABI_BD.log 2>&1' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/handbrake.py", line 222, in handbrake_mkv
    hand_break_output = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nice HandBrakeCLI -i /home/arm/media/raw/Wasabi/@eaDir -o '/home/arm/media/transcode/unidentified/Wasabi (2011)/@eaDir.mkv' --preset "HQ 1080p30 Surround" --subtitle scan -F --subtitle-burned --audio-lang-list de--all-audio >> /home/arm/logs/WASABI_BD.log 2>&1' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 202, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 109, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 70, in rip_visual_media
    start_transcode(job, logfile, hb_in_path, hb_out_path, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 119, in start_transcode
    handbrake.handbrake_mkv(hb_in_path, hb_out_path, logfile, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 231, in handbrake_mkv
    raise subprocess.CalledProcessError(hb_error.returncode, cmd)
subprocess.CalledProcessError: Command 'nice HandBrakeCLI -i /home/arm/media/raw/Wasabi/@eaDir -o '/home/arm/media/transcode/unidentified/Wasabi (2011)/@eaDir.mkv' --preset "HQ 1080p30 Surround" --subtitle scan -F --subtitle-burned --audio-lang-list de--all-audio >> /home/arm/logs/WASABI_BD.log 2>&1' returned non-zero exit status 2.
[18-08-2023 08:32:35] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

i tried it more then one time but the error is the same all the time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DaBlubber** [comment]
I found a misatake i did with language parameters. but with change back to default same error:
--audio-lang-list de--all-audio -> --audio-lang-list eng --all-audio
